import { useMemo, useState } from "react";
import { Alert } from "react-native";
import { useStore } from "../../../state/useStore";
import { type ClipVersion, type SongIdea } from "../../../types";
import { extractClipVersionNumber, getBaseClipTitle } from "../../../utils";

// ── lineage helpers ────────────────────────────────────────────────────────

function getLineageRoot(clips: ClipVersion[], clipId: string): ClipVersion | null {
  let current = clips.find((c) => c.id === clipId);
  while (current?.parentClipId) {
    const parent = clips.find((c) => c.id === current!.parentClipId);
    if (!parent) break;
    current = parent;
  }
  return current ?? null;
}

/**
 * BFS from lineageRootId — collects every clip in the thread where
 * isTitleAutoGenerated !== false (undefined counts as auto-generated for
 * backward compat with clips created before the flag existed).
 * Excludes the clip that was just renamed.
 */
function getAllAutoNamedLineageClips(
  clips: ClipVersion[],
  rootId: string,
  excludeId: string
): ClipVersion[] {
  const result: ClipVersion[] = [];

  const root = clips.find((c) => c.id === rootId);
  if (root && root.id !== excludeId && root.isTitleAutoGenerated !== false) {
    result.push(root);
  }

  const queue: string[] = [rootId];
  while (queue.length > 0) {
    const parentId = queue.shift()!;
    for (const clip of clips) {
      if (clip.parentClipId === parentId) {
        queue.push(clip.id);
        if (clip.id !== excludeId && clip.isTitleAutoGenerated !== false) {
          result.push(clip);
        }
      }
    }
  }
  return result;
}

function deriveLineageTitle(clip: ClipVersion, newBase: string): string {
  const vNum = extractClipVersionNumber(clip.title);
  return vNum != null ? `${newBase} v${vNum}` : newBase;
}

type RenamePromptInfo = {
  ideaId: string;
  newBase: string;
  autoNamed: ClipVersion[];
};

// ── hook ───────────────────────────────────────────────────────────────────

export function useSongClipEditing(selectedIdea: SongIdea | null) {
  const [editingClipId, setEditingClipId] = useState<string | null>(null);
  const [editingClipDraft, setEditingClipDraft] = useState("");
  const [editingClipNotesDraft, setEditingClipNotesDraft] = useState("");
  const [notesSheetClipId, setNotesSheetClipId] = useState<string | null>(null);

  const currentIdeaId = selectedIdea?.id ?? null;

  const notesSheetClip = useMemo(
    () =>
      notesSheetClipId && selectedIdea
        ? selectedIdea.clips.find((clip) => clip.id === notesSheetClipId) ?? null
        : null,
    [notesSheetClipId, selectedIdea]
  );

  function openNotesSheet(clip: ClipVersion) {
    setEditingClipDraft(clip.title);
    setEditingClipNotesDraft(clip.notes || "");
    setNotesSheetClipId(clip.id);
  }

  /**
   * Commits the title/notes change to the store and returns rename-prompt info
   * if other auto-named clips in the lineage need updating. Returns null when
   * no prompt is needed (title unchanged, no siblings, etc.).
   */
  function commitClipTitleSave(targetClipId: string): RenamePromptInfo | null {
    if (!currentIdeaId || !selectedIdea) {
      console.warn("[renameThread] early exit — no ideaId or selectedIdea", { currentIdeaId, hasIdea: !!selectedIdea });
      return null;
    }

    const clip = selectedIdea.clips.find((c) => c.id === targetClipId);
    const newTitle = editingClipDraft.trim() || "Untitled Clip";
    const newNotes = editingClipNotesDraft.trim();

    console.log("[renameThread] commitClipTitleSave", {
      targetClipId,
      clipFound: !!clip,
      clipTitle: clip?.title,
      clipAutoFlag: clip?.isTitleAutoGenerated,
      newTitle,
      totalClips: selectedIdea.clips.length,
    });

    useStore.getState().updateIdeas((ideas) =>
      ideas.map((idea) =>
        idea.id !== currentIdeaId
          ? idea
          : {
              ...idea,
              clips: idea.clips.map((c) =>
                c.id === targetClipId
                  ? { ...c, title: newTitle, notes: newNotes, isTitleAutoGenerated: false }
                  : c
              ),
            }
      )
    );

    if (!clip || newTitle === clip.title) {
      console.log("[renameThread] skipping — clip not found or title unchanged", { clipFound: !!clip, titleMatch: clip?.title === newTitle });
      return null;
    }

    const lineageRoot = getLineageRoot(selectedIdea.clips, targetClipId);
    console.log("[renameThread] lineageRoot", { rootId: lineageRoot?.id, rootTitle: lineageRoot?.title });
    if (!lineageRoot) return null;

    const autoNamed = getAllAutoNamedLineageClips(
      selectedIdea.clips,
      lineageRoot.id,
      targetClipId
    );
    console.log("[renameThread] autoNamed", autoNamed.map((c) => ({ id: c.id, title: c.title, auto: c.isTitleAutoGenerated })));
    if (autoNamed.length === 0) return null;

    return { ideaId: currentIdeaId, newBase: getBaseClipTitle(newTitle), autoNamed };
  }

  /** Shows the rename-siblings Alert. Call this after any sheet/modal has finished dismissing. */
  function showRenamePrompt(info: RenamePromptInfo) {
    const { ideaId, newBase, autoNamed } = info;
    const n = autoNamed.length;
    const clipWord = n === 1 ? "clip" : "clips";
    const example = autoNamed[0];
    const exampleNew = deriveLineageTitle(example, newBase);
    const moreLine = n > 1 ? `, and ${n - 1} more` : "";

    Alert.alert(
      "Update thread names?",
      `Rename ${n} other ${clipWord} in this thread to match?\n\n"${example.title}" → "${exampleNew}"${moreLine}`,
      [
        { text: "Keep existing", style: "cancel" },
        {
          text: `Update ${n} ${clipWord}`,
          onPress: () => {
            useStore.getState().updateIdeas((ideas) =>
              ideas.map((idea) =>
                idea.id !== ideaId
                  ? idea
                  : {
                      ...idea,
                      clips: idea.clips.map((c) => {
                        if (!autoNamed.some((d) => d.id === c.id)) return c;
                        return { ...c, title: deriveLineageTitle(c, newBase) };
                      }),
                    }
              )
            );
          },
        },
      ]
    );
  }

  function saveNotesSheet() {
    if (!notesSheetClipId) return;
    const clipId = notesSheetClipId;
    const promptInfo = commitClipTitleSave(clipId);
    // Close the sheet first so the Alert doesn't fight a dismissing BottomSheet.
    setNotesSheetClipId(null);
    if (promptInfo) {
      console.log("[renameThread] queuing prompt (notes sheet), delay 400ms");
      setTimeout(() => {
        console.log("[renameThread] firing prompt now (notes sheet)");
        showRenamePrompt(promptInfo);
      }, 400);
    }
  }

  function beginEditingClip(clip: ClipVersion) {
    setEditingClipId(clip.id);
    setEditingClipDraft(clip.title);
    setEditingClipNotesDraft(clip.notes || "");
  }

  function saveEditingClip(clipId: string) {
    const promptInfo = commitClipTitleSave(clipId);
    setEditingClipId(null);
    if (promptInfo) {
      // Small delay so the inline edit UI collapses before the Alert appears.
      console.log("[renameThread] queuing prompt (inline edit), delay 100ms");
      setTimeout(() => {
        console.log("[renameThread] firing prompt now (inline edit)");
        showRenamePrompt(promptInfo);
      }, 100);
    }
  }

  function cancelEditing() {
    setEditingClipId(null);
  }

  function closeNotesSheet() {
    setNotesSheetClipId(null);
  }

  return {
    editingClipId,
    editingClipDraft,
    setEditingClipDraft,
    editingClipNotesDraft,
    setEditingClipNotesDraft,
    notesSheetClip,
    openNotesSheet,
    saveNotesSheet,
    beginEditingClip,
    saveEditingClip,
    cancelEditing,
    closeNotesSheet,
  };
}
