import { useCallback, useEffect , useRef } from "react";
import { AppAlert } from "../../common/AppAlert";
import { actionIcons } from "../../common/actionIcons";
import { useStore } from "../../../state/useStore";
import { appActions } from "../../../state/actions";
import { buildDefaultIdeaTitle, ensureUniqueIdeaTitle } from "../../../utils";
import { buildDraftThreadRenames } from "../../../domain/clipLineageTitles";
import type { IdeaStatus, SongIdea, Workspace } from "../../../types";
import { useTranslation } from "react-i18next";

type UseSongEditFlowParams = {
  navigation: any;
  selectedIdea: SongIdea | null | undefined;
  selectedIdeaId: string | null;
  activeWorkspaceId: string | null;
  isEditMode: boolean;
  setIsEditMode: (value: boolean) => void;
  draftTitle: string;
  draftStatus: IdeaStatus;
  draftCompletion: number;
};

export function useSongEditFlow({
  navigation,
  selectedIdea,
  selectedIdeaId,
  activeWorkspaceId,
  isEditMode,
  setIsEditMode,
  draftTitle,
  draftStatus,
  draftCompletion,
}: UseSongEditFlowParams) {
  const { t } = useTranslation();
  const hasChanges = useCallback(() => {
    if (!selectedIdea) return false;
    return (
      draftTitle.trim() !== selectedIdea.title ||
      draftStatus !== selectedIdea.status ||
      draftCompletion !== selectedIdea.completionPct
    );
  }, [draftCompletion, draftStatus, draftTitle, selectedIdea]);

  const handleSave = useCallback(() => {
    if (!selectedIdeaId || !selectedIdea) return;
    const state = useStore.getState();
    // Read at save time: subscribing the page to the whole library for this one
    // title-uniqueness check re-rendered it on every write anywhere.
    const activeWorkspace = state.workspaces.find((workspace) => workspace.id === activeWorkspaceId);
    const fallbackTitle = ensureUniqueIdeaTitle(
      buildDefaultIdeaTitle(),
      activeWorkspace?.ideas.filter((idea) => idea.id !== selectedIdeaId).map((idea) => idea.title) ?? []
    );
    const finalTitle = draftTitle.trim() || fallbackTitle;
    const titleChanged = finalTitle !== selectedIdea.title;
    const statusChanged = draftStatus !== selectedIdea.status;
    const completionChanged = draftCompletion !== selectedIdea.completionPct;
    const meaningfulSongChange = statusChanged || completionChanged;

    // A draft made from several clips carries one thread titled after the
    // draft's placeholder name; naming the sketch names the thread too —
    // "Title", "Title v2", … (founder, 2026-10-03). Only on the draft's first
    // save: after that, take titles are the takes' own business.
    const threadRenames =
      selectedIdea.isDraft && titleChanged && draftTitle.trim()
        ? buildDraftThreadRenames(selectedIdea.clips, finalTitle)
        : null;

    if (titleChanged && !meaningfulSongChange && !selectedIdea.isDraft) {
      state.renameIdeaPreservingActivity(selectedIdeaId, finalTitle);
    } else {
      state.updateIdeas((ideas) =>
        ideas.map((idea) =>
          idea.id === selectedIdeaId
            ? {
                ...idea,
                title: finalTitle,
                clips: threadRenames
                  ? idea.clips.map((clip) =>
                      threadRenames.has(clip.id) ? { ...clip, title: threadRenames.get(clip.id)! } : clip
                    )
                  : idea.clips,
                // Only an actual title CHANGE counts as naming it. Saving the
                // sheet to change the stage must not silently claim the title
                // was chosen — that would promote an untouched import to serif.
                isTitleAutoGenerated: titleChanged
                  ? !draftTitle.trim()
                  : idea.isTitleAutoGenerated,
                status: draftStatus,
                completionPct: draftCompletion,
                isDraft: false,
              }
            : idea
        )
      );
    }

    if (selectedIdea.kind === "project") {
      if (selectedIdea.isDraft) {
        state.logIdeaActivity(selectedIdeaId, "created", "song-save");
      } else if (meaningfulSongChange) {
        state.logIdeaActivity(selectedIdeaId, "updated", "song-save");
      }
    }

    setIsEditMode(false);
  }, [
    activeWorkspaceId,
    draftCompletion,
    draftStatus,
    draftTitle,
    selectedIdea,
    selectedIdeaId,
    setIsEditMode,
  ]);

  // Set while a confirmed draft discard is leaving the screen, so the
  // beforeRemove guard below lets that one removal through instead of
  // re-prompting against the stale closure (2026-09-10).
  const discardingDraftRef = useRef(false);

  const handleCancel = useCallback((onDiscardAction?: () => void) => {
    const isDraft = selectedIdea?.isDraft;
    if (!hasChanges() && !isDraft) {
      setIsEditMode(false);
      onDiscardAction?.();
      return;
    }

    AppAlert.destructive(
      isDraft ? t("songDetail.removeUnsavedTitle") : t("songDetail.discardChangesTitle"),
      isDraft ? t("songDetail.removeUnsavedBody") : t("songDetail.discardChangesBody"),
      () => {
        setIsEditMode(false);
        if (isDraft) {
          // A discarded draft has no page to stay on: leave first, then drop
          // it, so the sketch screen never renders "not found" for an idea
          // that was deleted underneath it.
          discardingDraftRef.current = true;
          appActions.deleteSelectedIdea(true);
          if (onDiscardAction) {
            onDiscardAction();
          } else if (navigation.canGoBack?.()) {
            navigation.goBack();
          }
          return;
        }
        onDiscardAction?.();
      },
      { confirmLabel: isDraft ? t("songDetail.yesRemove") : t("songDetail.yesDiscard"), icon: actionIcons.discard }
    );
  }, [hasChanges, navigation, selectedIdea?.isDraft, setIsEditMode]);

  useEffect(() => {
    const unsubscribe = navigation.addListener("beforeRemove", (event: any) => {
      if (discardingDraftRef.current) return;
      if (!isEditMode && !selectedIdea?.isDraft) return;
      event.preventDefault();
      handleCancel(() => navigation.dispatch(event.data.action));
    });
    return unsubscribe;
  }, [handleCancel, isEditMode, navigation, selectedIdea?.isDraft]);

  return {
    hasChanges,
    handleSave,
    handleCancel,
  };
}
