import { useMemo, useState } from "react";
import {
  buildLineageTitle,
  buildLineageTitlePlan,
} from "../../../clipLineageTitles";
import {
  showLineageRenamePrompt,
  type LineageRenamePromptInfo,
} from "../../../clipLineageRenamePrompt";
import { useStore } from "../../../state/useStore";
import { type ClipVersion, type SongIdea } from "../../../types";

function getCurrentStoreIdea(ideaId: string | null): SongIdea | null {
  if (!ideaId) return null;
  const { activeWorkspaceId, workspaces } = useStore.getState();
  const workspace = workspaces.find((w) => w.id === activeWorkspaceId);
  return workspace?.ideas.find((idea) => idea.id === ideaId) ?? null;
}

// ── hook ───────────────────────────────────────────────────────────────────

export function useSongClipEditing(selectedIdea: SongIdea | null) {
  const [editingClipId, setEditingClipId] = useState<string | null>(null);
  const [editingClipDraft, setEditingClipDraft] = useState("");
  const [editingClipNotesDraft, setEditingClipNotesDraft] = useState("");
  const [notesSheetClipId, setNotesSheetClipId] = useState<string | null>(null);

  const currentIdeaId = selectedIdea?.id ?? null;

  const notesSheetClip = useMemo(
    () =>
      notesSheetClipId && selectedIdea
        ? selectedIdea.clips.find((clip) => clip.id === notesSheetClipId) ?? null
        : null,
    [notesSheetClipId, selectedIdea]
  );

  function openNotesSheet(clip: ClipVersion) {
    setEditingClipDraft(clip.title);
    setEditingClipNotesDraft(clip.notes || "");
    setNotesSheetClipId(clip.id);
  }

  /**
   * Commits the title/notes change to the store and returns rename-prompt info
   * if other clips in the lineage need updating. Returns null when no prompt
   * is needed.
   */
  function commitClipTitleSave(targetClipId: string): LineageRenamePromptInfo | null {
    const currentIdea = getCurrentStoreIdea(currentIdeaId);
    if (!currentIdeaId || !currentIdea) {
      console.warn("[renameThread] early exit — no live idea", {
        currentIdeaId,
        hasSelectedIdea: !!selectedIdea,
        hasLiveIdea: !!currentIdea,
      });
      return null;
    }

    const plan = buildLineageTitlePlan(currentIdea.clips, targetClipId, editingClipDraft);
    if (!plan) {
      console.log("[renameThread] skipping — clip not found", { targetClipId });
      return null;
    }

    const clip = plan.clip;
    const newNotes = editingClipNotesDraft.trim();
    const lineageSize = plan.orderedClips.length;

    console.log("[renameThread] commitClipTitleSave", {
      targetClipId,
      clipFound: !!clip,
      clipTitle: clip.title,
      clipAutoFlag: clip.isTitleAutoGenerated,
      draftTitle: plan.draftTitle,
      savedTitle: plan.savedTitle,
      newBase: plan.newBase,
      previousBase: plan.previousBase,
      totalClips: currentIdea.clips.length,
      selectedIdeaClipCount: selectedIdea?.clips.length ?? null,
    });

    useStore.getState().updateIdeas((ideas) =>
      ideas.map((idea) =>
        idea.id !== currentIdeaId
          ? idea
          : {
              ...idea,
              clips: idea.clips.map((c) =>
                c.id === targetClipId
                  ? { ...c, title: plan.savedTitle, notes: newNotes, isTitleAutoGenerated: false }
                  : c
              ),
            }
      )
    );

    console.log("[renameThread] lineage", {
      rootId: plan.lineage?.root.id,
      rootTitle: plan.lineage?.root.title,
      lineageSize,
      targetIndex: plan.targetIndex,
      isEditingRoot: plan.isEditingRoot,
    });
    if (!plan.lineage || lineageSize <= 1 || plan.targetIndex < 0) {
      console.log("[renameThread] skipping — not a lineage thread", {
        savedTitle: plan.savedTitle,
        previousTitle: clip.title,
        titleMatch: clip.title === plan.savedTitle,
      });
      return null;
    }

    console.log("[renameThread] lineage clips", plan.orderedClips.map((item, index) => ({
      id: item.id,
      title: item.title,
      index,
      auto: item.isTitleAutoGenerated,
      previousExpectedTitle: buildLineageTitle(plan.previousBase, index),
      nextExpectedTitle: buildLineageTitle(plan.newBase, index),
    })));

    const renames = plan.renames;
    console.log("[renameThread] renames", renames.map(({ clip, nextTitle }) => ({
      id: clip.id,
      title: clip.title,
      nextTitle,
      auto: clip.isTitleAutoGenerated,
    })));
    if (renames.length === 0) {
      console.log("[renameThread] skipping — no lineage renames needed", {
        savedTitle: plan.savedTitle,
        previousTitle: clip.title,
        titleMatch: clip.title === plan.savedTitle,
      });
      return null;
    }

    return { ideaId: currentIdeaId, renames };
  }

  function saveNotesSheet() {
    if (!notesSheetClipId) return;
    const clipId = notesSheetClipId;
    const promptInfo = commitClipTitleSave(clipId);
    // Close the sheet first so the Alert doesn't fight a dismissing BottomSheet.
    setNotesSheetClipId(null);
    if (promptInfo) {
      console.log("[renameThread] queuing prompt (notes sheet), delay 400ms");
      setTimeout(() => {
        console.log("[renameThread] firing prompt now (notes sheet)");
        showLineageRenamePrompt(promptInfo);
      }, 400);
    }
  }

  function beginEditingClip(clip: ClipVersion) {
    setEditingClipId(clip.id);
    setEditingClipDraft(clip.title);
    setEditingClipNotesDraft(clip.notes || "");
  }

  function saveEditingClip(clipId: string) {
    const promptInfo = commitClipTitleSave(clipId);
    setEditingClipId(null);
    if (promptInfo) {
      // Small delay so the inline edit UI collapses before the Alert appears.
      console.log("[renameThread] queuing prompt (inline edit), delay 100ms");
      setTimeout(() => {
        console.log("[renameThread] firing prompt now (inline edit)");
        showLineageRenamePrompt(promptInfo);
      }, 100);
    }
  }

  function cancelEditing() {
    setEditingClipId(null);
  }

  function closeNotesSheet() {
    setNotesSheetClipId(null);
  }

  return {
    editingClipId,
    editingClipDraft,
    setEditingClipDraft,
    editingClipNotesDraft,
    setEditingClipNotesDraft,
    notesSheetClip,
    openNotesSheet,
    saveNotesSheet,
    beginEditingClip,
    saveEditingClip,
    cancelEditing,
    closeNotesSheet,
  };
}
