import { isTitleAutoNamed, looksMachineNamed } from "../titleNaming";
import { buildDefaultIdeaTitle } from "../../utils";

/**
 * The earned serif (revised 2026-09-23): a title earns Lora by READING as a name,
 * wherever it was typed. Machine names — timestamps, recorder filenames, our own
 * defaults — stay in quiet Jakarta. An in-app rename always counts as a name.
 */
describe("looksMachineNamed", () => {
  it.each([
    "New Recording 7",
    "Recording 12",
    "Recording (2)",
    "Voice 001",
    "REC_0042",
    "Voice memo 3",
    "Memo",
    "Untitled",
    "20260921_143012",
    "2026-09-21 14.30.12",
    "audio-1758470000000-3-abc12",
    "WhatsApp Audio 2026-09-21 at 14.30.12",
    "PTT-20260921-WA0004",
    "Idea 3",
    "Idea 3 v2",
    "Recovered · 1:54 PM Sep 23rd",
    "Import 1:54 PM Sep 23rd",
    "1:54 PM Sep 23rd",
    "10:58 28 ביולי",
    "   ",
  ])("treats %j as a machine name", (title) => {
    expect(looksMachineNamed(title)).toBe(true);
  });

  it.each([
    "Chorus idea 2",
    "Porch swing melody",
    "Porch swing melody v9",
    "sample-01",
    "Bridge (slow version)",
    "Recording of the sea",
    "מנגינה למרפסת",
    "Take 2 was better",
  ])("treats %j as a name", (title) => {
    expect(looksMachineNamed(title)).toBe(false);
  });

  it("recognises today's default title exactly, in either language", () => {
    const createdAt = Date.now();
    expect(looksMachineNamed(buildDefaultIdeaTitle(createdAt), createdAt)).toBe(true);
  });
});

describe("isTitleAutoNamed", () => {
  it("an import with a human filename earns the serif without a rename", () => {
    expect(isTitleAutoNamed({ title: "chorus hook", isTitleAutoGenerated: true })).toBe(false);
  });

  it("an import still wearing a recorder filename does not", () => {
    expect(isTitleAutoNamed({ title: "New Recording 4", isTitleAutoGenerated: true })).toBe(true);
  });

  it("an in-app rename always counts, even to a machine-looking title", () => {
    expect(isTitleAutoNamed({ title: "Recording 3", isTitleAutoGenerated: false })).toBe(false);
  });

  it("legacy records with no flag are judged by their title", () => {
    expect(isTitleAutoNamed({ title: "Idea 1" })).toBe(true);
    expect(isTitleAutoNamed({ title: "Midnight riff" })).toBe(false);
  });
});
