import { findLineageForClip, type ClipLineage } from "./clipGraph";
import type { ClipVersion } from "../types";
import { getBaseClipTitle } from "../utils";

export type LineageRenameTarget = {
  clip: ClipVersion;
  nextTitle: string;
};

export type LineageTitlePlan = {
  clip: ClipVersion;
  draftTitle: string;
  savedTitle: string;
  newBase: string;
  previousBase: string;
  lineage: ClipLineage | null;
  orderedClips: ClipVersion[];
  targetIndex: number;
  isEditingRoot: boolean;
  renames: LineageRenameTarget[];
};

export function buildLineageTitle(baseTitle: string, lineageIndex: number): string {
  return lineageIndex === 0 ? baseTitle : `${baseTitle} v${lineageIndex + 1}`;
}

export function getLineageVersionClips(lineage: ClipLineage): ClipVersion[] {
  const rootId = lineage.root.id;
  return [
    lineage.root,
    ...lineage.clipsOldestToNewest.filter((clip) => clip.id !== rootId),
  ];
}

export function buildLineageTitlePlan(
  clips: ClipVersion[],
  targetClipId: string,
  rawDraftTitle: string
): LineageTitlePlan | null {
  const clip = clips.find((candidate) => candidate.id === targetClipId);
  if (!clip) return null;

  const draftTitle = rawDraftTitle.trim() || "Untitled Clip";
  const newBase = getBaseClipTitle(draftTitle) || draftTitle;
  const previousBase = getBaseClipTitle(clip.title) || clip.title;
  const lineage = findLineageForClip(clips, targetClipId);
  const orderedClips = lineage ? getLineageVersionClips(lineage) : [];
  const targetIndex = orderedClips.findIndex((candidate) => candidate.id === targetClipId);
  const isLineageThread = orderedClips.length > 1 && targetIndex >= 0;
  const savedTitle = isLineageThread ? buildLineageTitle(newBase, targetIndex) : draftTitle;
  const isEditingRoot = lineage?.root.id === targetClipId;

  const renames =
    isLineageThread && lineage
      ? orderedClips
          .map((candidate, index) => ({
            clip: candidate,
            index,
            nextTitle: buildLineageTitle(newBase, index),
          }))
          .filter(({ clip: candidate, index, nextTitle }) => {
            if (candidate.id === targetClipId) return false;
            if (candidate.title === nextTitle) return false;
            if (isEditingRoot) return true;
            if (candidate.isTitleAutoGenerated !== false) return true;

            const previousExpectedTitle = buildLineageTitle(previousBase, index);
            return candidate.title === previousExpectedTitle;
          })
          .map(({ clip: candidate, nextTitle }) => ({ clip: candidate, nextTitle }))
      : [];

  return {
    clip,
    draftTitle,
    savedTitle,
    newBase,
    previousBase,
    lineage,
    orderedClips,
    targetIndex,
    isEditingRoot,
    renames,
  };
}
