import { i18n } from "../i18n/instance";

/**
 * Does a title read as a NAME, or as something a machine stamped on a file?
 *
 * This is what earns the serif (design-system §earned serif, revised 2026-09-23). The
 * rule used to be "named inside SongNook": every import stayed in quiet Jakarta even
 * when the musician had named it in Voice Memos. Now the title itself decides —
 * a timestamp, a recorder's "New Recording 7", a bare date, or one of our own default
 * titles is a machine name; anything else is a name, wherever it was typed.
 *
 * `isTitleAutoGenerated === false` (an in-app rename) always wins: a musician who
 * deliberately calls a take "Recording 3" gets the serif for it.
 */

const EN_TIMESTAMP = /^\d{1,2}:\d{2}\s?(?:AM|PM)\s+[A-Za-z]{3}\s+\d{1,2}(?:st|nd|rd|th)?$/i;
const HE_TIMESTAMP = /^\d{1,2}:\d{2}\s+\d{1,2}\s+ב\S+$/;
// Our own generated shapes: default take titles, recovered takes, nameless imports.
const OUR_DEFAULTS = [/^Idea \d+$/i, /^רעיון \d+$/, /^(?:Recovered|שוחזר)\s?·/, /^Import\s/];
// What voice recorders and messaging apps call a file nobody named.
const RECORDER_FILENAMES = [
  /^(?:new\s+)?(?:recording|voice|memo|audio|rec|clip|track|untitled|note|sound|record|voice\s*memo)[\s_\-#.]*\(?\d*\)?$/i,
  /^rec[\s_-]?\d+/i,
  /^(?:audio|clip|recovered|import|recording|voice)[_-]\d{6,}/i,
  /^(?:whatsapp|telegram)\s+(?:audio|ptt)/i,
  /^ptt-\d/i,
  /^\d[\d\s_\-:.T]*$/, // 20260921_143012, 2026-09-21 14.30.12
];

function stripVersionSuffix(title: string): string {
  return title.replace(/\s+v\d+$/i, "").trim();
}

export function looksMachineNamed(title: string, createdAt?: number): boolean {
  const trimmed = title.trim();
  if (!trimmed) return true;
  if (createdAt !== undefined && isDefaultIdeaTitle(trimmed, createdAt)) return true;
  // "Chorus hook v3" is a child take of a named clip; "Idea 2 v3" is not.
  const base = stripVersionSuffix(trimmed);
  if (EN_TIMESTAMP.test(base) || HE_TIMESTAMP.test(base)) return true;
  if (OUR_DEFAULTS.some((pattern) => pattern.test(base))) return true;
  return RECORDER_FILENAMES.some((pattern) => pattern.test(base));
}

/** The one rule both cards and the primary-take strip apply. */
export function isTitleAutoNamed(entry: {
  title: string;
  createdAt?: number;
  isTitleAutoGenerated?: boolean;
}): boolean {
  if (entry.isTitleAutoGenerated === false) return false;
  return looksMachineNamed(entry.title, entry.createdAt);
}

function buildDefaultIdeaTitleIn(language: "en" | "he", timestamp: number) {
  const date = new Date(timestamp);
  const day = date.getDate();
  if (language === "he") {
    // Hebrew has no ordinal suffix and reads 24-hour: "10:58 · 28 ביולי".
    const time = date.toLocaleTimeString("he-IL", { hour: "2-digit", minute: "2-digit", hour12: false });
    const month = date.toLocaleDateString("he-IL", { month: "long" });
    return `${time} ${day} ב${month}`;
  }
  const suffix = day === 1 || day === 21 || day === 31 ? "st"
    : day === 2 || day === 22 ? "nd"
    : day === 3 || day === 23 ? "rd"
    : "th";
  const time = date.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  }).replace(" ", "");
  const month = date.toLocaleDateString("en-US", { month: "short" });
  return `${time} ${month} ${day}${suffix}`;
}

/** The auto title a new capture gets, in the app's current language. */
export const buildDefaultIdeaTitle = (timestamp = Date.now()) =>
  buildDefaultIdeaTitleIn(i18n.language === "he" ? "he" : "en", timestamp);

/**
 * True when `title` is still the unedited auto-generated timestamp.
 *
 * Checks BOTH languages on purpose: a title written in English and then read
 * after the user switches to Hebrew is still machine-supplied, and comparing
 * against only the current language would silently promote every old capture to
 * a "named" one — earning it a serif it never earned.
 */
export function isDefaultIdeaTitle(title: string, createdAt: number) {
  return (
    title === buildDefaultIdeaTitleIn("en", createdAt) ||
    title === buildDefaultIdeaTitleIn("he", createdAt)
  );
}
