/**
 * Word Finder — rhyming dictionary + thesaurus for lyric writing.
 *
 * Backed by the Datamuse API (https://www.datamuse.com/api/). Datamuse is keyless
 * until Jan 1 2027; after that every request needs an app-level API key, which must
 * NOT ship in the client bundle. The migration path is a thin proxy (see
 * server/word-proxy/) that injects the key server-side — when it's deployed, point
 * WORD_SERVICE_BASE_URL at it and nothing else in the app changes.
 */

export const WORD_SERVICE_BASE_URL = "https://api.datamuse.com";

/**
 * Hebrew meaning-based lookups (synonyms, opposites, …) have no equivalent API,
 * so they're generated by a small LLM behind this Cloudflare Worker (holds the
 * key, caches for a year). Sound-based Hebrew modes (rhymes) are planned against
 * Dicta's Charuzit and not wired yet. See server/word-he/.
 */
export const WORD_HE_SERVICE_BASE_URL = "https://songnook-word-he.bmostudio-dev.workers.dev";

const MAX_RESULTS = 40;
const REQUEST_TIMEOUT_MS = 8000;

export type WordLookupMode =
  | "rhymes"
  | "near"
  | "similar"
  | "related"
  | "homophones"
  | "consonance"
  | "soundsLike"
  | "opposite"
  | "synonyms"
  | "describe"
  | "kinds"
  | "parts";

export type WordSuggestion = {
  word: string;
  score: number;
  numSyllables?: number;
  /** Optional register/usage label (Hebrew LLM results only — e.g. "ספרותי"). */
  tag?: string;
};

type ModeConfig = {
  label: string;
  /** Datamuse query parameter carrying the looked-up word. */
  param: string;
  description: string;
  /** Sound-alike modes group results by syllable count for meter matching. */
  groupBySyllables?: boolean;
};

export const WORD_LOOKUP_MODES: Record<WordLookupMode, ModeConfig> = {
  // Quick modes — always visible in the sheet's segmented row.
  rhymes: { label: "Rhymes", param: "rel_rhy", description: "Perfect rhymes.", groupBySyllables: true },
  near: { label: "Near", param: "rel_nry", description: "Near rhymes — close but not exact.", groupBySyllables: true },
  similar: { label: "Similar", param: "ml", description: "Words with a similar meaning." },
  related: { label: "Related", param: "rel_trg", description: "Words the theme brings to mind." },
  // Extended modes — behind the ••• picker, grouped by goal.
  homophones: {
    label: "Homophones",
    param: "rel_hom",
    description: "Same sound, different word — course, coarse.",
    groupBySyllables: true,
  },
  consonance: {
    label: "Consonance",
    param: "rel_cns",
    description: "Same consonant bones — sample, simple.",
    groupBySyllables: true,
  },
  soundsLike: {
    label: "Sounds like",
    param: "sl",
    description: "Close in sound, loose on spelling.",
    groupBySyllables: true,
  },
  opposite: { label: "Opposites", param: "rel_ant", description: "Antonyms — for contrast lines." },
  synonyms: { label: "Synonyms", param: "rel_syn", description: "Strict synonyms only." },
  describe: { label: "Describing words", param: "rel_jjb", description: "Adjectives for it — ocean: deep, vast." },
  kinds: { label: "Kinds of it", param: "rel_gen", description: "More specific — bird: sparrow, heron." },
  parts: { label: "Parts of it", param: "rel_com", description: "What it contains — car: dashboard." },
};

/** The four quick modes shown as segments. */
export const WORD_LOOKUP_MODE_ORDER: WordLookupMode[] = ["rhymes", "near", "similar", "related"];

/**
 * Which lookup modes the Hebrew LLM worker serves, mapped to its mode names.
 * Meaning-based modes (incl. homophones) route here; the sound-based rhyme
 * modes (rhymes/near/consonance/soundsLike) are Charuzit's job and unlisted.
 */
const HEBREW_WORKER_MODES: Partial<Record<WordLookupMode, string>> = {
  similar: "similar",
  related: "related",
  synonyms: "synonyms",
  opposite: "opposites",
  describe: "describing",
  kinds: "kinds",
  parts: "parts",
  homophones: "homophones",
};

/** The worker mode name for a lookup mode, or null if Hebrew can't serve it yet. */
export function hebrewWorkerMode(mode: WordLookupMode): string | null {
  return HEBREW_WORKER_MODES[mode] ?? null;
}

/** Extended modes for the ••• picker, grouped by the writer's goal. */
export const EXTENDED_WORD_MODE_GROUPS: { title: string; modes: WordLookupMode[] }[] = [
  { title: "Sound", modes: ["homophones", "consonance", "soundsLike"] },
  { title: "Meaning", modes: ["opposite", "synonyms"] },
  { title: "Imagery", modes: ["describe", "kinds", "parts"] },
];

// A theme character: a letter of either script the app supports, plus the
// intra-word joiners (apostrophes/hyphens, and Hebrew geresh/gershayim/maqaf).
// Everything else is stripped. Latin is lowercased; Hebrew has no case.
const THEME_STRIP = /[^a-zא-ת'’\-־׳״]/g;
const THEME_HAS_LETTER = /[a-zא-ת]/;

/**
 * Normalize a free-typed theme ("love, leaving  town") into topic words — at
 * most five. Script-aware: English themes feed Datamuse's `topics`, Hebrew
 * themes feed the LLM worker's `themes`; a lookup only ever hits one backend.
 */
export function sanitizeThemeWords(theme: string): string[] {
  return theme
    .toLowerCase()
    .split(/[,\s]+/)
    .map((word) => word.replace(THEME_STRIP, ""))
    .filter((word) => THEME_HAS_LETTER.test(word))
    .slice(0, 5);
}

export type SyllableGroup = { syllables: number | null; suggestions: WordSuggestion[] };

/**
 * Bucket suggestions by syllable count (ascending, unknown last) so a writer
 * matching a melody can scan same-length words together. Relevance order is
 * preserved within each bucket.
 */
export function groupBySyllableCount(suggestions: WordSuggestion[]): SyllableGroup[] {
  const buckets = new Map<number | null, WordSuggestion[]>();
  for (const suggestion of suggestions) {
    const key = suggestion.numSyllables ?? null;
    const bucket = buckets.get(key);
    if (bucket) bucket.push(suggestion);
    else buckets.set(key, [suggestion]);
  }
  return [...buckets.entries()]
    .sort(([a], [b]) => {
      if (a === null) return 1;
      if (b === null) return -1;
      return a - b;
    })
    .map(([syllables, grouped]) => ({ syllables, suggestions: grouped }));
}

/** Characters that count as part of a lyric word (apostrophes for contractions, hyphens). */
const WORD_CHAR = /[\p{L}\p{N}'’\-־׳״]/u;

export function isEnglishLookupWord(word: string): boolean {
  return /[A-Za-z]/.test(word) && !/[\u0590-\u05FF\u0600-\u08FF]/.test(word);
}

export function isHebrewLookupWord(word: string): boolean {
  return /[\u0590-\u05FF]/.test(word) && !/[A-Za-z]/.test(word);
}

export type WordRange = { word: string; start: number; end: number };

/**
 * Find the word at a cursor position or inside a selection. A collapsed cursor
 * expands to the word around it; a selection is trimmed to its word characters.
 * Returns null when there is no word at the position.
 */
export function extractWordRange(text: string, start: number, end: number): WordRange | null {
  const length = text.length;
  let from = Math.max(0, Math.min(start, length));
  let to = Math.max(from, Math.min(end, length));

  if (from === to) {
    // Collapsed cursor: expand outward to word boundaries. A cursor sitting just
    // after a word (the common "just typed it" position) still finds that word.
    if (from > 0 && !WORD_CHAR.test(text[from] ?? "") && WORD_CHAR.test(text[from - 1])) {
      from -= 1;
      to = from;
    }
    while (from > 0 && WORD_CHAR.test(text[from - 1])) from -= 1;
    while (to < length && WORD_CHAR.test(text[to])) to += 1;
  } else {
    // Selection: trim leading/trailing non-word characters.
    while (from < to && !WORD_CHAR.test(text[from])) from += 1;
    while (to > from && !WORD_CHAR.test(text[to - 1])) to -= 1;
  }

  const word = text.slice(from, to).trim();
  if (!word || !/\p{L}/u.test(word)) return null;
  return { word, start: from, end: to };
}

/**
 * Insert a picked word into lyric text. Replaces [start, end) when the range is a
 * real selection, otherwise inserts at the caret with spaces added where the word
 * would otherwise fuse with its neighbors. Returns the new text and caret position.
 */
export type WordInsertion = {
  text: string;
  caret: number;
  /** Range of the inserted word itself, excluding any smart-added spaces —
   * for a transient highlight over exactly the word. */
  wordStart: number;
  wordEnd: number;
};

export function insertWordIntoText(
  text: string,
  start: number,
  end: number,
  word: string
): WordInsertion {
  const length = text.length;
  const from = Math.max(0, Math.min(start, length));
  const to = Math.max(from, Math.min(end, length));
  const before = text.slice(0, from);
  const after = text.slice(to);

  let leading = "";
  let trailing = "";
  if (from === to) {
    if (before.length > 0 && !/\s$/.test(before)) leading = " ";
    if (after.length > 0 && WORD_CHAR.test(after[0])) trailing = " ";
  }
  const insert = `${leading}${word}${trailing}`;
  const wordStart = from + leading.length;
  const wordEnd = wordStart + word.length;

  return { text: before + insert + after, caret: from + insert.length, wordStart, wordEnd };
}

/**
 * Place a picked suggestion into text, given the editor's current selection.
 * An explicit selection is replaced (trimmed to its word characters); a caret
 * strictly inside a word replaces the whole word rather than splitting it;
 * otherwise the word is inserted at the caret with smart spacing. Shared by
 * every editor that hosts the Word Finder so picking behaves identically.
 */
export function applyPickedWord(
  text: string,
  selStart: number,
  selEnd: number,
  word: string
): WordInsertion {
  let start = selStart;
  let end = selEnd;
  const range = extractWordRange(text, selStart, selEnd);
  if (range && (selEnd > selStart || (range.start < selStart && selStart < range.end))) {
    start = range.start;
    end = range.end;
  }
  return insertWordIntoText(text, start, end, word);
}

export type WordLookupOptions = {
  baseUrl?: string;
  /** Free-typed theme words — biases any mode via Datamuse's topics param. */
  theme?: string;
};

export function buildWordLookupUrl(
  mode: WordLookupMode,
  word: string,
  options?: WordLookupOptions
): string {
  const config = WORD_LOOKUP_MODES[mode];
  const params = new URLSearchParams();
  params.set(config.param, word.trim().toLowerCase());
  const topics = sanitizeThemeWords(options?.theme ?? "");
  if (topics.length > 0) params.set("topics", topics.join(","));
  params.set("max", String(MAX_RESULTS));
  // Syllable counts let the UI (and future meter tools) speak a songwriter's language.
  params.set("md", "s");
  return `${options?.baseUrl ?? WORD_SERVICE_BASE_URL}/words?${params.toString()}`;
}

export function parseWordSuggestions(payload: unknown): WordSuggestion[] {
  if (!Array.isArray(payload)) return [];
  const suggestions: WordSuggestion[] = [];
  for (const entry of payload) {
    if (!entry || typeof entry !== "object") continue;
    const word = (entry as { word?: unknown }).word;
    if (typeof word !== "string" || !word.trim()) continue;
    const score = (entry as { score?: unknown }).score;
    const numSyllables = (entry as { numSyllables?: unknown }).numSyllables;
    suggestions.push({
      word: word.trim(),
      score: typeof score === "number" ? score : 0,
      numSyllables: typeof numSyllables === "number" ? numSyllables : undefined,
    });
  }
  return suggestions;
}

export class WordLookupOfflineError extends Error {
  constructor() {
    super("Word lookup needs a connection");
    this.name = "WordLookupOfflineError";
  }
}

/** The Hebrew LLM worker was rate-limited (429) — a transient "try again". */
export class WordLookupBusyError extends Error {
  constructor() {
    super("Word finder is busy");
    this.name = "WordLookupBusyError";
  }
}

/** Shared fetch: timeout, external-abort passthrough, and the offline mapping. */
async function fetchWordServiceJson(url: string, signal?: AbortSignal): Promise<unknown> {
  const timeoutController = new AbortController();
  const timeout = setTimeout(() => timeoutController.abort(), REQUEST_TIMEOUT_MS);
  const abort = () => timeoutController.abort();
  signal?.addEventListener("abort", abort);

  let response: Response;
  try {
    response = await fetch(url, { signal: timeoutController.signal });
  } catch (error) {
    if (signal?.aborted) throw error;
    throw new WordLookupOfflineError();
  } finally {
    clearTimeout(timeout);
    signal?.removeEventListener("abort", abort);
  }

  if (!response.ok) throw new Error(`Word lookup failed (${response.status})`);
  return response.json();
}

// Session-scoped cache: rhymes/synonyms for a word never change, so repeat lookups
// while writing (flipping between modes, re-checking a word) should be instant and free.
const cache = new Map<string, WordSuggestion[]>();
const CACHE_LIMIT = 200;

function rememberInMemory(key: string, suggestions: WordSuggestion[]) {
  if (cache.size >= CACHE_LIMIT) {
    const oldest = cache.keys().next().value;
    if (oldest !== undefined) cache.delete(oldest);
  }
  cache.set(key, suggestions);
}

export function clearWordLookupCache() {
  cache.clear();
}

/**
 * Optional durable cache behind the in-memory one. The app installs a
 * SQLite-backed store at startup (src/services/wordLookupCache.ts) so lookups
 * survive restarts; lookups for a word never change, so nothing here expires.
 * Injected rather than imported to keep this module free of native deps.
 */
export type WordLookupPersistentStore = {
  get: (key: string) => Promise<string | null>;
  set: (key: string, value: string) => void | Promise<void>;
};

let persistentStore: WordLookupPersistentStore | null = null;

export function setWordLookupPersistentStore(store: WordLookupPersistentStore | null) {
  persistentStore = store;
}

async function readPersistent<T>(key: string, parse: (raw: unknown) => T): Promise<T | null> {
  if (!persistentStore) return null;
  try {
    const raw = await persistentStore.get(key);
    if (raw === null) return null;
    return parse(JSON.parse(raw));
  } catch {
    return null;
  }
}

function writePersistent(key: string, value: unknown) {
  try {
    void persistentStore?.set(key, JSON.stringify(value));
  } catch {
    // Durable caching is best-effort; the lookup already succeeded.
  }
}

/**
 * Cache-only lookup (memory, then SQLite) — resolves in milliseconds and never
 * touches the network. The sheet calls this immediately on every query change
 * so cached words render instantly; only true network fetches wait out the
 * typing debounce behind fetchWordSuggestions.
 */
export async function getCachedWordSuggestions(
  mode: WordLookupMode,
  word: string,
  options?: WordLookupOptions
): Promise<WordSuggestion[] | null> {
  const normalized = word.trim().toLowerCase();
  if (!normalized) return null;

  const themeKey = sanitizeThemeWords(options?.theme ?? "").join(",");
  const cacheKey = `${mode}:${themeKey}:${normalized}`;
  const cached = cache.get(cacheKey);
  if (cached) return cached;

  const stored = await readPersistent(cacheKey, parseWordSuggestions);
  if (stored !== null) {
    rememberInMemory(cacheKey, stored);
    return stored;
  }
  return null;
}

export async function fetchWordSuggestions(
  mode: WordLookupMode,
  word: string,
  options?: WordLookupOptions & { signal?: AbortSignal }
): Promise<WordSuggestion[]> {
  const normalized = word.trim().toLowerCase();
  if (!normalized) return [];

  const cached = await getCachedWordSuggestions(mode, normalized, options);
  if (cached !== null) return cached;

  const themeKey = sanitizeThemeWords(options?.theme ?? "").join(",");
  const cacheKey = `${mode}:${themeKey}:${normalized}`;
  const url = buildWordLookupUrl(mode, normalized, options);
  const suggestions = parseWordSuggestions(await fetchWordServiceJson(url, options?.signal));

  rememberInMemory(cacheKey, suggestions);
  writePersistent(cacheKey, suggestions);
  return suggestions;
}

// ── Hebrew (LLM worker) ────────────────────────────────────────────────────────

/** POST to the Hebrew worker: shares the timeout / offline / abort handling with
 * the Datamuse path, plus a 429 → busy mapping the LLM backend can produce. */
async function postWordHeJson(path: string, body: unknown, signal?: AbortSignal): Promise<unknown> {
  const timeoutController = new AbortController();
  const timeout = setTimeout(() => timeoutController.abort(), REQUEST_TIMEOUT_MS);
  const abort = () => timeoutController.abort();
  signal?.addEventListener("abort", abort);

  let response: Response;
  try {
    response = await fetch(`${WORD_HE_SERVICE_BASE_URL}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json" },
      body: JSON.stringify(body),
      signal: timeoutController.signal,
    });
  } catch (error) {
    if (signal?.aborted) throw error;
    throw new WordLookupOfflineError();
  } finally {
    clearTimeout(timeout);
    signal?.removeEventListener("abort", abort);
  }

  if (response.status === 429) throw new WordLookupBusyError();
  if (!response.ok) throw new Error(`Hebrew word lookup failed (${response.status})`);
  return response.json();
}

/** Adapt the worker's { words: [{ word, syllables, tag? }] } to WordSuggestion[].
 * Model order is authoritative (most apt first), so score descends by position. */
function adaptHebrewWords(payload: unknown): WordSuggestion[] {
  const words = (payload as { words?: unknown } | null)?.words;
  if (!Array.isArray(words)) return [];
  const suggestions: WordSuggestion[] = [];
  words.forEach((entry, index) => {
    if (!entry || typeof entry !== "object") return;
    const word = (entry as { word?: unknown }).word;
    if (typeof word !== "string" || !word.trim()) return;
    const syllables = (entry as { syllables?: unknown }).syllables;
    const tag = (entry as { tag?: unknown }).tag;
    suggestions.push({
      word: word.trim(),
      score: words.length - index,
      numSyllables: typeof syllables === "number" ? syllables : undefined,
      tag: typeof tag === "string" && tag.trim() ? tag.trim() : undefined,
    });
  });
  return suggestions;
}

/**
 * Possible nikud readings of a plain-typed Hebrew word (Charuzit via the
 * worker — free), most common first. Hebrew spelling is ambiguous without
 * vowels, so rhyme lookups disambiguate through one of these readings.
 */
const vocalizationCache = new Map<string, string[]>();

function parseStoredStrings(raw: unknown): string[] {
  return Array.isArray(raw) ? raw.filter((entry): entry is string => typeof entry === "string") : [];
}

export async function fetchHebrewVocalizations(
  word: string,
  options?: { signal?: AbortSignal }
): Promise<string[]> {
  const normalized = word.trim();
  if (!normalized) return [];

  const memo = vocalizationCache.get(normalized);
  if (memo) return memo;
  const key = `voc:${normalized}`;
  const stored = await readPersistent(key, parseStoredStrings);
  if (stored !== null) {
    vocalizationCache.set(normalized, stored);
    return stored;
  }

  const payload = await postWordHeJson("/he/vocalizations", { word: normalized }, options?.signal);
  const raw = (payload as { options?: unknown } | null)?.options;
  const readings = Array.isArray(raw)
    ? raw.filter((entry): entry is string => typeof entry === "string" && !!entry.trim())
    : [];
  vocalizationCache.set(normalized, readings);
  writePersistent(key, readings);
  return readings;
}

// Vowel-carrying niqqud marks (U+05B1–U+05BB: the hataf vowels through qubuts).
// Sheva (U+05B0) is deliberately excluded — it's silent more often than not, and
// counting it over-segments. Charuzit gives no syllable count, so we derive one
// from the pointed form: one vowel nucleus ≈ one syllable. Approximate (vocal
// sheva and some cases slip), but consistent enough to group rhymes by length
// for meter matching — the same thing Datamuse's md=s buys on the English side.
const HEBREW_VOWEL_RE = /[\u05B1-\u05BB]/g;
// Shuruq — the "u" vowel written as vav + dagesh (וּ) — carries no vowel point,
// so it isn't in the range above. Counted separately, else words like הוּרַם or
// יוּקַם undercount by one (this exact bug put 2-syllable words in "1 syllable").
// A holam-male (וֹ) already counts via its holam point, so no double-count here.
const HEBREW_SHURUQ_RE = /\u05D5\u05BC/g;

export function countHebrewSyllables(vocal: string): number | undefined {
  if (!vocal) return undefined;
  const vowels = (vocal.match(HEBREW_VOWEL_RE) ?? []).length;
  const shuruq = (vocal.match(HEBREW_SHURUQ_RE) ?? []).length;
  const total = vowels + shuruq;
  if (total === 0) return undefined; // unpointed — no basis to count
  return Math.max(1, total);
}

/** Adapt the worker's { words: [{ word, vocal }] } rhymes — order is relevance;
 * syllable count derived from the pointed form so rhymes group by length. */
export function adaptHebrewRhymes(payload: unknown): WordSuggestion[] {
  const words = (payload as { words?: unknown } | null)?.words;
  if (!Array.isArray(words)) return [];
  const suggestions: WordSuggestion[] = [];
  words.forEach((entry, index) => {
    if (!entry || typeof entry !== "object") return;
    const word = (entry as { word?: unknown }).word;
    if (typeof word !== "string" || !word.trim()) return;
    const vocal = (entry as { vocal?: unknown }).vocal;
    suggestions.push({
      word: word.trim(),
      score: words.length - index,
      numSyllables: typeof vocal === "string" ? countHebrewSyllables(vocal) : undefined,
    });
  });
  return suggestions;
}

/**
 * Rhymes for one vocalized reading (Charuzit via the worker — free, so callers
 * may auto-fire it on the debounce exactly like the Datamuse path). `near`
 * switches to slant rhymes (assonance/consonance). Cached under the pointed
 * form + variant: each reading and each of exact/near has its own set.
 */
export async function fetchHebrewRhymes(
  vocal: string,
  options?: { signal?: AbortSignal; near?: boolean }
): Promise<WordSuggestion[]> {
  const normalized = vocal.trim();
  if (!normalized) return [];
  const near = options?.near === true;

  const cacheKey = `rhy:he:${near ? "near" : "exact"}:${normalized}`;
  const memo = cache.get(cacheKey);
  if (memo) return memo;
  const stored = await readPersistent(cacheKey, parseWordSuggestions);
  if (stored !== null) {
    rememberInMemory(cacheKey, stored);
    return stored;
  }

  const payload = await postWordHeJson("/he/rhymes", { vocal: normalized, near }, options?.signal);
  const suggestions = adaptHebrewRhymes(payload);
  rememberInMemory(cacheKey, suggestions);
  writePersistent(cacheKey, suggestions);
  return suggestions;
}

/**
 * Hebrew meaning-based lookup via the LLM worker. Shares the same cache as the
 * English path (keyed mode:theme:word — Hebrew words never collide with English
 * ones), so a cached result is instant and free. Callers gate the *network*
 * call behind an explicit user action — this never fires on a debounce.
 */
export async function fetchHebrewWordSuggestions(
  mode: WordLookupMode,
  word: string,
  options?: WordLookupOptions & { signal?: AbortSignal }
): Promise<WordSuggestion[]> {
  if (!hebrewWorkerMode(mode)) return [];
  const normalized = word.trim();
  if (!normalized) return [];

  const cached = await getCachedWordSuggestions(mode, normalized, options);
  if (cached !== null) return cached;

  const themes = sanitizeThemeWords(options?.theme ?? "");
  const themeKey = themes.join(",");
  const cacheKey = `${mode}:${themeKey}:${normalized.toLowerCase()}`;

  const payload = await postWordHeJson(
    "/he/words",
    { word: normalized, mode: hebrewWorkerMode(mode), themes },
    options?.signal
  );
  const suggestions = adaptHebrewWords(payload);

  rememberInMemory(cacheKey, suggestions);
  writePersistent(cacheKey, suggestions);
  return suggestions;
}

// ── Definitions ──────────────────────────────────────────────────────────────

export type WordDefinition = { partOfSpeech: string; text: string };

const PART_OF_SPEECH_LABELS: Record<string, string> = {
  n: "noun",
  v: "verb",
  adj: "adjective",
  adv: "adverb",
  u: "other",
};

export function partOfSpeechLabel(tag: string): string {
  return PART_OF_SPEECH_LABELS[tag] ?? tag;
}

function parseWordDefinitions(raw: unknown): WordDefinition[] {
  if (!Array.isArray(raw)) return [];
  const defs: WordDefinition[] = [];
  for (const entry of raw) {
    if (typeof entry !== "string") continue;
    const tab = entry.indexOf("\t");
    if (tab === -1) continue;
    const text = entry.slice(tab + 1).trim();
    if (!text) continue;
    defs.push({ partOfSpeech: entry.slice(0, tab).trim(), text });
  }
  return defs;
}

export function buildDefinitionLookupUrl(word: string, baseUrl: string = WORD_SERVICE_BASE_URL): string {
  const params = new URLSearchParams();
  // sp= (spelled like) is Datamuse's documented way to fetch a single word's
  // record — an exact word also matches as its own best "spelled like" hit.
  params.set("sp", word.trim().toLowerCase());
  params.set("md", "d");
  params.set("max", "1");
  return `${baseUrl}/words?${params.toString()}`;
}

// Separate from the suggestions cache: keyed by word only, no mode/theme.
const definitionCache = new Map<string, WordDefinition[]>();
const DEFINITION_CACHE_LIMIT = 200;

/**
 * Fetch a word's definitions for the "hold to preview" popover. Returns an
 * empty array when the word isn't in Datamuse's dictionary data (common for
 * slang, names, or coined lyric words) — not an error, just nothing to show.
 */
export async function fetchWordDefinitions(
  word: string,
  options?: { signal?: AbortSignal; baseUrl?: string }
): Promise<WordDefinition[]> {
  // Hebrew has no Datamuse dictionary; route to the worker's definition mode.
  // Long-press is an explicit gesture, so an on-demand LLM call is acceptable.
  if (isHebrewLookupWord(word.trim())) return fetchHebrewDefinition(word, options?.signal);

  const normalized = word.trim().toLowerCase();
  if (!normalized) return [];

  const cached = definitionCache.get(normalized);
  if (cached) return cached;

  const storedDefs = await readPersistent(`def:${normalized}`, parseStoredDefinitions);
  if (storedDefs !== null) {
    rememberDefinition(normalized, storedDefs);
    return storedDefs;
  }

  const url = buildDefinitionLookupUrl(normalized, options?.baseUrl);
  const payload = await fetchWordServiceJson(url, options?.signal);
  const first = Array.isArray(payload) ? payload[0] : null;
  const matchesWord =
    first && typeof first === "object" && (first as { word?: unknown }).word === normalized;
  const defs = matchesWord ? parseWordDefinitions((first as { defs?: unknown }).defs) : [];

  rememberDefinition(normalized, defs);
  writePersistent(`def:${normalized}`, defs);
  return defs;
}

/**
 * Hebrew definition via the worker: { definition: { pos, gloss, root? } } → a
 * single WordDefinition row (root folded into the gloss when present). Shares
 * the definition cache with the English path.
 */
async function fetchHebrewDefinition(word: string, signal?: AbortSignal): Promise<WordDefinition[]> {
  const normalized = word.trim();
  if (!normalized) return [];

  const cached = definitionCache.get(normalized);
  if (cached) return cached;

  const stored = await readPersistent(`def:${normalized}`, parseStoredDefinitions);
  if (stored !== null) {
    rememberDefinition(normalized, stored);
    return stored;
  }

  const payload = await postWordHeJson("/he/words", { word: normalized, mode: "definition", themes: [] }, signal);
  const definition = (payload as { definition?: unknown } | null)?.definition;
  const defs: WordDefinition[] = [];
  if (definition && typeof definition === "object") {
    const gloss = (definition as { gloss?: unknown }).gloss;
    if (typeof gloss === "string" && gloss.trim()) {
      const pos = (definition as { pos?: unknown }).pos;
      const root = (definition as { root?: unknown }).root;
      const rootSuffix = typeof root === "string" && root.trim() ? ` · שורש ${root.trim()}` : "";
      defs.push({
        partOfSpeech: typeof pos === "string" ? pos.trim() : "",
        text: `${gloss.trim()}${rootSuffix}`,
      });
    }
  }

  rememberDefinition(normalized, defs);
  writePersistent(`def:${normalized}`, defs);
  return defs;
}

function rememberDefinition(word: string, defs: WordDefinition[]) {
  if (definitionCache.size >= DEFINITION_CACHE_LIMIT) {
    const oldest = definitionCache.keys().next().value;
    if (oldest !== undefined) definitionCache.delete(oldest);
  }
  definitionCache.set(word, defs);
}

/** Validate definitions re-read from the durable cache (we wrote them, but be safe). */
function parseStoredDefinitions(raw: unknown): WordDefinition[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(
    (entry): entry is WordDefinition =>
      !!entry &&
      typeof entry === "object" &&
      typeof (entry as WordDefinition).partOfSpeech === "string" &&
      typeof (entry as WordDefinition).text === "string"
  );
}
