/**
 * Hebrew word finder — the Hebrew Word Finder's entire backend.
 *
 *   app  →  this worker ──┬─ /he/words          →  Claude API (meaning modes; paid)
 *                         ├─ /he/vocalizations  →  Dicta Charuzit (free)
 *                         └─ /he/rhymes         →  Dicta Charuzit (free)
 *
 * No Hebrew API exists for MEANING-based lookups (synonyms, opposites, related,
 * describing words, …), so those are generated by a small Claude model. The
 * SOUND-based lookups (rhymes) proxy Dicta's free Charuzit service — proxied
 * rather than called from the app so results are edge/KV-cached (polite to
 * Dicta's servers) and so their unversioned endpoint is swappable with a worker
 * redeploy instead of an app release. The Anthropic API key must not ship in
 * the app bundle, hence the worker — same shape as magpie-benyehuda/word-proxy.
 *
 * Cost model: a lookup is ~400 input + ~700 output tokens on Haiku, well under
 * a cent. Results for a (mode, word, themes) triple never change, so they are
 * edge-cached for a year — each unique lookup is paid for at most once,
 * globally. `max_tokens` caps the worst-case per-request spend; the Console
 * spend limit on the key caps the worst-case month.
 *
 * Structured outputs (`output_config.format`) constrain generation to the JSON
 * schema, so responses always parse — no retry / repair path needed.
 *
 * Deliberately unauthenticated for now, like word-proxy — SongNook has no
 * accounts. When Pro entitlements become server-verifiable, gate here (see the
 * marked block below).
 *
 * Deploy:
 *   1. npm install            (SDK is bundled by wrangler at deploy time)
 *   2. npx wrangler deploy
 *   3. npx wrangler secret put ANTHROPIC_API_KEY
 *
 * App-side contract (keep in sync with src/domain/wordTools.ts):
 *   POST /he/words          body { word, mode, themes?: string[] }
 *     word-list modes → 200 { words: [{ word, syllables, tag? }] }
 *     mode "definition" → 200 { definition: { pos, gloss, root? } }
 *   POST /he/vocalizations  body { word }
 *     → 200 { options: ["שָׁמַיִם", …] }   possible nikud readings, most common first
 *   POST /he/rhymes         body { vocal }  (one vocalized reading)
 *     → 200 { words: [{ word, vocal }] }  word = unvocalized for insertion
 *   All routes:
 *     → 400 { error }  bad mode / non-Hebrew word / oversized input
 *     → 429 { error }  upstream rate limit (client should back off)
 *     → 502 { error }  upstream failure
 *
 * Caching: two tiers on every route — the edge cache (fast, per-datacenter,
 * evictable) in front of KV (durable, global). A given lookup is computed /
 * billed at most once ever, worldwide, per prompt version.
 */

import Anthropic from "@anthropic-ai/sdk";

const MODEL = "claude-haiku-4-5";
// Hard per-request cost ceiling; a 25-word list with tags fits comfortably.
const MAX_TOKENS = 1024;

// Baked into the cache key. BUMP THIS whenever the prompts, model, or output
// shape change — otherwise the year-long edge/KV cache keeps serving results
// generated by the old prompt. Acts as a global cache-invalidation lever.
const PROMPT_VERSION = "v3";

// ── Charuzit (Dicta) — free Hebrew rhyme engine ──────────────────────────────
// Reverse-engineered from wordplay.dicta.org.il; permission requested from
// Dicta by email. The versioned hostname is why the app goes through this
// worker: when charuzit-5-x appears, only the worker redeploys.
const CHARUZIT_BASE = "https://charuzit-4-0.loadbalancer.dicta.org.il";
// Cache-key version for the charuzit routes (independent of PROMPT_VERSION).
const CHARUZIT_VERSION = "c1";
// Result streams in preference order. Tanakh streams are excluded everywhere —
// their entries are verse phrases with markup, not insertable words.
// Exact rhymes (model omitted): common/modern first, then full, then no-suffix
// (rhymes beyond the shared grammatical ending), then long words.
const CHARUZIT_STREAMS = ["Rhyme_Common", "Rhyme", "Rhyme_NoSuffix", "Rhyme_LongWords"];
// Near / slant rhymes (model:"xxsonance"): assonance = same vowels, consonance
// = same consonant skeleton. Vowel-based first (reads as the truer near-rhyme),
// then consonant, then the broad combined stream as filler.
const CHARUZIT_NEAR_STREAMS = [
  "Assonance_Common", "Assonance", "Assonance_NoSuffix",
  "Consonance_Common", "Consonance_NoSuffix",
  "Xxsonance_Common",
];
const MAX_RHYMES = 80;

// ── Prompts ──────────────────────────────────────────────────────────────────
// The system prompt is the product: register, agreement, and ordering rules
// live here. Tune against the eval word list in README before touching the app.

const SYSTEM_BASE = `אתה מנוע אוצר־מילים בתוך SongNook, אפליקציה לכתיבת שירים. המשתמש כותב שיר בעברית ומחפש מילים סביב מילת חיפוש.

כללים מחייבים — הפרה שלהם פוסלת את התוצאה:
1. מילים אמיתיות בלבד, מנוקות במילון עברי. אם אינך בטוח שמילה קיימת — השמט אותה. לעולם אל תמציא, אל תגזור צורות שאינן בשימוש, ואל תבדה שורשים.
2. התאם את חלק הדיבר של מילת החיפוש: שם עצם → שמות עצם, פועל → פעלים, שם תואר → שמות תואר. אל תערבב חלקי דיבר.
3. אלא אם המשימה היא ניגודים במפורש — אל תכלול מילים הפוכות או מנוגדות במשמעות, גם לא עם תווית. מילה מנוגדת נחשבת שגיאה.
4. עדיף פחות מילים מדויקות על פני רשימה מלאה ומדוללת. אל "תמלא מקום" עם מילים רחוקות רק כדי להגיע ל־15.

כללי פלט:
- עברית מודרנית בכתיב מלא, ללא ניקוד.
- התאם מין ומספר למילת החיפוש כשזה רלוונטי (למשל שמות תואר).
- סדר מהמתאים ביותר והלאה; ללא כפילויות; עד 15 פריטים (רק המילים הטובות ביותר).
- syllables = מספר ההברות במילה.
- tag = תווית קצרה על המשלב או השימוש בלבד (למשל: ספרותי, סלנג, מקראי, ארכאי). לעולם אל תשתמש ב־tag כדי לתאר יחס למילת החיפוש (כמו "הפך" או "דומה"). אם אין הערת משלב — השמט את השדה.

דוגמה (משימה: מילים נרדפות; מילת חיפוש: "פחד"):
{"words":[{"word":"אימה"},{"word":"חרדה"},{"word":"מורא","tag":"ספרותי"},{"word":"בעתה","tag":"ספרותי"},{"word":"יראה"}]}
שים לב: כולן שמות עצם כמו "פחד"; אף אחת אינה פועל (כמו "לפחד"), שם תואר (כמו "מפוחד"), או ניגוד (כמו "אומץ"); "ביטחון" הושמט כי הוא מנוגד.`;

// One criterion line per mode. Keys are the worker's public mode names; the
// app maps its Datamuse-era mode ids onto these.
const WORD_MODES = {
  synonyms: "מצא מילים נרדפות — משמעות קרובה מאוד למילת החיפוש.",
  similar: "מצא מילים דומות במשמעות, גם רחוקות יותר — כל השדה הסמנטי.",
  opposites: "מצא מילים הפוכות במשמעות: אנטונימים, וגם ניגודים רעיוניים.",
  related: "מצא מילים שמתקשרות אסוציאטיבית למילת החיפוש — שמעוררות את אותו עולם, תמונה או תחושה.",
  describing: "מצא שמות תואר שמתארים את מילת החיפוש, מותאמים למין ולמספר שלה.",
  kinds: "מצא סוגים ודוגמאות של מילת החיפוש (היפונימים).",
  parts: "מצא חלקים ומרכיבים של מילת החיפוש (מרונימים).",
  homophones:
    "מצא מילים שנשמעות זהה או כמעט זהה למילת החיפוש (הומופונים), כולל חילופי א/ע, כ/ק, ת/ט וכתיב חלופי.",
};

const DEFINITION_CRITERION =
  "הגדר את מילת החיפוש: חלק הדיבר, הגדרה קצרה וברורה במשפט אחד, והשורש אם קיים.";

// ── Structured-output schemas ────────────────────────────────────────────────

const WORD_LIST_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["words"],
  properties: {
    words: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["word", "syllables"],
        properties: {
          word: { type: "string" },
          syllables: { type: "integer" },
          tag: { type: "string" },
        },
      },
    },
  },
};

const DEFINITION_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["definition"],
  properties: {
    definition: {
      type: "object",
      additionalProperties: false,
      required: ["pos", "gloss"],
      properties: {
        pos: { type: "string" },
        gloss: { type: "string" },
        root: { type: "string" },
      },
    },
  },
};

// ── Input validation ─────────────────────────────────────────────────────────
// Everything rejected here never reaches (or bills) the Claude API.

// Hebrew niqqud + cantillation (same range magpie strips) — users may paste
// pointed text; normalize it away so cache keys and prompts are stable.
const NIKKUD_RE = /[֑-ׇֽֿׁׂׅׄ]/g;
// Hebrew letters plus the joiners that occur inside real words:
// maqaf, geresh/gershayim (acronyms, loanwords like ג'ורג'), apostrophe, space.
const HEBREW_WORD_RE = /^[א-ת][א-ת־׳״' -]{0,29}$/;
// A vocalized (pointed) word as charuzit returns it — letters interleaved with
// nikud marks (U+0591–U+05C7). Validated before proxying so junk never reaches
// Dicta. Written with escapes: combining marks are invisible in source.
const VOCALIZED_WORD_RE =
  /^[\u05D0-\u05EA\u0591-\u05C7][\u05D0-\u05EA\u0591-\u05C7\u05BE\u05F3\u05F4' -]{0,49}$/;

const MAX_THEMES = 5;
const MAX_THEME_CHARS = 30;

function normalizeWord(raw) {
  return String(raw || "").normalize("NFC").replace(NIKKUD_RE, "").trim();
}

function validThemes(raw) {
  if (raw == null) return [];
  if (!Array.isArray(raw)) return null;
  const themes = raw
    .map((t) => normalizeWord(t))
    .filter((t) => t.length > 0 && t.length <= MAX_THEME_CHARS);
  if (themes.length !== raw.length) return null;
  // Sorted so that theme order never splits the cache.
  return themes.slice(0, MAX_THEMES).sort();
}

// ── Handler ──────────────────────────────────────────────────────────────────

const JSON_HEADERS = {
  "Content-Type": "application/json; charset=utf-8",
  "Access-Control-Allow-Origin": "*",
};

const HOUR = 3600;
const DAY = 86400;

// ── Rate limiting (KV fixed-window; approximate, fail-open) ───────────────────
// KV is eventually consistent, so counts can race under load — that's fine for
// blunting scripted abuse. Fail open when WORDHE_KV is unbound so dev isn't
// blocked. Counters only ever tick on a cache MISS (see cachedJson `guard`), so
// browsing cached words never consumes quota.

function clientIp(request) {
  return (
    request.headers.get("cf-connecting-ip") ||
    request.headers.get("x-forwarded-for") ||
    "unknown"
  );
}

function numVar(env, name, fallback) {
  const n = Number(env[name]);
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

/** Increment a fixed-window counter; allow until `limit`. Returns { ok } or
 * { ok:false, retryAfter } (seconds until the window rolls over). */
async function bumpCounter(env, prefix, limit, windowSec) {
  if (!env.WORDHE_KV) return { ok: true };
  const nowSec = Date.now() / 1000;
  const key = `${prefix}:${Math.floor(nowSec / windowSec)}`;
  const current = parseInt((await env.WORDHE_KV.get(key)) || "0", 10);
  if (current >= limit) {
    return { ok: false, retryAfter: Math.ceil(windowSec - (nowSec % windowSec)) };
  }
  // TTL a bit past the window so stale counters self-expire.
  await env.WORDHE_KV.put(key, String(current + 1), { expirationTtl: Math.ceil(windowSec) + HOUR });
  return { ok: true };
}

function json429(retryAfter) {
  return new Response(JSON.stringify({ error: "rate limited — try again shortly" }), {
    status: 429,
    headers: { ...JSON_HEADERS, "Retry-After": String(retryAfter ?? 60) },
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (request.method !== "POST") return json({ error: "not found" }, 404);

    // ── Entitlement gate (future) ─────────────────────────────────────────
    // When Pro accounts exist, verify the user's token here and 403 non-Pro
    // callers before spending LLM budget.

    let body;
    try {
      body = await request.json();
    } catch {
      return json({ error: "invalid JSON body" }, 400);
    }

    const ip = clientIp(request);
    if (url.pathname === "/he/words") return handleWords(env, ctx, body, ip);
    if (url.pathname === "/he/vocalizations") return handleVocalizations(env, ctx, body, ip);
    if (url.pathname === "/he/rhymes") return handleRhymes(env, ctx, body, ip);
    return json({ error: "not found" }, 404);
  },
};

/**
 * Two-tier cache around a compute: edge cache (fast, per-datacenter, evictable)
 * in front of KV (durable, global). `compute` runs only on a full miss and
 * returns either the result object or a `{ errorResponse }` to pass through
 * uncached. A KV hit backfills the edge; a compute hit fills both.
 *
 * `guard` (optional) runs only on a full miss, BEFORE compute — the billable /
 * upstream path — so rate limits never count cache hits. It returns a Response
 * (e.g. 429) to short-circuit, or null to proceed.
 */
async function cachedJson(env, ctx, key, compute, guard) {
  const cache = caches.default;
  const cacheKey = new Request(`https://wordhe.cache/${key}`);
  const edgeHit = await cache.match(cacheKey);
  if (edgeHit) return edgeHit;

  let bodyText = env.WORDHE_KV ? await env.WORDHE_KV.get(key) : null;
  if (bodyText === null) {
    if (guard) {
      const blocked = await guard();
      if (blocked) return blocked; // rate-limited — not cached
    }
    const result = await compute();
    if (result.errorResponse) return result.errorResponse;
    bodyText = JSON.stringify(result.value);
    if (env.WORDHE_KV) ctx.waitUntil(env.WORDHE_KV.put(key, bodyText));
  }

  const response = new Response(bodyText, {
    status: 200,
    headers: { ...JSON_HEADERS, "Cache-Control": "public, max-age=31536000" },
  });
  ctx.waitUntil(cache.put(cacheKey, response.clone()));
  return response;
}

// ── /he/words — LLM meaning lookups (paid) ───────────────────────────────────

async function handleWords(env, ctx, body, ip) {
  const mode = String(body.mode || "");
  const isDefinition = mode === "definition";
  if (!isDefinition && !WORD_MODES[mode]) return json({ error: "unknown mode" }, 400);

  const word = normalizeWord(body.word);
  if (!HEBREW_WORD_RE.test(word)) return json({ error: "word must be Hebrew" }, 400);

  const themes = validThemes(body.themes);
  if (themes === null) return json({ error: "invalid themes" }, 400);

  // Billable path only (cache misses): per-IP hourly limit, then a worker-wide
  // daily circuit breaker that catches distributed (many-IP) abuse.
  const guard = async () => {
    const perIp = await bumpCounter(env, `rl:words:${ip}`, numVar(env, "RATE_WORDS_PER_HOUR", 40), HOUR);
    if (!perIp.ok) return json429(perIp.retryAfter);
    const global = await bumpCounter(env, "rl:global:words", numVar(env, "RATE_WORDS_GLOBAL_PER_DAY", 1500), DAY);
    if (!global.ok) return json429(global.retryAfter);
    console.log("words billable", { mode, wordLen: word.length, themes: themes.length });
    return null;
  };

  const key = `${PROMPT_VERSION}/${mode}/${encodeURIComponent(word)}?t=${encodeURIComponent(themes.join(","))}`;
  return cachedJson(env, ctx, key, async () => {
    const criterion = isDefinition ? DEFINITION_CRITERION : WORD_MODES[mode];
    const themeLine = themes.length
      ? `\nהטה את הבחירה לכיוון הנושאים של השיר: ${themes.join(", ")}.`
      : "";
    try {
      const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });
      const response = await client.messages.create({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        system: `${SYSTEM_BASE}\n\nהמשימה: ${criterion}`,
        messages: [
          { role: "user", content: `מילת החיפוש: "${word}"${themeLine}` },
        ],
        output_config: {
          format: {
            type: "json_schema",
            schema: isDefinition ? DEFINITION_SCHEMA : WORD_LIST_SCHEMA,
          },
        },
      });
      const text = response.content.find((block) => block.type === "text")?.text;
      return { value: JSON.parse(text) };
    } catch (err) {
      if (err instanceof Anthropic.RateLimitError) {
        return { errorResponse: json({ error: "rate limited upstream" }, 429) };
      }
      return { errorResponse: json({ error: "lookup failed" }, 502) };
    }
  }, guard);
}

// ── /he/vocalizations + /he/rhymes — Charuzit proxy (free) ───────────────────

async function postCharuzit(path, payload) {
  const res = await fetch(`${CHARUZIT_BASE}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify(payload),
  });
  if (res.status === 429) return { status: 429 };
  if (!res.ok) return { status: 502 };
  return { status: 200, data: await res.json() };
}

function charuzitError(status) {
  return status === 429
    ? json({ error: "rate limited upstream" }, 429)
    : json({ error: "lookup failed" }, 502);
}

/** Per-IP guard for the free Charuzit routes — protects Dicta's servers (and
 * our standing with them), not our wallet, so the limit is looser. */
function charuzitGuard(env, ip) {
  return async () => {
    const perIp = await bumpCounter(env, `rl:charuzit:${ip}`, numVar(env, "RATE_CHARUZIT_PER_HOUR", 240), HOUR);
    return perIp.ok ? null : json429(perIp.retryAfter);
  };
}

/** The possible nikud readings of a plain-typed word, most common first. */
async function handleVocalizations(env, ctx, body, ip) {
  const word = normalizeWord(body.word);
  if (!HEBREW_WORD_RE.test(word)) return json({ error: "word must be Hebrew" }, 400);

  const key = `${CHARUZIT_VERSION}/voc/${encodeURIComponent(word)}`;
  return cachedJson(env, ctx, key, async () => {
    const res = await postCharuzit("/tipsoundplay", { w: word });
    if (res.status !== 200) return { errorResponse: charuzitError(res.status) };
    const options = Array.isArray(res.data)
      ? res.data.filter((o) => typeof o === "string" && o.trim()).slice(0, 8)
      : [];
    return { value: { options } };
  }, charuzitGuard(env, ip));
}

/** Rhymes for one vocalized reading, flattened across charuzit's streams.
 * `near: true` switches to the assonance/consonance model (slant rhymes). */
async function handleRhymes(env, ctx, body, ip) {
  const vocal = String(body.vocal || "").normalize("NFC").trim();
  if (!VOCALIZED_WORD_RE.test(vocal)) return json({ error: "vocal must be pointed Hebrew" }, 400);
  const near = body.near === true;

  const key = `${CHARUZIT_VERSION}/rhy/${near ? "near" : "exact"}/${encodeURIComponent(vocal)}`;
  return cachedJson(env, ctx, key, async () => {
    const payload = near
      ? {
          soundplay_keyword: vocal,
          rhyme_mode: 1,
          model: "xxsonance",
          soundplay_settings: { allowletswap: true, allowvocswap: true },
        }
      : { soundplay_keyword: vocal, rhyme_mode: 1 };
    const res = await postCharuzit("/api", payload);
    if (res.status !== 200) return { errorResponse: charuzitError(res.status) };
    const streams = near ? CHARUZIT_NEAR_STREAMS : CHARUZIT_STREAMS;
    return { value: { words: adaptCharuzitRhymes(res.data, vocal, streams) } };
  }, charuzitGuard(env, ip));
}

/**
 * Flatten charuzit's result streams into insertable rhymes: preferred streams
 * first, unvocalized `word` for insertion + pointed `vocal` for display,
 * deduped on the unvocalized form, the query word and anything with markup /
 * spaces (verse phrases) dropped.
 */
function adaptCharuzitRhymes(payload, queryVocal, streamOrder) {
  const streams = Array.isArray(payload?.results) ? payload.results : [];
  const byMode = new Map(streams.map((s) => [s?.mode, Array.isArray(s?.results) ? s.results : []]));
  const queryPlain = queryVocal.replace(NIKKUD_RE, "");
  const seen = new Set([queryPlain]);
  const words = [];
  for (const mode of streamOrder) {
    for (const entry of byMode.get(mode) ?? []) {
      const forms = Array.isArray(entry?.forms) ? entry.forms : [];
      for (const form of forms) {
        const vocal = String(form || "").trim();
        // Skip verse phrases: markup, tab-separated citations, or spaces.
        if (vocal.includes("<") || vocal.includes("\t") || vocal.includes(" ")) continue;
        const word = vocal.replace(NIKKUD_RE, "");
        if (!word || seen.has(word)) continue;
        seen.add(word);
        words.push({ word, vocal });
        if (words.length >= MAX_RHYMES) return words;
      }
    }
  }
  return words;
}

function json(obj, status) {
  return new Response(JSON.stringify(obj), { status, headers: JSON_HEADERS });
}
