import type {
    BluetoothMonitoringCalibration,
    ClipAnalysis,
    ClipGroup,
    ClipSection,
    ContentDirection,
    CustomTagDefinition,
    EditRegion,
    ChordSheet,
    IdeasListState,
    IdeaStatus,
    LyricsVersion,
    PracticeMarker,
    RecordingGrid,
    ReceivedMeta,
    Setlist,
    ShareKind,
    Songbook,
    SongChordPaletteItem,
} from "../types";
import type { TempoMap } from "../domain/tempoMap";

/**
 * Single source of truth for the SongNook Archive (`manifest.json`) shape, shared by the
 * exporter (libraryExport.ts) and importer (libraryImport.ts) so the two halves of the
 * round-trip can never drift. This is the human-readable share/handoff format — distinct from
 * the exact disaster-recovery backup (disasterRecoveryBackup.ts).
 *
 * Fidelity:
 *  - "standard": human-readable structure + one audio file per clip. Lossy — waveforms,
 *    markers, sections, tags, groups, analysis, edit history and multi-version lyrics are
 *    dropped, and IDs are remapped on import so the archive merges cleanly into any library.
 *  - "full": everything "standard" carries PLUS every persisted creative field, so a true
 *    archive can be reconstructed without metadata loss. The audio payload is identical in both
 *    modes; the only difference is the extra metadata JSON.
 */
export const SONG_NOOK_ARCHIVE_FORMAT = "songnook-archive";
/** Format id written by builds before the SongNook rename; still accepted on import. */
export const LEGACY_SONG_NOOK_ARCHIVE_FORMAT = "song-nook-archive";

/**
 * Bumped whenever the manifest shape changes. Import stays backward compatible with older versions.
 *  v7 (2026-09-16): edit regions in every fidelity; full fidelity adds the pre-edit source
 *  audio, overdub layer colour/creation time, song-level auto-title flag, hidden-idea state
 *  per collection/workspace, note text direction, and — for clip ideas — every take
 *  (`takes`) plus the idea's own fields (`idea`) instead of the primary take alone.
 */
export const LIBRARY_EXPORT_SCHEMA_VERSION = 7;

export type ArchiveFidelity = "standard" | "full";

export type SongNookArchiveOptions = {
    includeFullSongHistory: boolean;
    includeNotes: boolean;
    includeLyrics: boolean;
    includeHiddenItems: boolean;
    /** Preserve every SongNook metadata field (full fidelity). When false the archive is lossy. */
    preserveAllMetadata: boolean;
};

export type SongNookArchiveLibraryPreferences = {
    primaryWorkspaceId: string | null;
    primaryCollectionIdByWorkspace: Record<string, string>;
    bluetoothMonitoringCalibrations?: BluetoothMonitoringCalibration[];
};

export type ArchiveClipOverdubRootManifest = {
    gainDb: number;
    tonePreset: string;
};

export type ArchiveClipOverdubStemManifest = {
    id: string;
    title: string;
    gainDb: number;
    offsetMs: number;
    tonePreset: string;
    isMuted: boolean;
    durationMs?: number;
    waveformPeaks?: number[];
    /** Beat grid the stem was recorded against. Written in all fidelities (tiny + musically essential). */
    recordingGrid?: RecordingGrid;
    audioPath?: string;
    audioMissing?: boolean;
    // ── Full-fidelity only ──
    /** Layer accent (lane/tint colour); absent = import auto-assigns one. */
    color?: string;
    createdAt?: number;
};

export type ArchiveClipOverdubManifest = {
    root?: ArchiveClipOverdubRootManifest;
    renderedMixPath?: string;
    renderedMixDurationMs?: number;
    renderedMixWaveformPeaks?: number[];
    stems: ArchiveClipOverdubStemManifest[];
};

export type ArchiveClipManifest = {
    id: string;
    title: string;
    createdAt: number;
    isPrimary: boolean;
    isBookmarked?: boolean;
    parentClipId?: string;
    durationMs?: number;
    notes?: string;
    audioPath?: string;
    audioMissing?: boolean;
    overdub?: ArchiveClipOverdubManifest;
    /** Beat grid the take was recorded against (bpm/meter/downbeat offset). Written in all
     *  fidelities — it's tiny and it's what lets a recipient overdub in time. */
    recordingGrid?: RecordingGrid;
    /** Non-destructive keep/remove edits. Written in all fidelities: the audio payload is
     *  always the untouched master, so without these a recipient would hear the raw take. */
    editRegions?: EditRegion[];
    // ── Full-fidelity only (written when manifest.fidelity === "full") ──
    isTitleAutoGenerated?: boolean;
    importedAt?: number;
    sourceCreatedAt?: number;
    parentAssignedAt?: number;
    /** Real recorded waveform; standard archives let import regenerate a placeholder instead. */
    waveformPeaks?: number[];
    /** The pre-edit original, written only when it differs from the master. Clips derived
     *  from the same source share one archive entry (deduped by live file). */
    sourceAudioPath?: string;
    tags?: string[];
    practiceMarkers?: PracticeMarker[];
    sections?: ClipSection[];
    analysis?: ClipAnalysis;
    /** The lyrics version this take was recorded against (resolves against the
     *  song's lyricsVersions on import; harmless if absent or dangling). */
    lyricsVersionId?: string;
    manualSortOrder?: number;
};

/** The clip idea's own fields (full fidelity) — a clip idea is more than its primary take. */
export type ArchiveStandaloneIdeaManifest = {
    status?: IdeaStatus;
    completionPct?: number;
    lastActivityAt?: number;
    isTitleAutoGenerated?: boolean;
    isDraft?: boolean;
    importedAt?: number;
    sourceCreatedAt?: number;
    customTags?: CustomTagDefinition[];
};

/**
 * A clip idea. The entry itself describes the PRIMARY take (readable by pre-v7 importers);
 * full fidelity adds `takes` — every take of the idea, primary included, with lineage —
 * and `idea`, the idea-level fields. When `takes` is present an importer rebuilds the
 * idea from it and ignores the entry-level take fields.
 */
export type ArchiveStandaloneClipManifest = ArchiveClipManifest & {
    takes?: ArchiveClipManifest[];
    idea?: ArchiveStandaloneIdeaManifest;
};

export type ArchiveSongManifest = {
    id: string;
    title: string;
    folderPath: string;
    collectionId: string;
    createdAt: number;
    lastActivityAt: number;
    completionPct: number;
    isBookmarked: boolean;
    notes?: string;
    /** Latest lyric text (human-readable, also written as Lyrics.txt). */
    lyrics?: string;
    historyIncluded: boolean;
    /** The sketch's planned beat grid (tempo map). Written in all fidelities — tiny, and
     *  it's what lets a recipient record against the sender's plan. */
    songGrid?: TempoMap;
    songGridUpdatedAt?: number;
    clips: ArchiveClipManifest[];
    // ── Full-fidelity only ──
    status?: IdeaStatus;
    isDraft?: boolean;
    /** Still machine-titled (drives the earned-serif rule). */
    isTitleAutoGenerated?: boolean;
    importedAt?: number;
    sourceCreatedAt?: number;
    customTags?: CustomTagDefinition[];
    clipGroups?: ClipGroup[];
    /** Maps a lineage-root clip id to a group id (both within this song). */
    clipGroupAssignments?: Record<string, string>;
    /** All lyric versions with their full documents (chords included). */
    lyricsVersions?: LyricsVersion[];
    /** Song-level quick-insert chord palette. */
    chordPalette?: SongChordPaletteItem[];
    /** Standalone block chord chart for the song. */
    chordSheet?: ChordSheet;
};

export type ArchiveCollectionManifest = {
    id: string;
    title: string;
    parentCollectionId?: string | null;
    folderPath: string;
    songs: ArchiveSongManifest[];
    standaloneClips: ArchiveStandaloneClipManifest[];
    // ── Full-fidelity only ──
    description?: string;
    createdAt?: number;
    updatedAt?: number;
    /** Hidden ideas / hidden days on this collection's list (idea ids remapped on import). */
    ideasListState?: IdeasListState;
};

export type ArchiveWorkspaceManifest = {
    id: string;
    title: string;
    description?: string;
    isArchived?: boolean;
    folderPath: string;
    collections: ArchiveCollectionManifest[];
    // ── Full-fidelity only ──
    color?: string;
    avatarKey?: number;
    /** Received-package provenance survives a full export/import round trip
     *  (device migration must not silently convert received work to personal). */
    origin?: "personal" | "received" | "shared";
    received?: ReceivedMeta;
    /** Workspace-wide hidden ideas / days (idea ids remapped on import). */
    ideasListState?: IdeasListState;
};

export type ArchiveNotepadNoteManifest = {
    id: string;
    title: string;
    body: string;
    createdAt: number;
    updatedAt: number;
    isPinned: boolean;
    /** Authored direction of the note; absent = "auto". */
    textDirection?: ContentDirection;
};

export type ArchiveManifest = {
    format: typeof SONG_NOOK_ARCHIVE_FORMAT;
    schemaVersion: number;
    /** Absent on pre-v6 archives — treat as "standard". */
    fidelity?: ArchiveFidelity;
    exportedAt: string;
    options?: SongNookArchiveOptions;
    libraryPreferences?: SongNookArchiveLibraryPreferences;
    scope: {
        workspaceIds: string[];
        collectionIds: string[];
        excludedCollectionIds?: string[];
    };
    warnings?: string[];
    summary: {
        workspaces: number;
        collections: number;
        songs: number;
        standaloneClips: number;
        notepadNotes?: number;
    };
    notepadNotes?: ArchiveNotepadNoteManifest[];
    workspaces: ArchiveWorkspaceManifest[];
    /** Global songbooks/setlists (full fidelity); references remapped on import. */
    songbooks?: Songbook[];
    setlists?: Setlist[];
    /** What this archive declares itself to be — stamped by the SHARE flows at
     *  export and trusted over any inference on the receiving side. Absent on
     *  older archives and on full library exports made before this field. */
    share?: ArchiveShareDeclaration;
};

export type ArchiveShareDeclaration = {
    kind: ShareKind;
    title: string;
    sender: { name: string | null; userId: string | null };
    transferId: string | null;
    createdAt: number;
    appVersion?: string;
};
