import type {
    BluetoothMonitoringCalibration,
    ClipAnalysis,
    ClipGroup,
    ClipSection,
    CustomTagDefinition,
    EditRegion,
    ChordSheet,
    IdeaStatus,
    LyricsVersion,
    PracticeMarker,
    SongChordPaletteItem,
} from "../types";

/**
 * Single source of truth for the Song Seed Archive (`manifest.json`) shape, shared by the
 * exporter (libraryExport.ts) and importer (libraryImport.ts) so the two halves of the
 * round-trip can never drift. This is the human-readable share/handoff format — distinct from
 * the exact disaster-recovery backup (disasterRecoveryBackup.ts).
 *
 * Fidelity:
 *  - "standard": human-readable structure + one audio file per clip. Lossy — waveforms,
 *    markers, sections, tags, groups, analysis, edit history and multi-version lyrics are
 *    dropped, and IDs are remapped on import so the archive merges cleanly into any library.
 *  - "full": everything "standard" carries PLUS every persisted creative field, so a true
 *    archive can be reconstructed without metadata loss. The audio payload is identical in both
 *    modes; the only difference is the extra metadata JSON.
 */
export const SONG_SEED_ARCHIVE_FORMAT = "song-seed-archive";

/** Bumped whenever the manifest shape changes. Import stays backward compatible with older versions. */
export const LIBRARY_EXPORT_SCHEMA_VERSION = 6;

export type ArchiveFidelity = "standard" | "full";

export type SongSeedArchiveOptions = {
    includeFullSongHistory: boolean;
    includeNotes: boolean;
    includeLyrics: boolean;
    includeHiddenItems: boolean;
    /** Preserve every Song Seed metadata field (full fidelity). When false the archive is lossy. */
    preserveAllMetadata: boolean;
};

export type SongSeedArchiveLibraryPreferences = {
    primaryWorkspaceId: string | null;
    primaryCollectionIdByWorkspace: Record<string, string>;
    bluetoothMonitoringCalibrations?: BluetoothMonitoringCalibration[];
};

export type ArchiveClipOverdubRootManifest = {
    gainDb: number;
    tonePreset: "neutral" | "low-cut" | "warm" | "bright";
};

export type ArchiveClipOverdubStemManifest = {
    id: string;
    title: string;
    gainDb: number;
    offsetMs: number;
    tonePreset: "neutral" | "low-cut" | "warm" | "bright";
    isMuted: boolean;
    durationMs?: number;
    waveformPeaks?: number[];
    audioPath?: string;
    audioMissing?: boolean;
};

export type ArchiveClipOverdubManifest = {
    root?: ArchiveClipOverdubRootManifest;
    renderedMixPath?: string;
    renderedMixDurationMs?: number;
    renderedMixWaveformPeaks?: number[];
    stems: ArchiveClipOverdubStemManifest[];
};

export type ArchiveClipManifest = {
    id: string;
    title: string;
    createdAt: number;
    isPrimary: boolean;
    isBookmarked?: boolean;
    parentClipId?: string;
    durationMs?: number;
    notes?: string;
    audioPath?: string;
    audioMissing?: boolean;
    overdub?: ArchiveClipOverdubManifest;
    // ── Full-fidelity only (written when manifest.fidelity === "full") ──
    isTitleAutoGenerated?: boolean;
    importedAt?: number;
    sourceCreatedAt?: number;
    parentAssignedAt?: number;
    /** Real recorded waveform; standard archives let import regenerate a placeholder instead. */
    waveformPeaks?: number[];
    editRegions?: EditRegion[];
    tags?: string[];
    practiceMarkers?: PracticeMarker[];
    sections?: ClipSection[];
    analysis?: ClipAnalysis;
    manualSortOrder?: number;
};

export type ArchiveSongManifest = {
    id: string;
    title: string;
    folderPath: string;
    collectionId: string;
    createdAt: number;
    lastActivityAt: number;
    completionPct: number;
    isBookmarked: boolean;
    notes?: string;
    /** Latest lyric text (human-readable, also written as Lyrics.txt). */
    lyrics?: string;
    historyIncluded: boolean;
    clips: ArchiveClipManifest[];
    // ── Full-fidelity only ──
    status?: IdeaStatus;
    isDraft?: boolean;
    importedAt?: number;
    sourceCreatedAt?: number;
    customTags?: CustomTagDefinition[];
    clipGroups?: ClipGroup[];
    /** Maps a lineage-root clip id to a group id (both within this song). */
    clipGroupAssignments?: Record<string, string>;
    /** All lyric versions with their full documents (chords included). */
    lyricsVersions?: LyricsVersion[];
    /** Song-level quick-insert chord palette. */
    chordPalette?: SongChordPaletteItem[];
    /** Standalone block chord chart for the song. */
    chordSheet?: ChordSheet;
};

export type ArchiveCollectionManifest = {
    id: string;
    title: string;
    parentCollectionId?: string | null;
    folderPath: string;
    songs: ArchiveSongManifest[];
    standaloneClips: ArchiveClipManifest[];
    // ── Full-fidelity only ──
    description?: string;
    createdAt?: number;
    updatedAt?: number;
};

export type ArchiveWorkspaceManifest = {
    id: string;
    title: string;
    description?: string;
    isArchived?: boolean;
    folderPath: string;
    collections: ArchiveCollectionManifest[];
    // ── Full-fidelity only ──
    color?: string;
    avatarKey?: number;
};

export type ArchiveNotepadNoteManifest = {
    id: string;
    title: string;
    body: string;
    createdAt: number;
    updatedAt: number;
    isPinned: boolean;
};

export type ArchiveManifest = {
    format: typeof SONG_SEED_ARCHIVE_FORMAT;
    schemaVersion: number;
    /** Absent on pre-v6 archives — treat as "standard". */
    fidelity?: ArchiveFidelity;
    exportedAt: string;
    options?: SongSeedArchiveOptions;
    libraryPreferences?: SongSeedArchiveLibraryPreferences;
    scope: {
        workspaceIds: string[];
        collectionIds: string[];
        excludedCollectionIds?: string[];
    };
    warnings?: string[];
    summary: {
        workspaces: number;
        collections: number;
        songs: number;
        standaloneClips: number;
        notepadNotes?: number;
    };
    notepadNotes?: ArchiveNotepadNoteManifest[];
    workspaces: ArchiveWorkspaceManifest[];
};
