import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { File } from "expo-file-system";
import { strFromU8 } from "fflate";
import {
    extractStoredZipEntryToFile,
    indexStoredZipArchive,
    readStoredZipEntryBytes,
    type StoredZipIndex,
} from "./storedZipArchive";
import { createLyricsVersion, lyricsTextToDocument } from "../domain/lyrics";
import { createEmptyProjectLyrics, createEmptyWorkspaceIdeasListState } from "../state/dataSlice";
import type {
    BluetoothMonitoringCalibration,
    ClipVersion,
    Collection,
    IdeasListState,
    Note,
    ProjectLyrics,
    Setlist,
    Songbook,
    SongIdea,
    Workspace,
} from "../types";
import { SONG_NOOK_AUDIO_DIR } from "./storagePaths";
import { MANAGED_WAVEFORM_PEAK_COUNT } from "./audioStorage";
import { buildStaticWaveform, ensureUniqueCountedTitle } from "../utils";
import {
    LEGACY_SONG_NOOK_ARCHIVE_FORMAT,
    SONG_NOOK_ARCHIVE_FORMAT,
    type ArchiveClipManifest,
    type ArchiveClipOverdubManifest,
    type ArchiveManifest,
} from "./libraryArchiveManifest";
import { normalizeBluetoothMonitoringCalibrations } from "../domain/bluetoothMonitoring";
import { sanitizeTempoMap } from "../domain/tempoMap";

/** Pre-edit source files already extracted, by archive path → managed uri (shared sources). */
type SourceAudioDestinations = Map<string, string>;

/** Remap a hidden-idea list onto the freshly minted idea ids; hidden days copy as-is. */
function remapIdeasListState(
    state: IdeasListState | undefined,
    ideaIdMap: Map<string, string>
): IdeasListState {
    const hiddenIdeaIds = (state?.hiddenIdeaIds ?? [])
        .map((sourceId) => ideaIdMap.get(sourceId))
        .filter((id): id is string => !!id);
    const hiddenDays = Array.isArray(state?.hiddenDays) ? state.hiddenDays : [];
    return { hiddenIdeaIds, hiddenDays };
}

export type PickedLibraryArchiveFile = {
    uri: string;
    name: string;
};

export type ParsedSongNookArchive = {
    sourceUri: string;
    sourceName: string;
    manifest: ArchiveManifest;
    /**
     * Streaming index into the archive. Audio payloads are extracted entry-by-entry in
     * bounded chunks — never the whole archive in memory (a multi-hundred-MB archive read
     * as one buffer OOM'd Hermes on device).
     */
    archiveIndex: StoredZipIndex;
};

export type LibraryImportPreview = {
    archiveName: string;
    exportedAt: string;
    workspaceCount: number;
    collectionCount: number;
    songCount: number;
    standaloneClipCount: number;
    notepadNoteCount: number;
    workspaceTitles: string[];
    warningMessages: string[];
    primaryWorkspaceTitle: string | null;
};

export type MaterializedSongNookArchiveMerge = {
    importedWorkspaces: Workspace[];
    importedNotes: Note[];
    importedSongbooks: Songbook[];
    importedSetlists: Setlist[];
    suggestedPrimaryWorkspaceId: string | null;
    suggestedPrimaryCollectionIdByWorkspace: Record<string, string>;
    bluetoothMonitoringCalibrations: BluetoothMonitoringCalibration[];
    importedWorkspaceIds: string[];
    importedIdeaIds: string[];
    warnings: string[];
};

function buildEntityId(prefix: string) {
    return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function buildWorkspaceId() {
    return buildEntityId("ws");
}

function buildCollectionId() {
    return buildEntityId("col");
}

function buildIdeaId() {
    return buildEntityId("idea");
}

function buildClipId() {
    return buildEntityId("clip");
}

function buildOverdubStemId() {
    return buildEntityId("stem");
}

function buildNoteId() {
    return buildEntityId("note");
}

function buildClipGroupId() {
    return buildEntityId("group");
}

function getPathExtension(path: string | undefined) {
    const match = path?.match(/\.([a-zA-Z0-9]+)$/);
    return match?.[1]?.toLowerCase() ?? "m4a";
}

/**
 * Use the real archived waveform when present (full-fidelity archives), otherwise regenerate a
 * deterministic placeholder so the clip still draws something. Keyed off the new clip id.
 */
function resolveArchiveWaveform(clipManifest: ArchiveClipManifest, clipId: string): number[] {
    return clipManifest.waveformPeaks && clipManifest.waveformPeaks.length > 0
        ? clipManifest.waveformPeaks
        : buildStaticWaveform(`${clipId}-${clipManifest.title}`, MANAGED_WAVEFORM_PEAK_COUNT);
}

/**
 * Pull the optional full-fidelity creative fields off a clip manifest. Present only in archives
 * exported with "preserve all metadata"; absent fields stay undefined and are dropped by the
 * store normalizer. `isBookmarked` is intentionally excluded — standalone clips reuse it for the
 * idea's bookmark, so callers set it explicitly.
 */
function readFullClipMetadata(clipManifest: ArchiveClipManifest) {
    return {
        isTitleAutoGenerated: clipManifest.isTitleAutoGenerated,
        importedAt: clipManifest.importedAt,
        sourceCreatedAt: clipManifest.sourceCreatedAt,
        parentAssignedAt: clipManifest.parentAssignedAt,
        editRegions: clipManifest.editRegions,
        tags: clipManifest.tags,
        practiceMarkers: clipManifest.practiceMarkers,
        sections: clipManifest.sections,
        analysis: clipManifest.analysis,
        recordingGrid: clipManifest.recordingGrid,
        lyricsVersionId: clipManifest.lyricsVersionId,
        manualSortOrder: clipManifest.manualSortOrder,
    };
}

async function ensureAudioDirectory() {
    if (!FileSystem.documentDirectory) {
        throw new Error("Document directory unavailable.");
    }

    const info = await FileSystem.getInfoAsync(SONG_NOOK_AUDIO_DIR);
    if (!info.exists) {
        await FileSystem.makeDirectoryAsync(SONG_NOOK_AUDIO_DIR, { intermediates: true });
    }
}

/**
 * Stream one archive audio entry straight to its managed destination (via the shared
 * bounded-chunk extractor, which CRC-verifies the entry in-stream). Returns null when
 * the archive lacks the entry so callers can warn without aborting the import.
 */
async function extractManagedArchiveAudio(
    parsed: ParsedSongNookArchive,
    archivePath: string,
    targetId: string,
    extension: string
): Promise<string | null> {
    const entry = parsed.archiveIndex.entries.get(archivePath);
    if (!entry) return null;

    await ensureAudioDirectory();
    const destinationUri = `${SONG_NOOK_AUDIO_DIR}/${targetId}.${extension}`;
    await extractStoredZipEntryToFile(parsed.archiveIndex, entry, destinationUri);
    return destinationUri;
}

/**
 * One take: master audio, pre-edit source (shared across derived clips), overdubs and every
 * creative field the archive carries. Lineage (`parentClipId`) is remapped by the caller.
 */
async function materializeArchiveClip(
    clipManifest: ArchiveClipManifest,
    parsed: ParsedSongNookArchive,
    clipId: string,
    warnings: string[],
    clipLabel: string,
    sourceDestinations: SourceAudioDestinations
): Promise<ClipVersion> {
    let audioUri: string | undefined;
    if (clipManifest.audioPath) {
        audioUri =
            (await extractManagedArchiveAudio(
                parsed,
                clipManifest.audioPath,
                clipId,
                getPathExtension(clipManifest.audioPath)
            )) ?? undefined;
        if (!audioUri) {
            warnings.push(`Missing archived audio for ${clipLabel}.`);
        }
    }

    let sourceAudioUri: string | undefined;
    if (clipManifest.sourceAudioPath) {
        const shared = sourceDestinations.get(clipManifest.sourceAudioPath);
        if (shared) {
            sourceAudioUri = shared;
        } else {
            sourceAudioUri =
                (await extractManagedArchiveAudio(
                    parsed,
                    clipManifest.sourceAudioPath,
                    `${clipId}-source`,
                    getPathExtension(clipManifest.sourceAudioPath)
                )) ?? undefined;
            if (sourceAudioUri) {
                sourceDestinations.set(clipManifest.sourceAudioPath, sourceAudioUri);
            } else {
                warnings.push(`Missing archived source audio for ${clipLabel}.`);
            }
        }
    }

    const overdub = await materializeArchiveClipOverdub(clipManifest.overdub, parsed, clipId, warnings, clipLabel);

    return {
        id: clipId,
        title: clipManifest.title,
        notes: clipManifest.notes ?? "",
        createdAt: clipManifest.createdAt,
        isPrimary: clipManifest.isPrimary,
        parentClipId: clipManifest.parentClipId ?? undefined,
        audioUri,
        sourceAudioUri,
        durationMs: clipManifest.durationMs,
        waveformPeaks: resolveArchiveWaveform(clipManifest, clipId),
        overdub,
        isBookmarked: clipManifest.isBookmarked,
        ...readFullClipMetadata(clipManifest),
    };
}

/** Remap lineage onto the new ids and guarantee exactly one primary take. */
function finalizeImportedClips(clips: ClipVersion[], clipIdMap: Map<string, string>): ClipVersion[] {
    const hasPrimary = clips.some((candidate) => candidate.isPrimary);
    return clips.map((clip, index) => ({
        ...clip,
        parentClipId: clip.parentClipId ? clipIdMap.get(clip.parentClipId) : undefined,
        isPrimary: hasPrimary ? clip.isPrimary : index === 0,
    }));
}

async function materializeArchiveClipOverdub(
    overdubManifest: ArchiveClipOverdubManifest | undefined,
    parsed: ParsedSongNookArchive,
    clipId: string,
    warnings: string[],
    clipLabel: string
) {
    if (!overdubManifest) {
        return undefined;
    }

    let renderedMixUri: string | undefined;
    if (overdubManifest.renderedMixPath) {
        renderedMixUri =
            (await extractManagedArchiveAudio(
                parsed,
                overdubManifest.renderedMixPath,
                `${clipId}-mix`,
                getPathExtension(overdubManifest.renderedMixPath)
            )) ?? undefined;
        if (!renderedMixUri) {
            warnings.push(`Missing archived rendered overdub mix for ${clipLabel}.`);
        }
    }

    const stems = [];
    for (const stemManifest of overdubManifest.stems ?? []) {
        const stemId = buildOverdubStemId();
        let audioUri: string | undefined;
        if (stemManifest.audioPath) {
            audioUri =
                (await extractManagedArchiveAudio(
                    parsed,
                    stemManifest.audioPath,
                    `${clipId}-${stemId}`,
                    getPathExtension(stemManifest.audioPath)
                )) ?? undefined;
            if (!audioUri) {
                warnings.push(`Missing archived overdub stem for ${clipLabel} / ${stemManifest.title}.`);
            }
        }

        stems.push({
            id: stemId,
            title: stemManifest.title,
            audioUri,
            gainDb: stemManifest.gainDb,
            offsetMs: stemManifest.offsetMs,
            tonePreset: stemManifest.tonePreset,
            isMuted: !!stemManifest.isMuted,
            durationMs: stemManifest.durationMs,
            waveformPeaks: stemManifest.waveformPeaks,
            recordingGrid: stemManifest.recordingGrid,
            color: stemManifest.color,
            createdAt: stemManifest.createdAt ?? Date.now(),
        });
    }

    if (stems.length === 0 && !renderedMixUri) {
        return undefined;
    }

    return {
        root: overdubManifest.root
            ? {
                  gainDb: overdubManifest.root.gainDb,
                  tonePreset: overdubManifest.root.tonePreset,
              }
            : undefined,
        stems,
        renderedMixUri,
        renderedMixDurationMs: overdubManifest.renderedMixDurationMs,
        renderedMixWaveformPeaks: overdubManifest.renderedMixWaveformPeaks,
        lastRenderedAt: Date.now(),
    };
}

function isSongNookArchiveManifest(value: unknown): value is ArchiveManifest {
    if (!value || typeof value !== "object") return false;
    const candidate = value as Partial<ArchiveManifest>;
    // Accept the pre-rename format id too — archives exported before the SongNook
    // rename carry "song-nook-archive" and must keep importing forever.
    const format = candidate.format as string | undefined;
    return (
        (format === SONG_NOOK_ARCHIVE_FORMAT || format === LEGACY_SONG_NOOK_ARCHIVE_FORMAT) &&
        Array.isArray(candidate.workspaces)
    );
}

export async function pickSongNookArchiveFile(): Promise<PickedLibraryArchiveFile | null> {
    const result = await DocumentPicker.getDocumentAsync({
        type: ["application/zip", "application/x-zip-compressed", "*/*"],
        multiple: false,
        copyToCacheDirectory: true,
    });

    if (result.canceled || result.assets.length === 0) {
        return null;
    }

    const asset = result.assets[0]!;
    return {
        uri: asset.uri,
        name: asset.name || "SongNook Archive.zip",
    };
}

export async function readSongNookArchive(
    sourceUri: string,
    sourceName = sourceUri.split("/").pop() ?? "SongNook Archive.zip"
): Promise<ParsedSongNookArchive> {
    // Index the archive without loading payloads — SongNook Archives are written by
    // createZipArchive (stored, uncompressed), the same format the backup reader streams.
    const archiveIndex = await indexStoredZipArchive(sourceUri);
    const manifestEntry = archiveIndex.entries.get("manifest.json");
    if (!manifestEntry) {
        throw new Error("Archive is missing manifest.json.");
    }

    const manifestJson = JSON.parse(
        strFromU8(await readStoredZipEntryBytes(archiveIndex, manifestEntry))
    );
    if (!isSongNookArchiveManifest(manifestJson)) {
        throw new Error("This file is not a valid SongNook Archive.");
    }

    return {
        sourceUri,
        sourceName,
        manifest: manifestJson,
        archiveIndex,
    };
}

export function buildLibraryImportPreview(parsed: ParsedSongNookArchive): LibraryImportPreview {
    const primaryWorkspaceTitle =
        parsed.manifest.libraryPreferences?.primaryWorkspaceId
            ? parsed.manifest.workspaces.find(
                  (workspace) =>
                      workspace.id === parsed.manifest.libraryPreferences?.primaryWorkspaceId
              )?.title ?? null
            : null;

    return {
        archiveName: parsed.sourceName,
        exportedAt: parsed.manifest.exportedAt,
        workspaceCount: parsed.manifest.summary.workspaces,
        collectionCount: parsed.manifest.summary.collections,
        songCount: parsed.manifest.summary.songs,
        standaloneClipCount: parsed.manifest.summary.standaloneClips,
        notepadNoteCount: parsed.manifest.summary.notepadNotes ?? parsed.manifest.notepadNotes?.length ?? 0,
        workspaceTitles: parsed.manifest.workspaces.map((workspace) => workspace.title),
        warningMessages: parsed.manifest.warnings ?? [],
        primaryWorkspaceTitle,
    };
}

export async function materializeSongNookArchiveMerge(
    parsed: ParsedSongNookArchive,
    existingWorkspaces: Workspace[],
    localPrimaryWorkspaceId: string | null
): Promise<MaterializedSongNookArchiveMerge> {
    const warnings = [...(parsed.manifest.warnings ?? [])];
    const importedWorkspaces: Workspace[] = [];
    const importedNotes: Note[] = [];
    const importedWorkspaceIds: string[] = [];
    const importedIdeaIds: string[] = [];
    // Source-id -> new-id maps so global songbook/setlist references survive the
    // re-id that import performs. (Lyric version ids are preserved as-is.)
    const workspaceIdMap = new Map<string, string>();
    const ideaIdMap = new Map<string, string>();
    const clipIdMapGlobal = new Map<string, string>();
    // Lyric version ids per imported song, so songbook/setlist chart references that point
    // at a version this archive did not carry are dropped instead of dangling.
    const lyricVersionIdsByIdea = new Map<string, Set<string>>();
    const sourceDestinations: SourceAudioDestinations = new Map();
    const suggestedPrimaryCollectionIdByWorkspace: Record<string, string> = {};
    const bluetoothMonitoringCalibrations = normalizeBluetoothMonitoringCalibrations(
        parsed.manifest.libraryPreferences?.bluetoothMonitoringCalibrations
    );

    const existingWorkspaceTitles = existingWorkspaces.map((workspace) => workspace.title);
    const importedPrimaryWorkspaceSourceId = parsed.manifest.libraryPreferences?.primaryWorkspaceId ?? null;
    let suggestedPrimaryWorkspaceId: string | null = null;

    for (const noteManifest of parsed.manifest.notepadNotes ?? []) {
        importedNotes.push({
            id: buildNoteId(),
            title: noteManifest.title,
            body: noteManifest.body,
            createdAt: noteManifest.createdAt,
            updatedAt: noteManifest.updatedAt,
            isPinned: !!noteManifest.isPinned,
            textDirection: noteManifest.textDirection,
        });
    }

    for (const workspaceManifest of parsed.manifest.workspaces) {
        const workspaceId = buildWorkspaceId();
        workspaceIdMap.set(workspaceManifest.id, workspaceId);
        const workspaceTitle = ensureUniqueCountedTitle(
            workspaceManifest.title,
            existingWorkspaceTitles
        );
        existingWorkspaceTitles.push(workspaceTitle);

        const collectionIdMap = new Map<string, string>();
        const clipIdMap = new Map<string, string>();
        const siblingTitlesByParent = new Map<string, string[]>();
        const collectionDrafts: Array<{
            sourceId: string;
            collectionId: string;
            title: string;
            parentSourceId: string | null;
            description?: string;
            createdAt?: number;
            updatedAt?: number;
        }> = [];
        const collections: Collection[] = [];
        const ideas: SongIdea[] = [];

        for (const collectionManifest of workspaceManifest.collections) {
            const parentKey = collectionManifest.parentCollectionId ?? "__root__";
            const siblingTitles = siblingTitlesByParent.get(parentKey) ?? [];
            const collectionTitle = ensureUniqueCountedTitle(collectionManifest.title, siblingTitles);
            siblingTitles.push(collectionTitle);
            siblingTitlesByParent.set(parentKey, siblingTitles);

            const collectionId = buildCollectionId();
            collectionIdMap.set(collectionManifest.id, collectionId);
            collectionDrafts.push({
                sourceId: collectionManifest.id,
                collectionId,
                title: collectionTitle,
                parentSourceId: collectionManifest.parentCollectionId ?? null,
                description: collectionManifest.description,
                createdAt: collectionManifest.createdAt,
                updatedAt: collectionManifest.updatedAt,
            });
        }

        collectionDrafts.forEach((draft) => {
            collections.push({
                id: draft.collectionId,
                title: draft.title,
                workspaceId,
                parentCollectionId: draft.parentSourceId
                    ? collectionIdMap.get(draft.parentSourceId) ?? null
                    : null,
                description: draft.description,
                createdAt: draft.createdAt ?? Date.now(),
                updatedAt: draft.updatedAt ?? Date.now(),
                ideasListState: createEmptyWorkspaceIdeasListState(),
            });
        });

        for (const collectionManifest of workspaceManifest.collections) {
            const collectionId = collectionIdMap.get(collectionManifest.id);
            if (!collectionId) {
                continue;
            }

            for (const songManifest of collectionManifest.songs) {
                const ideaId = buildIdeaId();
                ideaIdMap.set(songManifest.id, ideaId);
                importedIdeaIds.push(ideaId);

                const clips: ClipVersion[] = [];
                for (const clipManifest of songManifest.clips) {
                    const clipId = buildClipId();
                    clipIdMap.set(clipManifest.id, clipId);
                    clipIdMapGlobal.set(clipManifest.id, clipId);
                    clips.push(
                        await materializeArchiveClip(
                            clipManifest,
                            parsed,
                            clipId,
                            warnings,
                            `${songManifest.title} / ${clipManifest.title}`,
                            sourceDestinations
                        )
                    );
                }

                const remappedClips = finalizeImportedClips(clips, clipIdMap);

                // Re-id clip groups and remap their assignments (root clip id -> group id) onto the
                // freshly minted ids, so the store normalizer keeps them. Full-fidelity only.
                let clipGroups: SongIdea["clipGroups"];
                let clipGroupAssignments: SongIdea["clipGroupAssignments"];
                if (songManifest.clipGroups?.length) {
                    const groupIdMap = new Map<string, string>();
                    clipGroups = songManifest.clipGroups.map((group) => {
                        const newGroupId = buildClipGroupId();
                        groupIdMap.set(group.id, newGroupId);
                        return { ...group, id: newGroupId };
                    });
                    const remapped: Record<string, string> = {};
                    for (const [rootClipId, groupId] of Object.entries(
                        songManifest.clipGroupAssignments ?? {}
                    )) {
                        const newClipId = clipIdMap.get(rootClipId);
                        const newGroupId = groupIdMap.get(groupId);
                        if (newClipId && newGroupId) {
                            remapped[newClipId] = newGroupId;
                        }
                    }
                    if (Object.keys(remapped).length > 0) {
                        clipGroupAssignments = remapped;
                    }
                }

                const lyrics: ProjectLyrics = songManifest.lyricsVersions?.length
                    ? { versions: songManifest.lyricsVersions }
                    : songManifest.lyrics
                        ? { versions: [createLyricsVersion(lyricsTextToDocument(songManifest.lyrics))] }
                        : createEmptyProjectLyrics();
                lyricVersionIdsByIdea.set(ideaId, new Set(lyrics.versions.map((version) => version.id)));

                ideas.push({
                    id: ideaId,
                    title: songManifest.title,
                    notes: songManifest.notes ?? "",
                    status: songManifest.status ?? "song",
                    completionPct: songManifest.completionPct,
                    kind: "project",
                    collectionId,
                    clips: remappedClips,
                    lyrics,
                    isTitleAutoGenerated: songManifest.isTitleAutoGenerated,
                    chordPalette: songManifest.chordPalette,
                    chordSheet: songManifest.chordSheet,
                    songGrid: sanitizeTempoMap(songManifest.songGrid),
                    songGridUpdatedAt: songManifest.songGridUpdatedAt,
                    customTags: songManifest.customTags,
                    clipGroups,
                    clipGroupAssignments,
                    isDraft: songManifest.isDraft,
                    importedAt: songManifest.importedAt,
                    sourceCreatedAt: songManifest.sourceCreatedAt,
                    createdAt: songManifest.createdAt,
                    lastActivityAt: songManifest.lastActivityAt,
                    isBookmarked: !!songManifest.isBookmarked,
                });
            }

            for (const clipManifest of collectionManifest.standaloneClips) {
                const ideaId = buildIdeaId();
                ideaIdMap.set(clipManifest.id, ideaId);
                importedIdeaIds.push(ideaId);

                let clips: ClipVersion[];
                if (clipManifest.takes?.length) {
                    // v7 full fidelity: every take of the clip idea, with lineage.
                    const takeIdMap = new Map<string, string>();
                    const takes: ClipVersion[] = [];
                    for (const takeManifest of clipManifest.takes) {
                        const takeId = buildClipId();
                        takeIdMap.set(takeManifest.id, takeId);
                        clipIdMapGlobal.set(takeManifest.id, takeId);
                        takes.push(
                            await materializeArchiveClip(
                                takeManifest,
                                parsed,
                                takeId,
                                warnings,
                                `${clipManifest.title} / ${takeManifest.title}`,
                                sourceDestinations
                            )
                        );
                    }
                    clips = finalizeImportedClips(takes, takeIdMap);
                } else {
                    // Pre-v7 (or standard) archives: the entry IS the primary take.
                    const clipId = buildClipId();
                    const primary = await materializeArchiveClip(
                        { ...clipManifest, parentClipId: undefined },
                        parsed,
                        clipId,
                        warnings,
                        clipManifest.title,
                        sourceDestinations
                    );
                    clips = [{ ...primary, isPrimary: true, isBookmarked: undefined }];
                }

                const ideaMeta = clipManifest.idea;
                ideas.push({
                    id: ideaId,
                    title: clipManifest.title,
                    notes: clipManifest.notes ?? "",
                    status: ideaMeta?.status ?? "clip",
                    completionPct: ideaMeta?.completionPct ?? 0,
                    kind: "clip",
                    collectionId,
                    clips,
                    customTags: ideaMeta?.customTags,
                    isDraft: ideaMeta?.isDraft,
                    isTitleAutoGenerated: ideaMeta?.isTitleAutoGenerated,
                    importedAt: ideaMeta?.importedAt ?? clipManifest.importedAt,
                    sourceCreatedAt: ideaMeta?.sourceCreatedAt ?? clipManifest.sourceCreatedAt,
                    createdAt: clipManifest.createdAt,
                    lastActivityAt: ideaMeta?.lastActivityAt ?? clipManifest.createdAt,
                    isBookmarked: !!clipManifest.isBookmarked,
                });
            }

            const importedPrimaryCollectionSourceId =
                parsed.manifest.libraryPreferences?.primaryCollectionIdByWorkspace?.[workspaceManifest.id];
            if (importedPrimaryCollectionSourceId === collectionManifest.id) {
                suggestedPrimaryCollectionIdByWorkspace[workspaceId] = collectionId;
            }
        }

        // Hidden-idea state (full fidelity) references idea ids, which only exist now.
        for (const collectionManifest of workspaceManifest.collections) {
            const collectionId = collectionIdMap.get(collectionManifest.id);
            const collection = collections.find((candidate) => candidate.id === collectionId);
            if (collection && collectionManifest.ideasListState) {
                collection.ideasListState = remapIdeasListState(collectionManifest.ideasListState, ideaIdMap);
            }
        }

        importedWorkspaceIds.push(workspaceId);
        importedWorkspaces.push({
            id: workspaceId,
            title: workspaceTitle,
            description: workspaceManifest.description,
            color: workspaceManifest.color,
            avatarKey: workspaceManifest.avatarKey,
            isArchived: false,
            collections,
            ideas,
            ...(workspaceManifest.ideasListState
                ? { ideasListState: remapIdeasListState(workspaceManifest.ideasListState, ideaIdMap) }
                : null),
            // Round-trip received provenance (device migration keeps packages
            // as packages). The ShareImport path overrides this downstream.
            origin: workspaceManifest.origin,
            received: workspaceManifest.received,
        });

        if (!localPrimaryWorkspaceId && importedPrimaryWorkspaceSourceId === workspaceManifest.id) {
            suggestedPrimaryWorkspaceId = workspaceId;
        }
    }

    // Remap global songbooks/setlists onto the freshly imported ids, dropping any
    // references whose songs/clips weren't part of this archive.
    const importedSongbooks: Songbook[] = (parsed.manifest.songbooks ?? [])
        .map((songbook) => ({
            id: buildEntityId("songbook"),
            title: songbook.title,
            createdAt: songbook.createdAt,
            updatedAt: songbook.updatedAt,
            items: (songbook.items ?? [])
                .map((item) => {
                    const workspaceId = workspaceIdMap.get(item.workspaceId);
                    const ideaId = ideaIdMap.get(item.ideaId);
                    if (!workspaceId || !ideaId) return null;
                    // A lyric chart needs its version to have travelled with the song.
                    if (item.kind === "lyricChart" && item.versionId && !lyricVersionIdsByIdea.get(ideaId)?.has(item.versionId)) {
                        return null;
                    }
                    return { ...item, id: buildEntityId("songbook-item"), workspaceId, ideaId };
                })
                .filter((item): item is Songbook["items"][number] => item !== null),
        }))
        .filter((songbook) => songbook.items.length > 0);

    const importedSetlists: Setlist[] = (parsed.manifest.setlists ?? [])
        .map((setlist) => ({
            id: buildEntityId("setlist"),
            title: setlist.title,
            createdAt: setlist.createdAt,
            updatedAt: setlist.updatedAt,
            entries: (setlist.entries ?? [])
                .map((entry) => {
                    const workspaceId = workspaceIdMap.get(entry.workspaceId);
                    const ideaId = ideaIdMap.get(entry.ideaId);
                    if (!workspaceId || !ideaId) return null;
                    return {
                        ...entry,
                        id: buildEntityId("setlist-entry"),
                        workspaceId,
                        ideaId,
                        clipIds: (entry.clipIds ?? [])
                            .map((clipId) => clipIdMapGlobal.get(clipId))
                            .filter((clipId): clipId is string => !!clipId),
                        lyricVersionIds: (entry.lyricVersionIds ?? []).filter((versionId) =>
                            lyricVersionIdsByIdea.get(ideaId)?.has(versionId)
                        ),
                    };
                })
                .filter((entry): entry is Setlist["entries"][number] => entry !== null),
        }))
        .filter((setlist) => setlist.entries.length > 0);

    return {
        importedWorkspaces,
        importedNotes,
        importedSongbooks,
        importedSetlists,
        suggestedPrimaryWorkspaceId,
        suggestedPrimaryCollectionIdByWorkspace,
        bluetoothMonitoringCalibrations,
        importedWorkspaceIds,
        importedIdeaIds,
        warnings,
    };
}
