import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system/legacy";
import { importRecordedAudioAsset } from "./audioStorage";
import { useStore } from "../state/useStore";
import { appActions } from "../state/actions";
import { i18n } from "../i18n/instance";
import { buildDefaultIdeaTitle } from "../utils";
import type { ClipVersion, Workspace } from "../types";
import { persistLog } from "./persistLog";

const PENDING_RECORDING_KEY = "songnook-pending-recording";

/**
 * A take that was attached in memory but whose metadata write did not durably land
 * (2026-09-07 field report: the audio survived, the store entry did not). Written by the
 * save path when its flush fails; consumed on the next launch, where the store either
 * turns out to hold the clip after all (passive persist caught up) or gets it re-attached.
 */
export type AttachedRecordingJournal = {
    ideaId: string;
    clipId: string;
    audioUri: string;
    /** The idea's title at save time — restores a rename the store may have lost. */
    ideaTitle: string;
    ideaTitleAutoGenerated: boolean;
    clipTitle: string;
    durationMs?: number;
    waveformPeaks?: number[];
    createdAt: number;
};

type PendingRecordingSession = {
    fileUri: string;
    startedAt: number;
    updatedAt: number;
    attached?: AttachedRecordingJournal;
};

export type RecordingRecoveryResult =
    | { status: "none" }
    | { status: "recovered"; title: string }
    | { status: "missing" }
    | { status: "failed"; message: string };

function buildRecoveredRecordingTitle(startedAt: number) {
    // Same auto-name convention every fresh capture gets ("11:45AM Aug 26th"),
    // with a short recovered marker — the old "Recovered Recording 07/29/2026,
    // 7:51 PM" format truncated on cards and mixed date styles (audit B12).
    return i18n.t("defaults.recoveredClipTitle", { name: buildDefaultIdeaTitle(startedAt) });
}

async function readPendingRecordingSession(): Promise<PendingRecordingSession | null> {
    try {
        const raw = await AsyncStorage.getItem(PENDING_RECORDING_KEY);
        if (!raw) return null;
        const parsed = JSON.parse(raw) as PendingRecordingSession;
        if (typeof parsed.fileUri !== "string" || !Number.isFinite(parsed.startedAt)) {
            return null;
        }
        return parsed;
    } catch {
        return null;
    }
}

export async function persistPendingRecordingSession(fileUri: string, startedAt: number) {
    await AsyncStorage.setItem(
        PENDING_RECORDING_KEY,
        JSON.stringify({
            fileUri,
            startedAt,
            updatedAt: Date.now(),
        } satisfies PendingRecordingSession)
    );
}

/**
 * Replace the in-flight marker with an "attached but not durable" journal. The marker
 * now points at the MANAGED file (the recorder temp is redundant and gets cleaned up as
 * usual), so the next launch can re-attach instead of re-importing a duplicate.
 */
export async function persistAttachedRecordingJournal(entry: AttachedRecordingJournal) {
    const session = await readPendingRecordingSession();
    await AsyncStorage.setItem(
        PENDING_RECORDING_KEY,
        JSON.stringify({
            fileUri: entry.audioUri,
            startedAt: session?.startedAt ?? entry.createdAt,
            updatedAt: Date.now(),
            attached: entry,
        } satisfies PendingRecordingSession)
    );
}

export async function clearPendingRecordingSession() {
    await AsyncStorage.removeItem(PENDING_RECORDING_KEY);
}

function libraryHasClip(workspaces: Workspace[], clipId: string): boolean {
    return workspaces.some((workspace) =>
        workspace.ideas.some((idea) => idea.clips.some((clip) => clip.id === clipId))
    );
}

function findIdeaLocation(workspaces: Workspace[], ideaId: string) {
    for (const workspace of workspaces) {
        const idea = workspace.ideas.find((candidate) => candidate.id === ideaId);
        if (idea) return { workspace, idea };
    }
    return null;
}

/** Put a journaled take back on its idea — any workspace, not just the active one. */
function reattachJournaledClip(journal: AttachedRecordingJournal): boolean {
    const location = findIdeaLocation(useStore.getState().workspaces, journal.ideaId);
    if (!location) return false;
    const now = Date.now();
    const clip: ClipVersion = {
        id: journal.clipId,
        title: journal.clipTitle,
        isTitleAutoGenerated: true,
        notes: "",
        createdAt: journal.createdAt,
        isPrimary: location.idea.clips.length === 0,
        audioUri: journal.audioUri,
        durationMs: journal.durationMs,
        waveformPeaks: journal.waveformPeaks,
    };
    useStore.setState((store) => ({
        workspaces: store.workspaces.map((workspace) =>
            workspace.id !== location.workspace.id
                ? workspace
                : {
                    ...workspace,
                    ideas: workspace.ideas.map((idea) => {
                        if (idea.id !== journal.ideaId) return idea;
                        // A rename the store lost comes back too — but never over a name
                        // the user gave the idea after the journal was written.
                        const restoreTitle =
                            idea.isTitleAutoGenerated !== false && !journal.ideaTitleAutoGenerated;
                        return {
                            ...idea,
                            title: restoreTitle ? journal.ideaTitle : idea.title,
                            isTitleAutoGenerated: restoreTitle ? false : idea.isTitleAutoGenerated,
                            clips: [clip, ...idea.clips],
                            lastActivityAt: Math.max(idea.lastActivityAt, now),
                        };
                    }),
                }
        ),
    }));
    return true;
}

export async function recoverPendingRecordingSession(): Promise<RecordingRecoveryResult> {
    const session = await readPendingRecordingSession();
    if (!session) {
        return { status: "none" };
    }

    try {
        // Attached-but-not-durable journal: the store may have caught up, or may not.
        if (session.attached) {
            const journal = session.attached;
            if (libraryHasClip(useStore.getState().workspaces, journal.clipId)) {
                await clearPendingRecordingSession();
                return { status: "none" };
            }
            const info = await FileSystem.getInfoAsync(journal.audioUri);
            if (!info.exists || (typeof info.size === "number" && info.size <= 0)) {
                await clearPendingRecordingSession();
                return { status: "missing" };
            }
            if (reattachJournaledClip(journal)) {
                await clearPendingRecordingSession();
                persistLog("recording.recovered", `re-attached ${journal.clipId} to ${journal.ideaId}`);
                return { status: "recovered", title: journal.ideaTitle };
            }
            // The idea itself is gone: fall through and land the take in the inbox.
        }

        const info = await FileSystem.getInfoAsync(session.fileUri);
        if (!info.exists || (typeof info.size === "number" && info.size <= 0)) {
            await clearPendingRecordingSession();
            return { status: "missing" };
        }

        const store = useStore.getState();
        const workspaceId =
            store.activeWorkspaceId ??
            store.workspaces.find((workspace) => !workspace.isArchived)?.id ??
            null;

        if (!workspaceId) {
            return { status: "failed", message: "No active workspace available for recovery." };
        }

        const workspace = store.workspaces.find((candidate) => candidate.id === workspaceId) ?? null;
        const collectionId =
            workspace?.collections[0]?.id ?? store.addCollection(workspaceId, "Inbox", null);

        const clipId = `recovered-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
        const managedAudio = await importRecordedAudioAsset(session.fileUri, clipId);
        const title = session.attached && !session.attached.ideaTitleAutoGenerated
            ? session.attached.ideaTitle
            : buildRecoveredRecordingTitle(session.startedAt);

        appActions.importClipToCollection(collectionId, {
            title,
            audioUri: managedAudio.audioUri,
            durationMs: managedAudio.durationMs,
            waveformPeaks: managedAudio.waveformPeaks,
            createdAt: session.startedAt,
            importedAt: Date.now(),
            sourceCreatedAt: session.startedAt,
        });

        if (session.fileUri !== managedAudio.audioUri) {
            await FileSystem.deleteAsync(session.fileUri, { idempotent: true }).catch(() => {});
        }

        await clearPendingRecordingSession();
        persistLog("recording.recovered", "imported to inbox");
        return { status: "recovered", title };
    } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown recovery failure.";
        console.warn("[RecordingRecovery] Failed to recover pending recording", error);
        return { status: "failed", message };
    }
}
