#!/usr/bin/env node
/**
 * docs/privacy-policy.md + docs/terms-of-use.md → src/pages/legal.generated.ts
 *
 * The markdown in docs/ is the single source of truth (it is what the founder
 * reviews and what the store listings link to). This turns it into HTML at build
 * time so the Worker serves it with zero runtime dependencies — the docs use only
 * headings, paragraphs, bullets and bold, so a 40-line converter is all it takes.
 * Re-run after editing either doc:  npm run build:legal
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docs = resolve(here, "../../../docs");

const escapeHtml = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const inline = (s) => escapeHtml(s).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

function toHtml(md) {
  const lines = md.split(/\r?\n/);
  const out = [];
  let para = [];
  let list = [];
  let title = "";
  let effective = "";
  const flushPara = () => { if (para.length) { out.push(`<p>${inline(para.join(" "))}</p>`); para = []; } };
  const flushList = () => { if (list.length) { out.push(`<ul>${list.map((l) => `<li>${inline(l)}</li>`).join("")}</ul>`); list = []; } };
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^# /.test(line)) { flushPara(); flushList(); title = line.slice(2).trim(); continue; }
    if (/^## /.test(line)) { flushPara(); flushList(); out.push(`<h2>${inline(line.slice(3).trim())}</h2>`); continue; }
    if (/^- /.test(line)) { flushPara(); list.push(line.slice(2).trim()); continue; }
    if (line.trim() === "") { flushPara(); flushList(); continue; }
    const eff = line.match(/^\*\*Effective date:\*\*\s*(.+)$/);
    if (eff) { flushPara(); flushList(); effective = eff[1].trim(); continue; }
    if (list.length) flushList();
    para.push(line.trim());
  }
  flushPara(); flushList();
  if (!title) throw new Error("legal doc has no H1 title");
  return { title, effective, html: out.join("\n") };
}

const privacy = toHtml(readFileSync(resolve(docs, "privacy-policy.md"), "utf8"));
const terms = toHtml(readFileSync(resolve(docs, "terms-of-use.md"), "utf8"));

const ts = `// GENERATED by scripts/build-legal.mjs from docs/*.md — do not edit by hand.
// Re-run \`npm run build:legal\` after changing the markdown.
export const LEGAL = {
  privacy: ${JSON.stringify(privacy, null, 2)},
  terms: ${JSON.stringify(terms, null, 2)},
} as const;
`;
writeFileSync(resolve(here, "../src/pages/legal.generated.ts"), ts);
console.log(`legal.generated.ts: privacy (${privacy.html.length}b, ${privacy.effective}) · terms (${terms.html.length}b, ${terms.effective})`);
