import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { colors, radii } from "../design/tokens";

// Activity view: heatmap, day/month/range breakdowns, filters.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const activityStyles = {
  activityRangeBanner: {
    marginBottom: 10,
    minHeight: 36,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityRangeBannerCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activityRangeBannerText: {
    flex: 1,
    fontSize: 12,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityRangeBannerClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F1ED",
  },
  activityChipRow: {
    flexGrow: 0,
    marginBottom: 10,
  },
  activityWorkspaceFilterWrap: {
    position: "relative",
    zIndex: 20,
    marginBottom: 10,
  },
  activityWorkspaceFilterTrigger: {
    minHeight: 36,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  activityWorkspaceFilterLabel: {
    flex: 1,
    fontSize: 12,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityWorkspaceFilterMenu: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    borderRadius: radii.xl,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    shadowColor: "#1b1c1a",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  activityWorkspaceFilterOption: {
    minHeight: 40,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  activityWorkspaceFilterOptionActive: {
    backgroundColor: "#FDFBF7",
  },
  activityWorkspaceFilterOptionText: {
    fontSize: 13,
    color: "#524440",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityWorkspaceFilterOptionTextActive: {
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityChipScroll: {
    gap: 8,
    paddingRight: 8,
  },
  activityFilterChip: {
    minHeight: 34,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activityFilterChipActive: {
    backgroundColor: "#1b1c1a",
    borderColor: "#1b1c1a",
  },
  activityFilterChipText: {
    fontSize: 12,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityFilterChipTextActive: {
    color: "#ffffff",
  },
  activityControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  activitySegmentStack: {
    gap: 8,
    marginBottom: 10,
  },
  activitySegmentWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    flex: 1,
  },
  activitySegmentBtn: {
    minHeight: 34,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activitySegmentBtnActive: {
    backgroundColor: "#1b1c1a",
    borderColor: "#1b1c1a",
  },
  activitySegmentText: {
    fontSize: 12,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activitySegmentTextActive: {
    color: "#ffffff",
  },
  activityYearControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activityTodayBtn: {
    borderRadius: 4,
    backgroundColor: "#e4deda",
    paddingHorizontal: 10,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  activityTodayBtnText: {
    fontSize: 12,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityYearBtn: {
    width: 30,
    height: 30,
    borderRadius: 4,
    backgroundColor: "#e4deda",
    alignItems: "center",
    justifyContent: "center",
  },
  activityYearText: {
    fontSize: 14,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
    minWidth: 44,
    textAlign: "center",
  },
  activitySummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  activitySummaryText: {
    fontSize: 12,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activitySummaryBlock: {
    flex: 1,
    gap: 4,
  },
  activityHintText: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  activityLegendLabel: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityLegendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 2,
  },
  activityScreenContent: {
    paddingBottom: 24,
    gap: 12,
  },
  activityCard: {
    borderWidth: 0,
    borderRadius: 6,
    backgroundColor: "#efeeea",
    padding: 12,
    gap: 10,
    shadowOpacity: 0,
    elevation: 0,
  },
  activityHeatmapContent: {
    gap: 8,
  },
  activityHeatmapHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  activityHeatmapHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  activityHeatmapEyebrow: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  activityHeatmapSelectedLabel: {
    fontSize: 15,
    lineHeight: 20,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityHeatmapScopeLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityHeatmapHeaderHint: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityMonthRow: {
    position: "relative",
    minHeight: 16,
  },
  activityMonthPressable: {
    position: "absolute",
    minHeight: 16,
    justifyContent: "center",
  },
  activityMonthPressableActive: {
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryDeep,
  },
  activityMonthLabel: {
    position: "relative",
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityMonthLabelActive: {
    color: colors.primaryDeep,
  },
  activityMonthSummaryCard: {
    borderWidth: 1,
    borderColor: "#E8E4DF",
    borderRadius: radii.xl,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityMonthSummaryCopy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  activityMonthSummaryTitle: {
    fontSize: 13,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityMonthSummaryMeta: {
    fontSize: 12,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityGridRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  activityWeekdayLabels: {
    width: 16,
    gap: 4,
    paddingTop: 17,
  },
  activityWeekdayLabel: {
    height: 14,
    fontSize: 9,
    color: "#84736f",
    textAlign: "center",
    includeFontPadding: false,
  },
  activityWeeksWrap: {
    flexDirection: "row",
    gap: 4,
  },
  activityWeekColumn: {
    gap: 4,
  },
  activityDayCell: {
    borderRadius: 3,
    backgroundColor: "transparent",
    padding: 0,
  },
  activityDayCellFill: {
    flex: 1,
    borderRadius: 2,
  },
  activityDayCellFillSelected: {
    borderRadius: 2,
  },
  activityDayCellRangeSelected: {
    borderColor: colors.primaryDeep,
    borderWidth: 1.25,
    padding: 1.5,
  },
  activityDayCellToday: {
    borderColor: "#1b1c1a",
    borderWidth: 1.5,
  },
  activityDayCellPressed: {
    transform: [{ scale: 0.94 }],
  },
  activityResultsSection: {
    gap: 10,
  },
  activityResultsSummaryText: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  activityResultsList: {
    gap: 8,
  },
  activityResultEmptyCard: {
    gap: 6,
    backgroundColor: "#efeeea",
    borderWidth: 0,
    borderRadius: 4,
    shadowOpacity: 0,
    elevation: 0,
  },
  activityResultEmptyTitle: {
    fontSize: 14,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityResultEmptyText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityRangeWorkspaceGroupList: {
    gap: 12,
  },
  activityRangeCollectionList: {
    gap: 8,
  },
  activityRangeCollectionCard: {
    borderWidth: 1,
    borderColor: "#E8E4DF",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  activityRangeCollectionCopy: {
    gap: 4,
  },
  activityRangeCollectionTitle: {
    fontSize: 14,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityRangeCollectionMeta: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityRangeCollectionActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityRangeCollectionCount: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityDayModalCard: {
    gap: 10,
    maxHeight: "72%",
  },
  activityDayEntryScroll: {
    maxHeight: 340,
  },
  activityDayWorkspaceGroupList: {
    gap: 12,
    paddingBottom: 4,
  },
  activityDayWorkspaceGroup: {
    gap: 8,
  },
  activityDayWorkspaceTitle: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    paddingHorizontal: 2,
  },
  activityDayEntryList: {
    gap: 8,
    paddingBottom: 4,
  },
  activityDayEntryCard: {
    borderRadius: 4,
    backgroundColor: "#efeeea",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  activityDayEntryTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  activityDayEntryTitleWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  activityDayEntryTitle: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityDayEntryMetric: {
    fontSize: 11,
    color: "#4a3f3b",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  activityDayEntryMeta: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  activityDayModalActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  activityDayOpenBtn: {
    minHeight: 34,
  },
  activityDayCloseBtn: {
    minWidth: 90,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
