import { StyleSheet } from "react-native";
import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { colors, radii, shadows } from "../design/tokens";

// Shared shell, cards, buttons, modals, headers and other cross-screen primitives.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const baseStyles = {
  screen: {
    flex: 1,
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 16,
  },
  flexFill: {
    flex: 1,
  },
  screenIdeas: {
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 14,
  },
  screenProjectDetail: {
    backgroundColor: "#FDFBF7",
  },
  screenClipDetail: {
    backgroundColor: "#FDFBF7",
  },
  hamburgerBtn: {
    width: 38,
    height: 38,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E8E4DF",
    shadowColor: "#1b1c1a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(27,28,26,0.18)",
  },
  drawerPanel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: "84%",
    maxWidth: 340,
    backgroundColor: "#fff",
    borderTopRightRadius: 26,
    borderBottomRightRadius: 26,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    gap: 8,
    shadowColor: "#1b1c1a",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 12,
  },
  sideNavLabel: {
    fontSize: 20,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  breadcrumbText: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  contextPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: "#D7C2BD",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#fff",
  },
  contextPillText: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.2,
  },
  sideNavToggle: {
    borderWidth: 1,
    borderColor: "#D7C2BD",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  shellContent: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  headerLeftCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  backLinkBtn: {
    minHeight: 32,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  backLinkText: {
    fontSize: 13,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#84736f",
  },
  title: { fontSize: 22, fontFamily: "PlusJakartaSans_700Bold", color: "#1b1c1a" },
  pageTitleCompact: { fontSize: 20, fontFamily: "PlayfairDisplay_600SemiBold", color: colors.textPrimary },
  titleInlineWrap: {
    marginHorizontal: 8,
    position: "relative",
    alignSelf: "stretch",
  },
  titleInlineInput: {
    borderWidth: 1,
    borderColor: "#D7C2BD",
    backgroundColor: "#fff",
    borderRadius: 4,
    paddingLeft: 10,
    paddingRight: 64,
    paddingVertical: 6,
    fontSize: 20,
    lineHeight: 26,
    fontFamily: "PlayfairDisplay_600SemiBold",
    color: "#1b1c1a",
    minHeight: 38,
    textAlignVertical: "top",
  },
  titleInlineInputPlaceholder: {
    fontFamily: "PlusJakartaSans_500Medium",
  },
  titleInlineBtns: {
    position: "absolute",
    right: 8,
    top: "50%",
    marginTop: -12,
    flexDirection: "row",
    gap: 6,
  },
  titleClearBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F1ED",
    borderWidth: 1,
    borderColor: "#E8E4DF",
  },
  subtitle: { marginTop: 2, marginBottom: 12, fontSize: 13, color: "#84736f" },
  inputRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginBottom: 8,
    flexWrap: "wrap",
  },
  input: {
    flex: 1,
    minWidth: 120,
    borderWidth: 1,
    borderColor: "#D7C2BD",
    backgroundColor: "#fff",
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  notesInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#D7C2BD",
    backgroundColor: "#fff",
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 64,
    textAlignVertical: "top",
    marginBottom: 6,
  },
  primaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: radii.round,
    minHeight: 36,
    paddingHorizontal: 16,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: {
    fontSize: 13,
    color: colors.onPrimary,
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.2,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: radii.round,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  backBtnText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    color: colors.textStrong,
  },
  listContent: { paddingVertical: 10, gap: 8 },
  listContentTimeline: {
    paddingTop: 34,
  },
  listContentCompact: {
    gap: 0,
    paddingVertical: 6,
  },
  listRowWrap: { flexDirection: "row", alignItems: "stretch", gap: 6 },
  cardFlex: { flex: 1 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    padding: 14,
    gap: 6,
    ...shadows.card,
    position: "relative",
  },
  cardDisabled: {
    opacity: 0.5,
  },
  listCardRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  listCardMain: { flex: 1, gap: 2 },
  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  cardTitleRow: { flex: 1, flexDirection: "row", alignItems: "center", gap: 6 },
  cardTitle: { flex: 1, fontSize: 16, fontFamily: "PlusJakartaSans_600SemiBold", color: colors.textPrimary },
  cardMeta: { fontSize: 12, color: colors.textSecondary, fontFamily: "PlusJakartaSans_400Regular" },
  cardMetaWarning: { color: "#b45309" },
  badge: {
    fontSize: 10,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.3,
  },
  badgeCurrent: {
    backgroundColor: colors.primary,
    color: colors.onPrimary,
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.4,
    overflow: "hidden",
  },
  badgeArchived: {
    backgroundColor: "#E8E4DF",
    color: "#524440",
    overflow: "hidden",
  },
  badgeGhostProject: {
    backgroundColor: "#166534",
    color: "#ffffff",
    overflow: "hidden",
  },
  secondaryBtn: {
    alignSelf: "flex-start",
    borderRadius: radii.round,
    minHeight: 36,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.surfaceHigh,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: { fontSize: 13, color: colors.textStrong, fontFamily: "PlusJakartaSans_600SemiBold" },
  setPrimaryBtn: {
    alignSelf: "flex-start",
    marginTop: 2,
    borderWidth: 1,
    borderColor: "#a89994",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#fff",
    minWidth: 56,
  },
  setPrimaryBtnText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
    textAlign: "center",
  },
  pressDown: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  pressDownStrong: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },
  btnDisabled: { opacity: 0.5 },
  iconBtnText: { fontSize: 16, lineHeight: 18 },
  emptyText: { marginTop: 10, color: "#84736f" },
  rowButtons: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
  navBar: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  cardSelectionLead: {
    width: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitleRowCompact: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  dangerBtn: {
    borderWidth: 1,
    borderColor: colors.danger,
    backgroundColor: colors.dangerSurface,
    borderRadius: 8,
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 40,
  },
  dangerBtnDisabled: {
    borderWidth: 0,
    backgroundColor: "#F4F1ED",
  },
  dangerBtnText: { color: colors.danger, fontFamily: "PlusJakartaSans_700Bold", fontSize: 14 },
  cardSelected: { borderColor: colors.primary, borderWidth: 1.5 },
  listCardSelected: {
    borderColor: colors.primary,
    borderWidth: 1.5,
    ...shadows.cardActive,
  },
  cardEditing: { borderColor: "#B87D6B", borderWidth: 2 },
  cardHighlight: { borderColor: "#22c55e", borderWidth: 2 },
  cardHighlightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#dcfce7",
    borderRadius: radii.xl,
  },
  primaryPickCol: {
    width: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    gap: 2,
    backgroundColor: "transparent",
  },
  primaryPickStarWrap: {
    width: 22,
    height: 22,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "#1b1c1a",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  primaryPickLabel: {
    fontSize: 8,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#1b1c1a",
  },
  cardGhostProject: {
    borderStyle: "dashed",
    borderColor: "#16a34a",
    borderWidth: 2,
    backgroundColor: "#f0fdf4",
  },
  cardInsideHover: {
    transform: [{ scale: 1.02 }],
  },
  cardActiveInside: {
    transform: [{ scale: 0.97 }],
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(27,28,26,0.25)",
    justifyContent: "center",
    padding: 20,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(27,28,26,0.25)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    padding: 14,
    gap: 1,
  },
  modalTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
    marginBottom: 8,
  },
  bottomSheetBackdrop: {
    flex: 1,
    // Warm charcoal scrim instead of cold slate.
    backgroundColor: "rgba(27,28,26,0.35)",
    justifyContent: "flex-end",
  },
  bottomSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  bottomSheetCard: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 0,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    // No hard border — soft ambient lift instead (Nocturne Paper).
    borderWidth: 0,
    paddingHorizontal: 16,
    marginHorizontal: 0,
    marginBottom: 0,
    shadowColor: "#3D3732",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: -3 },
    shadowRadius: 18,
    elevation: 16,
  },
  bottomSheetDragZone: {
    paddingTop: 10,
    paddingBottom: 10,
    alignItems: "center",
  },
  bottomSheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 999,
    // Warm muted handle.
    backgroundColor: "#D7C2BD",
    marginBottom: 4,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
