import { StyleSheet } from "react-native";
import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { radii } from "../design/tokens";

// Ideas list rows, cards and list chrome.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const ideasListStyles = {
  ideasListContentFloating: {
    paddingBottom: 178,
  },
  ideasListContentSelection: {
    paddingBottom: 168,
  },
  ideasListItemWrap: {
    gap: 6,
  },
  ideasListLeadHotzone: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 76,
    zIndex: 4,
  },
  ideasListLeadHotzoneCompact: {
    width: 70,
  },
  ideasListLeadHotzoneExpanded: {
    width: 76,
  },
  ideasListLeadHotzoneInline: {
    flexDirection: "column",
    width: 46,
  },
  ideasListLeadHotzoneTop: {
    flex: 1,
    width: "100%",
  },
  ideasListLeadHotzoneBottom: {
    flex: 1,
    width: "100%",
  },
  ideasListCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    // Lighter border + tighter, quieter shadow so cards feel less imposing.
    borderColor: "rgba(215,194,189,0.18)",
    paddingVertical: 8,
    paddingHorizontal: 11,
    position: "relative",
    shadowColor: "#3D3732",
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 4,
    elevation: 1,
    minHeight: 60,
  },
  ideasListCardCompact: {
    borderRadius: radii.lg,
    paddingVertical: 5,
    paddingHorizontal: 9,
    minHeight: 0,
  },
  ideasListProjectCard: {
    borderLeftWidth: 3,
  },
  ideasListCardNowPlaying: {
    borderColor: "rgba(184,125,107,0.4)",
  },
  ideasListCardSelected: {
    borderColor: "#B87D6B",
    borderWidth: 2,
    backgroundColor: "#FDF5F2",
  },
  ideasListCardCornerBadge: {
    position: "absolute",
    top: 7,
    right: 8,
    zIndex: 2,
    width: 20,
    height: 20,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  ideasListCardHighlightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(184,125,107,0.22)",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "rgba(184,125,107,0.55)",
  },
  ideasListExpandedStaticWrap: {
    flex: 1,
    justifyContent: "space-between",
  },
  ideasListExpandedHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ideasListExpandedHeaderLead: {
    width: 46,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListExpandedHeaderMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  ideasListExpandedMetaGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  ideasListExpandedMetaRows: {
    gap: 2,
  },
  ideasListExpandedMetaGridRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ideasListExpandedMetaLeadSpacer: {
    width: 46,
    flexShrink: 0,
  },
  ideasListExpandedMetaLeftCol: {
    width: 46,
    minHeight: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListExpandedMetaCenterCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  ideasListExpandedMetaRightCol: {
    width: 72,
    gap: 1,
    flexShrink: 0,
  },
  ideasListExpandedMetaRightIndicators: {
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  ideasListCardRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  ideasListLeadCol: {
    width: 46,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexShrink: 0,
    alignSelf: "stretch",
  },
  ideasListLeadColInlineActive: {
    justifyContent: "space-evenly",
  },
  ideasListLeadDurationSlot: {
    width: "100%",
    minHeight: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasListLeadDurationText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    lineHeight: 14,
    color: "#84736f",
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  ideasListCardMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
    justifyContent: "space-between",
  },
  ideasListCardMainCompact: {
    gap: 4,
  },
  ideasListCardTopBlock: {
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  ideasListCardBottomBlock: {
    gap: 1,
    minWidth: 0,
  },
  ideasListCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  ideasListCardTrailing: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    flexShrink: 0,
  },
  ideasListFavoriteBtn: {
    padding: 2,
  },
  ideasListCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flex: 1,
    minWidth: 0,
  },
  ideasListCardTitleRowExpanded: {
    alignItems: "flex-start",
  },
  ideasListTitleIconWrap: {
    width: 14,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListCardTitle: {
    flex: 1,
    minWidth: 0,
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 14,
    lineHeight: 18,
    color: "#1C1C19",
  },
  ideasListCardTitleProject: {
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  ideasListCardTitleCompact: {
    fontSize: 13,
    lineHeight: 16,
  },
  ideasListCardTitleHighlight: {
    backgroundColor: "#fde68a",
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  ideasListCardMeta: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    color: "#84736f",
    },
  ideasListCreatedAtText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 10,
    lineHeight: 12,
    color: "#84736f",
    fontVariant: ["tabular-nums"],
  },
  ideasListExpandedMetaStack: {
    gap: 1,
  },
  ideasListDateRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasListDateStack: {
    gap: 2,
    flex: 1,
    minWidth: 0,
  },
  ideasListMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 14,
  },
  ideasListMetaLeftCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 14,
    flexShrink: 1,
    minWidth: 0,
  },
  ideasListMetaToken: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  ideasListMetaIconWrap: {
    width: 13,
    height: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasListMetaDurationText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    lineHeight: 14,
    color: "#524440",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaDurationTextCompact: {
    fontSize: 12,
    lineHeight: 13,
  },
  ideasListMetaText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    lineHeight: 13,
    color: "#84736f",
    fontVariant: ["tabular-nums"],
  },
  ideasListCompactProgressText: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 11,
    lineHeight: 13,
    color: "#84736f",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaRightCol: {
    width: 72,
    alignItems: "flex-end",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListMetaRightColInner: {
    width: "100%",
    alignItems: "flex-end",
    justifyContent: "center",
    minHeight: 14,
  },
  ideasListMetaRightCluster: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
    minHeight: 12,
  },
  ideasListMetaSizeText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    lineHeight: 14,
    color: "#84736f",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasListDateSizeCol: {
    width: 72,
    alignItems: "flex-end",
    justifyContent: "center",
    flexShrink: 0,
    minHeight: 28,
  },
  ideasListDateSizeText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 10,
    lineHeight: 13,
    color: "#84736f",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaSizeTextCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  ideasListMetaSeparator: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 10,
    lineHeight: 12,
    color: "#B8A8A3",
    },
  ideasListStatusBadgeText: {
    fontSize: 9,
    lineHeight: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 46,
    textAlign: "center",
  },
  ideasListProgressText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    lineHeight: 12,
    color: "#84736f",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasListNowPlayingTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 2,
    backgroundColor: "rgba(215,194,189,0.4)",
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: "hidden",
  },
  ideasListNowPlayingFill: {
    height: "100%",
    backgroundColor: "#B87D6B",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
