import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { colors, radii } from "../design/tokens";

// Library and workspace browsing: collections, playlists, pickers.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const libraryStyles = {
  workspaceBrowseSection: {
    marginTop: 6,
    marginBottom: 8,
    gap: 8,
  },
  workspaceBrowseSectionTitle: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    paddingHorizontal: 4,
  },
  workspaceBrowseCollectionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workspaceBrowseMatchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  workspaceBrowseMatchBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: "100%",
  },
  workspaceBrowseMatchText: {
    fontSize: 12,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
    flexShrink: 1,
  },
  workspaceBrowseMatchContext: {
    color: "#84736f",
    fontFamily: "PlusJakartaSans_500Medium",
  },
  workspaceBrowseMatchHighlight: {
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  workspaceBrowseChildList: {
    gap: 8,
  },
  workspaceBrowseChildCard: {
    paddingVertical: 14,
    borderColor: "#D7C2BD",
    backgroundColor: "#FDFBF7",
  },
  workspaceBrowseChildTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  workspaceBrowseChildTitleWrap: {
    flex: 1,
    gap: 8,
  },
  workspaceBrowseChildMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workspaceBrowseChildChevron: {
    width: 26,
    height: 26,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "#D7C2BD",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  collectionBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  collectionBreadcrumbLink: {
    paddingVertical: 2,
  },
  collectionBreadcrumbText: {
    fontSize: 12,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  collectionBreadcrumbTextActive: {
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  collectionInlineActionBtn: {
    width: 28,
    height: 28,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FDFBF7",
    borderWidth: 1,
    borderColor: "#E8E4DF",
  },
  collectionMoveScroll: {
    maxHeight: 320,
  },
  collectionMoveScrollContent: {
    gap: 12,
    paddingTop: 10,
  },
  collectionMoveSection: {
    gap: 8,
  },
  collectionMoveOptionList: {
    gap: 6,
  },
  collectionMoveOption: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  collectionMoveOptionSelected: {
    borderColor: "#a89994",
    backgroundColor: "#FDFBF7",
  },
  collectionMoveOptionCopy: {
    flex: 1,
    gap: 2,
  },
  collectionMoveOptionTitle: {
    fontSize: 13,
    color: "#524440",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  collectionMoveOptionTitleSelected: {
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  collectionMoveOptionSubtitle: {
    fontSize: 11,
    color: "#84736f",
  },
  projectCard: {
    backgroundColor: "#F4F1ED",
    borderColor: "#D7C2BD",
  },
  libraryScrollContent: {
    paddingBottom: 24,
    gap: 12,
  },
  libraryDetailHeader: {
    marginBottom: 2,
  },
  libraryPlaylistItemRow: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  libraryPlaylistItemRowActive: {
    backgroundColor: "#FDFBF7",
    borderColor: "#D7C2BD",
  },
  libraryPlaylistItemMain: {
    flex: 1,
    gap: 6,
  },
  libraryPlaylistItemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  libraryPlaylistItemTypePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  libraryPlaylistItemTypeText: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.3,
  },
  libraryPlaylistItemUnavailablePill: {
    borderRadius: 999,
    backgroundColor: colors.dangerSurface,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  libraryPlaylistItemUnavailableText: {
    fontSize: 10,
    color: colors.danger,
    fontFamily: "PlusJakartaSans_700Bold",
    letterSpacing: 0.3,
  },
  libraryPlaylistItemActions: {
    gap: 8,
  },
  libraryPickerBackRow: {
    minHeight: 34,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 4,
  },
  libraryPickerBackText: {
    fontSize: 13,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  libraryPickerSection: {
    gap: 8,
  },
  libraryPickerItemRow: {
    minHeight: 58,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  libraryPickerItemMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  libraryPickerItemCopy: {
    flex: 1,
    gap: 2,
  },
  libraryPickerFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#F4F1ED",
  },
  workspaceCardPrimary: {
    borderColor: "#e4d2a8",
    backgroundColor: "#fffdf7",
  },
  workspaceCardBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  workspacePrimaryButton: {
    width: 28,
    height: 28,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
  },
  workspacePrimaryButtonActive: {
    borderColor: "#e4d2a8",
    backgroundColor: "#fff7db",
  },
  collectionActionsModalCard: {
    gap: 10,
  },
  collectionActionsOptionList: {
    gap: 8,
  },
  collectionActionsOption: {
    minHeight: 44,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  collectionActionsOptionDestructive: {
    borderColor: colors.borderMuted,
    backgroundColor: colors.dangerSurface,
  },
  collectionActionsOptionLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  collectionActionsOptionText: {
    fontSize: 14,
    lineHeight: 18,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  collectionActionsOptionTextDestructive: {
    color: colors.danger,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
