import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { radii } from "../design/tokens";

// Settings screen: sections, accordions, toggles, storage, scopes.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const settingsStyles = {
  settingsScrollContent: {
    paddingBottom: 24,
    gap: 18,
  },
  settingsActionCard: {
    marginTop: 4,
    minHeight: 72,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  settingsActionCardCopy: {
    flex: 1,
    gap: 4,
  },
  settingsActionCardTitle: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    lineHeight: 20,
    color: "#1b1c1a",
  },
  settingsActionCardMeta: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    lineHeight: 18,
    color: "#84736f",
  },
  settingsSection: {
    gap: 10,
  },
  settingsAccordionShell: {
    gap: 0,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  settingsAccordionShellOpen: {
    borderColor: "#D7C2BD",
    backgroundColor: "#FDFBF7",
  },
  settingsAccordionHeader: {
    minHeight: 68,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  settingsAccordionHeaderOpen: {
    backgroundColor: "transparent",
  },
  settingsAccordionCopy: {
    flex: 1,
    gap: 2,
  },
  settingsAccordionTitle: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    lineHeight: 20,
    color: "#1b1c1a",
  },
  settingsAccordionHint: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 17,
    color: "#84736f",
  },
  settingsAccordionBody: {
    gap: 10,
    marginTop: 0,
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#E8E4DF",
    backgroundColor: "transparent",
  },
  settingsSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
  },
  settingsSectionLabel: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 11,
    lineHeight: 16,
    color: "#84736f",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  settingsSectionMeta: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    lineHeight: 16,
    color: "#a89994",
  },
  settingsSectionHint: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    lineHeight: 18,
    color: "#84736f",
  },
  settingsOptionStack: {
    gap: 8,
  },
  settingsChoiceRow: {
    minHeight: 60,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingsChoiceRowSelected: {
    borderColor: "#B87D6B",
    backgroundColor: "#FDF5F2",
  },
  settingsChoiceCopy: {
    flex: 1,
    gap: 2,
  },
  settingsChoiceTitle: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    lineHeight: 18,
    color: "#1b1c1a",
  },
  settingsChoiceMeta: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 17,
    color: "#84736f",
  },
  settingsScopeStack: {
    gap: 10,
  },
  settingsScopeGroup: {
    gap: 6,
  },
  settingsWorkspaceRow: {
    minHeight: 52,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsWorkspaceSelectZone: {
    flex: 1,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingsWorkspaceExpandBtn: {
    width: 34,
    height: 34,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FDFBF7",
    borderWidth: 1,
    borderColor: "#E8E4DF",
  },
  settingsScopeChildren: {
    marginLeft: 10,
    paddingLeft: 12,
    borderLeftWidth: 1,
    borderLeftColor: "#E8E4DF",
    gap: 6,
  },
  settingsScopeRow: {
    minHeight: 48,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingsScopeRowNested: {
    marginLeft: 18,
  },
  settingsScopeRowDisabled: {
    opacity: 0.78,
  },
  settingsScopeCopy: {
    flex: 1,
    gap: 2,
  },
  settingsScopeTitle: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    lineHeight: 18,
    color: "#1b1c1a",
  },
  settingsScopeMeta: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 16,
    color: "#84736f",
  },
  settingsToggleRow: {
    minHeight: 58,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsTogglePill: {
    width: 44,
    height: 26,
    borderRadius: 999,
    backgroundColor: "#E8E4DF",
    paddingHorizontal: 3,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  settingsTogglePillActive: {
    backgroundColor: "#B87D6B",
    alignItems: "flex-end",
  },
  settingsToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: radii.round,
    backgroundColor: "#ffffff",
  },
  settingsToggleThumbActive: {
    backgroundColor: "#ffffff",
  },
  settingsSummaryPanel: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: "#E8E4DF",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 12,
  },
  settingsSummaryTitle: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    lineHeight: 20,
    color: "#1b1c1a",
  },
  settingsSummaryMeta: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    lineHeight: 18,
    color: "#84736f",
  },
  settingsStoragePrimaryValue: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 28,
    lineHeight: 32,
    color: "#1b1c1a",
    fontVariant: ["tabular-nums"],
  },
  settingsStorageMetricRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  settingsStorageMetricCopy: {
    flex: 1,
    gap: 2,
  },
  settingsStorageMetricValue: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    lineHeight: 18,
    color: "#1b1c1a",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  settingsStoragePathRow: {
    gap: 4,
  },
  settingsStoragePathValue: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 17,
    color: "#84736f",
  },
  settingsStorageNote: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 17,
    color: "#84736f",
  },
  settingsActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  settingsPrimaryAction: {
    minWidth: 148,
  },
  settingsBusyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsBusyText: {
    flex: 1,
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 17,
    color: "#84736f",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
