import { StyleSheet } from "react-native";
import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { colors, radii } from "../design/tokens";

// Song detail screen: header, nav, breadcrumbs, tabs, summary, meta, notes.
// Raw style objects — merged and registered once via StyleSheet.create in ../styles.ts.
export const songDetailStyles = {
  songDetailHeader: {
    marginTop: 2,
    marginBottom: 10,
  },
  songDetailNavRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  songDetailNavLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  songDetailInlineBreadcrumbs: {
    flex: 1,
    minWidth: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: 0,
    flexWrap: "nowrap",
  },
  songDetailNavCompactTitle: {
    fontFamily: "PlusJakartaSans_500Medium",
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    lineHeight: 20,
    color: "#1b1c1a",
  },
  songDetailNavCompactTypeLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    lineHeight: 20,
    color: "#a89994",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  songDetailCompactTitleWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailBreadcrumbWrap: {
    flex: 1,
    minWidth: 0,
  },
  songDetailBreadcrumbScrollContent: {
    alignItems: "center",
    gap: 4,
    paddingRight: 8,
  },
  songDetailBreadcrumbChunk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailBreadcrumbTextHitbox: {
    minHeight: 18,
    justifyContent: "center",
  },
  songDetailBreadcrumbSeparator: {
    fontSize: 12,
    lineHeight: 14,
    color: "#B8A8A3",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailBreadcrumbText: {
    fontSize: 12,
    lineHeight: 14,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailBreadcrumbTextActive: {
    color: "#524440",
  },
  songDetailBreadcrumbEllipsis: {
    fontSize: 12,
    lineHeight: 14,
    color: "#B8A8A3",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailNavEditActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailNavTextAction: {
    minHeight: 30,
    borderRadius: radii.round,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F1ED",
    borderWidth: 1,
    borderColor: "rgba(215,194,189,0.5)",
  },
  songDetailNavTextActionPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  songDetailNavTextActionText: {
    fontSize: 12,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailNavTextActionPrimaryText: {
    fontSize: 12,
    color: "#ffffff",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailTitleBlock: {
    marginTop: 4,
    gap: 3,
  },
  songDetailTitleBlockHidden: {
    display: "none",
  },
  songDetailHeaderModeLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailTitleInputWrap: {
    marginHorizontal: 0,
    marginTop: 2,
  },
  songDetailTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 2,
  },
  songDetailTitleLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  songDetailPageTitle: {
    flex: 1,
    fontSize: 20,
    lineHeight: 24,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#1C1C19",
  },
  songDetailPageTitleLarge: {
    fontFamily: "PlayfairDisplay_600SemiBold",
    fontSize: 26,
    lineHeight: 32,
    color: "#1b1c1a",
  },
  songDetailPageTitleWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  songDetailTypeLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  songDetailTypeEyebrow: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    lineHeight: 14,
    color: "#a89994",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  songDetailBreadcrumbLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 1,
    marginBottom: 4,
    overflow: "hidden",
  },
  songDetailHeaderEditActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailHeaderActionBtn: {
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  songDetailDangerMenuText: {
    flex: 1,
    fontSize: 13,
    color: colors.danger,
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailTopStack: {
    gap: 8,
    marginBottom: 6,
  },
  songDetailProgressStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 1,
    marginBottom: 14,
  },
  songDetailProgressStripLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    color: "#a89994",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  songDetailProgressStripPercent: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    color: "#84736f",
    fontVariant: ["tabular-nums"],
  },
  songDetailSongTabs: {
    flexDirection: "row",
    marginTop: -2,
    marginBottom: 4,
    paddingHorizontal: 4,
    paddingVertical: 3,
    backgroundColor: "rgba(215,194,189,0.2)",
    borderRadius: 8,
  },
  songDetailSongTab: {
    flex: 1,
    paddingVertical: 6,
    alignItems: "center",
    borderRadius: 6,
  },
  songDetailSongTabActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#3D3732",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  songDetailSongTabText: {
    fontSize: 13,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailSongTabTextActive: {
    color: "#1C1C19",
  },
  songDetailTabScroll: {
    flex: 1,
  },
  songDetailTabScrollContent: {
    gap: 10,
    paddingBottom: 0,
  },
  songDetailTabPanelWrap: {
    gap: 10,
  },
  songDetailTabPanelCard: {
    width: "100%",
  },
  songDetailMetaTabStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flexWrap: "wrap",
  },
  songDetailMetaTab: {
    minHeight: 28,
    borderRadius: radii.xl,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#F4F1ED",
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailMetaTabActive: {
    backgroundColor: "#1C1C19",
  },
  songDetailMetaTabText: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailMetaTabTextActive: {
    color: "#FDFBF7",
  },
  songDetailMetaPanel: {
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  songDetailMetaPanelBody: {
    gap: 6,
  },
  songDetailMetaCompactStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMetaStageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMetaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMetaLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMetaFieldLabel: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailMetaFieldHint: {
    fontSize: 11,
    color: "#B8A8A3",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailMetaValue: {
    fontSize: 16,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailMetaValueCompact: {
    fontSize: 15,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
    fontVariant: ["tabular-nums"],
  },
  songDetailMetaSliderWrap: {
    gap: 2,
  },
  songDetailMetaPreview: {
    fontSize: 11.5,
    lineHeight: 16,
    color: "#524440",
  },
  songDetailMetaPreviewMuted: {
    color: "#84736f",
  },
  songDetailMetaActionRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
  },
  songDetailMetaActionChip: {
    minHeight: 26,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "rgba(215,194,189,0.5)",
    backgroundColor: "#F4F1ED",
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailMetaActionChipText: {
    fontSize: 10,
    color: "#524440",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailSummaryCard: {
    gap: 8,
    paddingVertical: 12,
  },
  songDetailSummaryCardCompact: {
    gap: 6,
    paddingVertical: 10,
  },
  songDetailSummaryStrip: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  songDetailSummaryProgressCell: {
    flex: 0.9,
    minWidth: 0,
  },
  songDetailSummaryActionsStack: {
    flex: 1.1,
    minWidth: 0,
    gap: 8,
  },
  songDetailSummaryProgressCard: {
    minHeight: 84,
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
  },
  songDetailSummaryActionCard: {
    minHeight: 0,
    paddingVertical: 10,
    gap: 4,
  },
  songDetailSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  songDetailSummaryTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailStatusSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  songDetailStatusPercent: {
    fontSize: 16,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailStatusPercentCompact: {
    fontSize: 18,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
    lineHeight: 22,
  },
  songDetailStatusBadgeLarge: {
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  songDetailEditorCard: {
    gap: 10,
    paddingVertical: 12,
  },
  songDetailNotesEditorCard: {
    flex: 1,
  },
  songDetailWritingRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  songDetailWritingCell: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  songDetailWritingRowStacked: {
    flexDirection: "column",
  },
  songDetailMiniCard: {
    minWidth: 0,
    paddingVertical: 10,
    gap: 6,
    marginBottom: 0,
    minHeight: 88,
  },
  songDetailMiniCardStandalone: {
    width: "100%",
    minHeight: 0,
  },
  songDetailMiniCardRow: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  songDetailMiniCardStacked: {
    flex: 0,
    width: "100%",
  },
  songDetailMiniCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMiniCardTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  songDetailMiniCardTitle: {
    fontSize: 13,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailMiniCardMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailMiniCardActionWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMiniCardMetaText: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailMiniCardBody: {
    fontSize: 11.5,
    lineHeight: 16,
    color: "#84736f",
  },
  songDetailMiniCardActionText: {
    fontSize: 10,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSummaryLinkCard: {
    minHeight: 60,
    paddingVertical: 10,
    gap: 4,
    justifyContent: "center",
  },
  songDetailSummaryLinkHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailSummaryLinkLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  songDetailSummaryLinkTitle: {
    fontSize: 13,
    color: "#1C1C19",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailSummaryLinkMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  songDetailSummaryLinkMetaText: {
    fontSize: 10,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSummaryLinkBody: {
    fontSize: 11.5,
    lineHeight: 15,
    color: "#84736f",
  },
  songDetailMiniCardButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  songDetailMiniCardButton: {
    minHeight: 30,
    paddingHorizontal: 12,
    borderRadius: radii.round,
  },
  songDetailMiniCardButtonText: {
    fontSize: 12,
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailLyricsCard: {
    borderColor: "rgba(215,194,189,0.3)",
    backgroundColor: "#FDFBF7",
    minHeight: 0,
  },
  songDetailSectionEyebrow: {
    fontSize: 11,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 4,
    marginBottom: 6,
  },
  songDetailSectionHeaderCopy: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  songDetailSectionTitle: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    color: "#a89994",
    textTransform: "uppercase" as "uppercase",
    letterSpacing: 0.8,
  },
  songDetailSectionMeta: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10,
    color: "#a89994",
    fontVariant: ["tabular-nums"],
  },
  songDetailClipListHeader: {
    gap: 10,
  },
  songDetailClipSummarySection: {
    marginBottom: 4,
  },
  songDetailClipSection: {
    gap: 8,
  },
  songDetailStickyIdeasHeader: {
    // Pinned toolbar: opaque page tone so content scrolls cleanly beneath it,
    // separated by a single 0.5pt technical line rather than a filled band + shadow.
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E8E4DF",
    overflow: "visible" as const,
    zIndex: 120,
  },
  songDetailPrimaryDivider: {
    height: 1,
    backgroundColor: "#E8E4DF",
    marginTop: 12,
    marginBottom: 2,
  },
  songDetailListWithStrip: {
    flex: 1,
  },
  songDetailPrimaryStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    paddingLeft: 0,
    paddingRight: 4,
    marginBottom: 6,
  },
  songDetailPrimaryStripAccent: {
    width: 3,
    alignSelf: "stretch",
    borderRadius: 2,
    backgroundColor: "#B87D6B",
  },
  songDetailPrimaryStripPlay: {
    width: 30,
    height: 30,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primaryDeep,
  },
  songDetailPrimaryStripCopy: {
    flex: 1,
    minWidth: 0,
  },
  songDetailPrimaryStripLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "#a89994",
    marginBottom: 1,
  },
  songDetailPrimaryStripTitle: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    color: "#1b1c1a",
  },
  songDetailPrimaryStripLocate: {
    width: 34,
    height: 34,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailClipPrimaryLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "#a89994",
  },
  songDetailRecordBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: radii.round,
  },
  songDetailClipRowWrap: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  // Chip style for the collapse-all button when the header is fully collapsed —
  // matches the sort / filter utility chips in the toolbar so it reads as a
  // clear, tappable control rather than a whispered text action.
  songDetailCollapseAllChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 34,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "rgba(215,194,189,0.5)",
    backgroundColor: "#FDFBF7",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  songDetailClipList: {
    flex: 1,
  },
  songDetailClipListContent: {
    paddingTop: 0,
    paddingBottom: 0,
    gap: 7,
  },
  songDetailParentPickCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
    paddingRight: 12,
  },
  songDetailParentPickHelper: {
    fontSize: 12,
    lineHeight: 16,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  songDetailParentPickMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_500Medium",
  },
  songDetailParentPickInlineHint: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7C2BD",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  songDetailParentPickInlineTitle: {
    fontSize: 12,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  songDetailParentPickInlineText: {
    fontSize: 11,
    lineHeight: 15,
    color: "#84736f",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },

  // -- Song Notes Tab --
  songNotesTabEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
    gap: 8,
  },
  songNotesTabEmptyTitle: {
    fontSize: 15,
    fontFamily: "PlusJakartaSans_600SemiBold",
    color: "#84736f",
  },
  songNotesTabEmptySubtitle: {
    fontSize: 13,
    fontFamily: "PlusJakartaSans_400Regular",
    color: "#B8A8A3",
  },
  songNotesTabBody: {
    fontSize: 15,
    lineHeight: 23,
    fontFamily: "PlusJakartaSans_400Regular",
    color: "#524440",
  },
  songNotesTabEditorInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "rgba(215,194,189,0.5)",
    backgroundColor: "#FDFBF7",
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 280,
    textAlignVertical: "top",
    fontSize: 15,
    lineHeight: 23,
    fontFamily: "PlusJakartaSans_400Regular",
    color: "#1C1C19",
    marginBottom: 6,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
