import { StyleSheet } from "react-native";
import { colors, radii, shadows } from "../../design/tokens";

export const playerScreenStyles = StyleSheet.create({
  screen: {
    backgroundColor: colors.page,
  },
  headerBlock: {
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 4,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  overflowButton: {
    width: 40,
    height: 40,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  overflowButtonPressed: {
    opacity: 0.7,
  },
  // "Tools" toggle — replaces the Player|Practice segmented control. Quiet outlined
  // pill that fills terracotta when practice tools are open.
  toolsPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    height: 34,
    paddingHorizontal: 13,
    borderRadius: radii.round,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    backgroundColor: colors.surface,
  },
  toolsPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  toolsPillText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  toolsPillTextActive: {
    color: colors.onPrimary,
  },
  titleBlock: {
    gap: 6,
  },
  title: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 23,
    lineHeight: 28,
    color: colors.textPrimary,
  },
  // Clip title sits inline in the nav row (between back and the right controls).
  navTitle: {
    flex: 1,
    marginHorizontal: 10,
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 17,
    lineHeight: 22,
    color: colors.textPrimary,
  },
  // Row under the reel that holds the Tools toggle (and leaves room for reel-side controls).
  reelToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingTop: 10,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  metaText: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  metaDot: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  metaSpacer: {
    flexGrow: 1,
  },
  timingText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    lineHeight: 16,
    color: colors.textStrong,
    fontVariant: ["tabular-nums"],
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 10,
  },
  footerStack: {
    gap: 8,
  },
  speedPopover: {
    marginHorizontal: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e3e6eb",
    backgroundColor: "rgba(246,247,249,0.98)",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  speedPopoverSlider: {
    width: "100%",
    height: 30,
  },
  speedPopoverTicks: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    marginTop: 2,
  },
  waveformSection: {
    gap: 6,
    marginHorizontal: -14,
  },
  waveformShell: {
    position: "relative",
  },
  mixUpdatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251,249,245,0.78)",
  },
  mixUpdatingBadge: {
    maxWidth: 280,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    backgroundColor: "#fffdf9",
    alignItems: "center",
    gap: 4,
  },
  mixUpdatingLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: "#824f3f",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.45,
  },
  mixUpdatingMeta: {
    fontSize: 12,
    lineHeight: 16,
    color: "#6a5751",
    textAlign: "center",
  },
  supportStack: {
    gap: 8,
    flexShrink: 1,
  },
  practiceContent: {
    gap: 8,
    flexShrink: 1,
    marginHorizontal: -6,
  },
  notesText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#1f2937",
  },
  layerList: {
    gap: 8,
  },
  layerCard: {
    backgroundColor: "#fffdf9",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  layerCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  layerPlayButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efeeea",
  },
  layerPlayButtonIcon: {
    marginLeft: 2,
  },
  layerCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  layerEnabledDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#b8a69f",
    backgroundColor: "transparent",
    marginTop: 2,
  },
  layerEnabledDotActive: {
    backgroundColor: "#824f3f",
    borderColor: "#824f3f",
  },
  layerCardTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  layerCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    lineHeight: 19,
    color: "#1b1c1a",
    fontWeight: "700",
  },
  layerCardDuration: {
    fontSize: 12,
    lineHeight: 16,
    color: "#6a5751",
    fontVariant: ["tabular-nums"] as never,
  },
  layerCardMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6a5751",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerWaveWrap: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 8,
  },
  layerWavePlayhead: {
    position: "absolute",
    top: 2,
    bottom: 2,
    width: 2,
    marginLeft: -1,
    backgroundColor: "#824f3f",
    opacity: 0.8,
  },
  layerCardControls: {
    gap: 8,
  },
  layerToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  layerToolbarButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "#ece7e1",
  },
  layerToolbarButtonText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#824f3f",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerRootSection: {
    gap: 8,
    paddingVertical: 4,
  },
  layerRootHeader: {
    gap: 2,
  },
  layerRootTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: "#3d302b",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerRootMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6a5751",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  layerRow: {
    paddingVertical: 2,
    gap: 6,
  },
  layerRowCopy: {
    gap: 2,
  },
  layerRowTitle: {
    fontSize: 14,
    lineHeight: 19,
    color: "#1f2937",
    fontWeight: "600",
  },
  layerRowMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  layerControlButton: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#efeeea",
  },
  layerControlButtonActive: {
    backgroundColor: "#e3d5cf",
  },
  layerControlButtonDestructive: {
    backgroundColor: "#f3e5e2",
  },
  layerControlButtonDisabled: {
    backgroundColor: "#f3f1ee",
    opacity: 0.55,
  },
  layerControlButtonText: {
    fontSize: 11,
    lineHeight: 14,
    color: "#4b5563",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  layerControlButtonTextActive: {
    color: "#824f3f",
  },
  layerControlButtonTextDestructive: {
    color: "#a04b41",
  },
  layerControlButtonTextDisabled: {
    color: "#8c837e",
  },
  notesPlaceholder: {
    color: "#8a93a1",
  },
  practiceCard: {
    backgroundColor: "#f6f7f9",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e3e6eb",
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  practiceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 44,
  },
  practiceLabel: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    color: "#111827",
    minWidth: 50,
    flexShrink: 0,
  },
  practiceValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  loopActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eceef2",
    flexShrink: 0,
  },
  speedTickText: {
    fontSize: 12,
    color: "#9ca3af",
    fontWeight: "500",
    fontVariant: ["tabular-nums"] as never,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  speedTickTextActive: {
    color: "#3b82f6",
    fontWeight: "700",
  },
  loopRangeText: {
    fontSize: 11,
    lineHeight: 11,
    color: "#6b7280",
    fontVariant: ["tabular-nums"] as never,
    flexShrink: 1,
    textAlign: "center",
  },
  loopRangePill: {
    height: 36,
    minWidth: 132,
    paddingHorizontal: 10,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#eceef2",
    flexShrink: 1,
    flexGrow: 1,
    maxWidth: 170,
    justifyContent: "center",
  },
  loopRangePillPressed: {
    opacity: 0.78,
  },
  notesInlineText: {
    fontSize: 14,
    color: "#9ca3af",
    flex: 1,
    textAlign: "right",
  },
  toggleShell: {
    width: 52,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e5e7eb",
    padding: 3,
    justifyContent: "center",
    flexShrink: 0,
  },
  toggleShellActive: {
    backgroundColor: "#dbeafe",
  },
  toggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    shadowColor: "#64748b",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  toggleKnobActive: {
    transform: [{ translateX: 22 }],
  },
  divider: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  optionGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  optionChip: {
    minWidth: 60,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#eceef2",
  },
  optionChipActive: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8dde6",
    shadowColor: "#94a3b8",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  optionChipDisabled: {
    opacity: 0.45,
  },
  optionChipText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#374151",
    fontWeight: "600",
  },
  optionChipTextActive: {
    color: "#111827",
  },
  optionChipTextDisabled: {
    color: "#94a3b8",
  },
  practicePitchGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    flexWrap: "wrap",
    flex: 1,
  },
  pitchStepButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eceef2",
  },
  pitchStepButtonDisabled: {
    opacity: 0.45,
  },
  pitchValueShell: {
    minWidth: 64,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8dde6",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 4,
  },
  pitchValueText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#111827",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  pitchValueMeta: {
    fontSize: 11,
    lineHeight: 14,
    color: "#6b7280",
    fontWeight: "700",
  },
  pitchSummaryText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#6b7280",
    fontWeight: "600",
    minWidth: 74,
    textAlign: "right",
  },
  // ─── Practice tools (console: tool selector + inspector) ────────────────────
  toolList: {
    gap: 8,
    marginTop: 2,
  },
  categorySegment: {
    flexDirection: "row",
    backgroundColor: colors.surfaceHigh,
    borderRadius: radii.md,
    padding: 3,
    gap: 3,
  },
  categorySegmentItem: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: radii.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  categorySegmentItemActive: {
    backgroundColor: colors.surface,
    ...shadows.control,
  },
  categorySegmentText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  categorySegmentTextActive: {
    color: colors.textPrimary,
  },
  toolSelector: {
    flexDirection: "row",
    gap: 6,
  },
  toolTab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  toolTabActive: {
    backgroundColor: colors.primary,
  },
  toolTabText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    color: colors.textSecondary,
  },
  toolTabTextActive: {
    color: colors.onPrimary,
  },
  inspector: {
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    borderRadius: radii.sm,
    padding: 13,
    gap: 12,
  },
  // ── Playback settings: compact vertical chips + anchored popover ─────────────
  settingsWrap: {
    position: "relative",
    zIndex: 10,
  },
  settingsRow: {
    flexDirection: "row",
    gap: 6,
  },
  settingChip: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    paddingVertical: 10,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  settingChipActive: {
    borderColor: colors.primary,
    backgroundColor: "#FBF4F1",
  },
  settingChipValue: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  settingChipLabel: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textSecondary,
  },
  popoverBackdrop: {
    position: "absolute",
    top: -2000,
    left: -2000,
    right: -2000,
    bottom: -2000,
    zIndex: 15,
  },
  settingPopover: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 20,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    borderRadius: radii.sm,
    padding: 13,
    gap: 12,
    ...shadows.card,
  },
  pinAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 10,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    borderStyle: "dashed",
  },
  pinAddText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.primary,
    fontVariant: ["tabular-nums"],
  },
  pinRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
  },
  pinRowDivider: {
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  pinDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  pinLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 14,
    color: colors.textPrimary,
  },
  pinTime: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  pinEmptyText: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textMuted,
    textAlign: "center",
    paddingVertical: 4,
  },
  toolCard: {
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    borderRadius: radii.sm,
    overflow: "hidden",
  },
  toolHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    minHeight: 52,
    gap: 10,
  },
  toolHeaderPressed: {
    backgroundColor: colors.surfaceContainer,
  },
  toolHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  toolLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    color: colors.textPrimary,
  },
  toolHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  toolValue: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
    flexShrink: 1,
  },
  toolBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 12,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  toolBodyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  toolBodyLabel: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textSecondary,
  },
  switchShell: {
    width: 46,
    height: 28,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceHigh,
    padding: 3,
    justifyContent: "center",
  },
  switchShellActive: {
    backgroundColor: colors.primary,
  },
  switchKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.surface,
    ...shadows.control,
  },
  switchKnobActive: {
    transform: [{ translateX: 18 }],
  },
  loopControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toolLoopPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    height: 34,
    paddingHorizontal: 12,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    flexGrow: 1,
  },
  toolLoopText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    color: colors.textStrong,
    fontVariant: ["tabular-nums"],
  },
  loopIconButton: {
    width: 36,
    height: 36,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceContainer,
  },
  toolChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  toolChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    minWidth: 52,
    alignItems: "center",
  },
  toolChipActive: {
    backgroundColor: colors.primary,
  },
  toolChipDisabled: {
    opacity: 0.45,
  },
  toolChipText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  toolChipTextActive: {
    color: colors.onPrimary,
  },
  toolSlider: {
    width: "100%",
    height: 34,
  },
  pitchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepButton: {
    width: 38,
    height: 38,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceContainer,
  },
  stepButtonDisabled: {
    opacity: 0.45,
  },
  toolPitchShell: {
    minWidth: 60,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceContainer,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 3,
  },
  toolPitchValue: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  toolPitchUnit: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    color: colors.textSecondary,
  },
  pitchSpacer: {
    flex: 1,
  },
  pinSheetContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 16,
  },
  pinSheetTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
  },
  pinSheetTime: {
    fontSize: 13,
    color: "#ca8a04",
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
    marginTop: -8,
  },
  pinSheetInput: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#f3f4f6",
    fontSize: 15,
    color: "#111827",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  pinSheetFooter: {
    flexDirection: "row",
    gap: 10,
  },
  pinSheetButton: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: "#ca8a04",
  },
  pinSheetButtonSecondary: {
    backgroundColor: "#f3f4f6",
  },
  pinSheetButtonDanger: {
    backgroundColor: "#dc2626",
    flexDirection: "row",
    justifyContent: "center",
  },
  pinSheetButtonDisabled: {
    backgroundColor: "#e5e7eb",
  },
  pinSheetButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#ffffff",
  },
  pinSheetButtonSecondaryText: {
    color: "#374151",
  },
  pinSheetButtonTextDisabled: {
    color: "#9ca3af",
  },
});
