import { StyleSheet } from "react-native";
import { colors, radii, shadows } from "../../design/tokens";

export const playerScreenStyles = StyleSheet.create({
  screen: {
    backgroundColor: colors.page,
  },
  headerBlock: {
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 4,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  overflowButton: {
    width: 40,
    height: 40,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  overflowButtonPressed: {
    opacity: 0.7,
  },
  // "Tools" toggle — replaces the Player|Practice segmented control. Quiet outlined
  // pill that fills terracotta when practice tools are open.
  toolsPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    height: 34,
    paddingHorizontal: 13,
    borderRadius: radii.round,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    backgroundColor: colors.surface,
  },
  toolsPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  toolsPillText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  toolsPillTextActive: {
    color: colors.onPrimary,
  },
  titleBlock: {
    gap: 6,
  },
  title: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 23,
    lineHeight: 28,
    color: colors.textPrimary,
  },
  // Clip title sits inline in the nav row (between back and the right controls).
  navTitle: {
    flex: 1,
    marginHorizontal: 10,
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 17,
    lineHeight: 22,
    color: colors.textPrimary,
  },
  // Row under the reel that holds the Tools toggle (and leaves room for reel-side controls).
  reelToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 10,
  },
  reelToolbarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stickyReel: {
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 6,
    gap: 6,
    backgroundColor: colors.page,
  },
  reelExpandButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
  },
  reelExpandText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    color: colors.textSecondary,
  },
  reelTimingRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: 2,
  },
  reelTimingText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  reelCornerButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: radii.round,
    backgroundColor: "rgba(244, 241, 237, 0.86)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  metaText: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  metaDot: {
    fontSize: 12,
    lineHeight: 16,
    color: colors.textMuted,
  },
  metaSpacer: {
    flexGrow: 1,
  },
  timingText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    lineHeight: 16,
    color: colors.textStrong,
    fontVariant: ["tabular-nums"],
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 10,
  },
  // Play-along fills the body so the lyrics get every spare pixel.
  playAlongContent: {
    flex: 1,
  },
  footerStack: {
    gap: 8,
  },
  speedPopover: {
    marginHorizontal: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: "#e3e6eb",
    backgroundColor: "rgba(246,247,249,0.98)",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  speedPopoverSlider: {
    width: "100%",
    height: 30,
  },
  speedPopoverTicks: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    marginTop: 2,
  },
  waveformSection: {
    gap: 6,
    marginHorizontal: -14,
  },
  waveformShell: {
    position: "relative",
  },
  supportStack: {
    gap: 8,
    flexShrink: 1,
  },
  practiceContent: {
    gap: 8,
    flexShrink: 1,
    marginHorizontal: -6,
  },
  notesText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#1f2937",
  },
  layerList: {
    gap: 8,
  },
  layerCard: {
    backgroundColor: "#fffdf9",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  layerCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  layerPlayButton: {
    width: 34,
    height: 34,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efeeea",
  },
  layerPlayButtonIcon: {
    marginLeft: 2,
  },
  layerCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  layerEnabledDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#b8a69f",
    backgroundColor: "transparent",
    marginTop: 2,
  },
  layerEnabledDotActive: {
    backgroundColor: "#824f3f",
    borderColor: "#824f3f",
  },
  layerCardTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  layerCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    lineHeight: 19,
    color: "#1b1c1a",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  layerCardDuration: {
    fontSize: 12,
    lineHeight: 16,
    color: "#6a5751",
    fontVariant: ["tabular-nums"] as never,
  },
  layerCardMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6a5751",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerRootSection: {
    gap: 8,
    paddingVertical: 4,
  },
  layerRootHeader: {
    gap: 2,
  },
  layerRootTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: "#3d302b",
    fontFamily: "PlusJakartaSans_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerRootMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6a5751",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  layerRow: {
    paddingVertical: 2,
    gap: 6,
  },
  layerRowCopy: {
    gap: 2,
  },
  layerRowTitle: {
    fontSize: 14,
    lineHeight: 19,
    color: "#1f2937",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  layerRowMeta: {
    fontSize: 11,
    lineHeight: 15,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  layerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  layerControlButton: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: radii.lg,
    backgroundColor: "#efeeea",
  },
  layerControlButtonActive: {
    backgroundColor: "#e3d5cf",
  },
  layerControlButtonDestructive: {
    backgroundColor: "#f3e5e2",
  },
  layerControlButtonDisabled: {
    backgroundColor: "#f3f1ee",
    opacity: 0.55,
  },
  layerControlButtonText: {
    fontSize: 11,
    lineHeight: 14,
    color: "#4b5563",
    fontFamily: "PlusJakartaSans_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  layerControlButtonTextActive: {
    color: "#824f3f",
  },
  layerControlButtonTextDestructive: {
    color: "#a04b41",
  },
  layerControlButtonTextDisabled: {
    color: "#8c837e",
  },
  notesPlaceholder: {
    color: "#8a93a1",
  },
  practiceCard: {
    backgroundColor: "#f6f7f9",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e3e6eb",
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  practiceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 44,
  },
  practiceLabel: {
    fontSize: 15,
    lineHeight: 18,
    fontFamily: "PlusJakartaSans_600SemiBold",
    color: "#111827",
    minWidth: 50,
    flexShrink: 0,
  },
  practiceValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  loopActionButton: {
    width: 36,
    height: 36,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eceef2",
    flexShrink: 0,
  },
  speedTickText: {
    fontSize: 12,
    color: "#9ca3af",
    fontFamily: "PlusJakartaSans_500Medium",
    fontVariant: ["tabular-nums"] as never,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  speedTickTextActive: {
    color: "#3b82f6",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  loopRangeText: {
    fontSize: 11,
    lineHeight: 11,
    color: "#6b7280",
    fontVariant: ["tabular-nums"] as never,
    flexShrink: 1,
    textAlign: "center",
  },
  loopRangePill: {
    height: 36,
    minWidth: 132,
    paddingHorizontal: 10,
    borderRadius: radii.round,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#eceef2",
    flexShrink: 1,
    flexGrow: 1,
    maxWidth: 170,
    justifyContent: "center",
  },
  loopRangePillPressed: {
    opacity: 0.78,
  },
  notesInlineText: {
    fontSize: 14,
    color: "#9ca3af",
    flex: 1,
    textAlign: "right",
  },
  toggleShell: {
    width: 52,
    height: 36,
    borderRadius: radii.round,
    backgroundColor: "#e5e7eb",
    padding: 3,
    justifyContent: "center",
    flexShrink: 0,
  },
  toggleShellActive: {
    backgroundColor: "#dbeafe",
  },
  toggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    shadowColor: "#64748b",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  toggleKnobActive: {
    transform: [{ translateX: 22 }],
  },
  divider: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  optionGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  optionChip: {
    minWidth: 60,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#eceef2",
  },
  optionChipActive: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8dde6",
    shadowColor: "#94a3b8",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  optionChipDisabled: {
    opacity: 0.45,
  },
  optionChipText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#374151",
    fontFamily: "PlusJakartaSans_600SemiBold",
  },
  optionChipTextActive: {
    color: "#111827",
  },
  optionChipTextDisabled: {
    color: "#94a3b8",
  },
  practicePitchGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    flexWrap: "wrap",
    flex: 1,
  },
  pitchStepButton: {
    width: 34,
    height: 34,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eceef2",
  },
  pitchStepButtonDisabled: {
    opacity: 0.45,
  },
  pitchValueShell: {
    minWidth: 64,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8dde6",
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 4,
  },
  pitchValueText: {
    fontSize: 14,
    lineHeight: 16,
    color: "#111827",
    fontFamily: "PlusJakartaSans_700Bold",
    fontVariant: ["tabular-nums"],
  },
  pitchValueMeta: {
    fontSize: 11,
    lineHeight: 14,
    color: "#6b7280",
    fontFamily: "PlusJakartaSans_700Bold",
  },
  pitchSummaryText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#6b7280",
    fontFamily: "PlusJakartaSans_600SemiBold",
    minWidth: 74,
    textAlign: "right",
  },
  // ─── Practice tools (console: tool selector + inspector) ────────────────────
  toolList: {
    gap: 8,
    marginTop: 2,
  },
  categorySegment: {
    flexDirection: "row",
    backgroundColor: colors.surfaceHigh,
    borderRadius: radii.md,
    padding: 3,
    gap: 3,
  },
  categorySegmentItem: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: radii.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  categorySegmentItemActive: {
    backgroundColor: colors.surface,
    ...shadows.control,
  },
  categorySegmentText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  categorySegmentTextActive: {
    color: colors.textPrimary,
  },
  toolSelector: {
    flexDirection: "row",
    gap: 6,
  },
  toolTab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  toolTabActive: {
    backgroundColor: colors.primary,
  },
  toolTabText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    color: colors.textSecondary,
  },
  toolTabTextActive: {
    color: colors.onPrimary,
  },
  inspector: {
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    borderRadius: radii.sm,
    padding: 13,
    gap: 12,
  },
  // ── Playback settings: compact vertical chips + anchored popover ─────────────
  settingsWrap: {
    position: "relative",
    zIndex: 10,
  },
  settingsRow: {
    flexDirection: "row",
    gap: 6,
  },
  settingChip: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    paddingVertical: 10,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    backgroundColor: colors.surface,
  },
  settingChipActive: {
    borderColor: colors.primary,
    backgroundColor: "#FBF4F1",
  },
  settingChipValue: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  settingChipLabel: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textSecondary,
  },
  popoverBackdrop: {
    position: "absolute",
    top: -2000,
    left: -2000,
    right: -2000,
    bottom: -2000,
    zIndex: 15,
  },
  settingPopover: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 20,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    borderRadius: radii.sm,
    padding: 13,
    gap: 12,
    ...shadows.card,
  },
  pinAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 10,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.borderMuted,
    borderStyle: "dashed",
  },
  pinAddText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.primary,
    fontVariant: ["tabular-nums"],
  },
  pinRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
  },
  pinRowDivider: {
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  pinDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  pinLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 14,
    color: colors.textPrimary,
  },
  pinTime: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  pinEmptyText: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textMuted,
    textAlign: "center",
    paddingVertical: 4,
  },
  pinRowColumn: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 0,
  },
  pinRowMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pinRowSeek: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pinTray: {
    marginTop: 8,
    paddingTop: 10,
    paddingBottom: 4,
    gap: 10,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  pinTrayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pinSlider: {
    flex: 1,
    height: 32,
  },
  pinTrayTime: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
    minWidth: 44,
    textAlign: "right",
  },
  pinNoteInput: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 9,
    minHeight: 40,
    textAlignVertical: "top",
  },
  pinNotePreview: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12.5,
    color: colors.textMuted,
    paddingLeft: 18,
    paddingTop: 2,
    paddingBottom: 2,
  },
  pinStepButton: {
    width: 32,
    height: 32,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
  },
  pinTrayTimeCenter: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
    textAlign: "center",
    marginTop: 2,
  },
  pinNoteSaveRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  pinNoteSaveButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: radii.sm,
    backgroundColor: "#FBF4F1",
    borderWidth: 0.5,
    borderColor: colors.primary,
  },
  pinNoteSaveButtonClean: {
    backgroundColor: colors.surfaceContainer,
    borderColor: "transparent",
  },
  pinNoteSaveText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12.5,
    color: colors.primary,
  },
  pinNoteSaveTextClean: {
    color: colors.textMuted,
  },
  sectionQuickAddLabel: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textMuted,
    marginBottom: 8,
    letterSpacing: 0.3,
    fontVariant: ["tabular-nums"],
  },
  sectionChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 4,
  },
  sectionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    borderWidth: 0.5,
    borderColor: "transparent",
  },
  sectionChipActive: {
    backgroundColor: "#FBF4F1",
    borderColor: colors.primary,
  },
  sectionChipText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12.5,
    color: colors.textSecondary,
  },
  sectionSwatch: {
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: colors.borderMuted,
  },
  sectionDurationPill: {
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.xs,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  sectionDurationText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  sectionEditTray: {
    marginTop: 8,
    paddingTop: 10,
    paddingBottom: 4,
    gap: 10,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  sectionEditInput: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.sm,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  pinDetailNoteInput: {
    minHeight: 64,
    textAlignVertical: "top",
    paddingTop: 9,
  },
  sectionDeleteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
  },
  sectionDeleteText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.danger,
  },
  sectionEdgeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  sectionEdgeLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    color: colors.textMuted,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  sectionEdgeTime: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  sectionChangeTypeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceContainer,
  },
  sectionChangeTypeText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  loopSectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.borderSubtle,
  },
  loopSectionLabel: {
    flex: 1,
    minWidth: 0,
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 14,
    color: colors.textPrimary,
  },
  loopSectionTime: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  sectionModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(27, 28, 26, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  sectionModalCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 18,
    gap: 14,
  },
  sectionModalTitle: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 15,
    color: colors.textPrimary,
  },
  sectionModalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sectionModalNewButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: radii.sm,
    borderWidth: 0.5,
    borderColor: colors.primary,
    alignSelf: "flex-start",
  },
  sectionModalNewText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12.5,
    color: colors.primary,
  },
  sectionColorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  sectionColorSwatch: {
    width: 28,
    height: 28,
    borderRadius: radii.round,
    borderWidth: 2,
    borderColor: "transparent",
  },
  sectionColorSwatchActive: {
    borderColor: colors.textPrimary,
  },
  sectionModalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 2,
  },
  sectionModalCancel: {
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: radii.sm,
  },
  sectionModalCancelText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
  },
  sectionModalConfirm: {
    paddingVertical: 9,
    paddingHorizontal: 18,
    borderRadius: radii.sm,
    backgroundColor: colors.primary,
  },
  sectionModalConfirmDisabled: {
    opacity: 0.4,
  },
  sectionModalConfirmText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.onPrimary,
  },
  toolValueInline: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12.5,
    color: colors.textMuted,
    marginLeft: 8,
    fontVariant: ["tabular-nums"],
  },
  sectionAddCircle: {
    width: 26,
    height: 26,
    borderRadius: radii.round,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionRowMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sectionRowLabel: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionRowLabelText: {
    flex: 1,
    minWidth: 0,
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 12.5,
    color: colors.textPrimary,
  },
  sectionTimeChip: {
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: radii.xs,
    backgroundColor: colors.surfaceContainer,
  },
  sectionTimeChipActive: {
    backgroundColor: "transparent",
  },
  sectionTimeChipText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 10.5,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  sectionAdjusterHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionEdgeLiveTime: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  sectionPinCircle: {
    width: 30,
    height: 30,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionPinCircleDisabled: {
    opacity: 0.5,
  },
  ibeam: {
    height: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  ibeamCap: {
    width: 8,
    height: 2,
    borderRadius: 1,
  },
  ibeamStem: {
    width: 2,
    height: 11,
  },
  sectionPickerFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionModalDelete: {
    width: 42,
    height: 42,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: "rgba(168, 68, 58, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTimeChipTextActive: {
    color: colors.primary,
  },
  sectionTimeDash: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textMuted,
    marginHorizontal: -2,
  },
  sectionRowIcon: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionAdjuster: {
    marginTop: 8,
    paddingTop: 10,
    gap: 8,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  sectionPinButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceContainer,
  },
  sectionPinButtonDisabled: {
    opacity: 0.45,
  },
  sectionPinText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 12.5,
    color: colors.primary,
  },
  sectionPinTextDisabled: {
    color: colors.textMuted,
  },
  sectionPinDragHint: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textMuted,
    fontVariant: ["tabular-nums"],
  },
  sectionDetailPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  sectionDetailSwatch: {
    width: 22,
    height: 22,
    borderRadius: radii.sm,
  },
  sectionDetailPreviewText: {
    flex: 1,
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 15,
    color: colors.textPrimary,
  },
  recordLayerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 6,
    paddingVertical: 12,
    borderRadius: radii.md,
    backgroundColor: "#FBF4F1",
    borderWidth: 0.5,
    borderColor: colors.primary,
  },
  recordLayerButtonPressed: {
    backgroundColor: "#F6E9E3",
  },
  recordLayerDot: {
    width: 9,
    height: 9,
    borderRadius: radii.round,
    backgroundColor: "#C0473B",
  },
  recordLayerText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13.5,
    color: colors.primary,
  },
  analysisRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
  },
  analysisValue: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  analysisSep: {
    width: 3,
    height: 3,
    borderRadius: radii.round,
    backgroundColor: colors.textMuted,
  },
  analysisHint: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 11,
    color: colors.textMuted,
  },
  analysisDetectButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  analysisDetectText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.primary,
  },
  analysisErrorText: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 11.5,
    color: colors.textMuted,
    paddingHorizontal: 4,
    marginTop: 6,
  },
  toolCard: {
    backgroundColor: colors.surface,
    borderWidth: 0.5,
    borderColor: colors.borderSubtle,
    borderRadius: radii.sm,
    overflow: "hidden",
  },
  toolHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    minHeight: 52,
    gap: 10,
  },
  toolHeaderPressed: {
    backgroundColor: colors.surfaceContainer,
  },
  toolHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  toolLabel: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 14,
    color: colors.textPrimary,
  },
  toolHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  toolValue: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
    flexShrink: 1,
  },
  toolBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 12,
    borderTopWidth: 0.5,
    borderTopColor: colors.borderSubtle,
  },
  toolBodyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  toolBodyLabel: {
    fontFamily: "PlusJakartaSans_400Regular",
    fontSize: 13,
    color: colors.textSecondary,
  },
  switchShell: {
    width: 46,
    height: 28,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceHigh,
    padding: 3,
    justifyContent: "center",
  },
  switchShellActive: {
    backgroundColor: colors.primary,
  },
  switchKnob: {
    width: 22,
    height: 22,
    borderRadius: radii.round,
    backgroundColor: colors.surface,
    ...shadows.control,
  },
  switchKnobActive: {
    transform: [{ translateX: 18 }],
  },
  loopControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toolLoopPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    height: 34,
    paddingHorizontal: 12,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    flexGrow: 1,
  },
  toolLoopText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    color: colors.textStrong,
    fontVariant: ["tabular-nums"],
  },
  loopIconButton: {
    width: 36,
    height: 36,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceContainer,
  },
  toolChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  toolChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.round,
    backgroundColor: colors.surfaceContainer,
    minWidth: 52,
    alignItems: "center",
  },
  toolChipActive: {
    backgroundColor: colors.primary,
  },
  toolChipDisabled: {
    opacity: 0.45,
  },
  toolChipText: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 13,
    color: colors.textSecondary,
    fontVariant: ["tabular-nums"],
  },
  toolChipTextActive: {
    color: colors.onPrimary,
  },
  toolSlider: {
    width: "100%",
    height: 34,
  },
  pitchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepButton: {
    width: 38,
    height: 38,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceContainer,
  },
  stepButtonDisabled: {
    opacity: 0.45,
  },
  toolPitchShell: {
    minWidth: 60,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceContainer,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 3,
  },
  toolPitchValue: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 15,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  toolPitchUnit: {
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontSize: 11,
    color: colors.textSecondary,
  },
  pitchSpacer: {
    flex: 1,
  },
  pinSheetContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 16,
  },
  pinSheetTitle: {
    fontSize: 17,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#111827",
  },
  pinSheetTime: {
    fontSize: 13,
    color: "#ca8a04",
    fontFamily: "PlusJakartaSans_600SemiBold",
    fontVariant: ["tabular-nums"],
    marginTop: -8,
  },
  pinSheetInput: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radii.lg,
    backgroundColor: "#f3f4f6",
    fontSize: 15,
    color: "#111827",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  pinSheetFooter: {
    flexDirection: "row",
    gap: 10,
  },
  pinSheetButton: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: radii.lg,
    alignItems: "center",
    backgroundColor: "#ca8a04",
  },
  pinSheetButtonSecondary: {
    backgroundColor: "#f3f4f6",
  },
  pinSheetButtonDanger: {
    backgroundColor: "#dc2626",
    flexDirection: "row",
    justifyContent: "center",
  },
  pinSheetButtonDisabled: {
    backgroundColor: "#e5e7eb",
  },
  pinSheetButtonText: {
    fontSize: 15,
    fontFamily: "PlusJakartaSans_600SemiBold",
    color: "#ffffff",
  },
  pinSheetButtonSecondaryText: {
    color: "#374151",
  },
  pinSheetButtonTextDisabled: {
    color: "#9ca3af",
  },
});
