import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f4f5f7",
    paddingHorizontal: 16,
  },
  flexFill: {
    flex: 1,
  },
  screenIdeas: {
    backgroundColor: "#f4f5f7",
    paddingHorizontal: 14,
  },
  ideasHeaderBlock: {
    marginTop: 2,
    marginBottom: 10,
    gap: 4,
  },
  ideasHeaderTitle: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "700",
    color: "#0f172a",
  },
  ideasHeaderSubtitle: {
    fontSize: 13,
    color: "#64748b",
  },
  ideasPageHeader: {
    marginBottom: 8,
  },
  ideasPageHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ideasPageHeaderTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  ideasPageHeaderBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 4,
    minWidth: 0,
  },
  ideasPageHeaderBreadcrumbChunk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    flexShrink: 1,
  },
  ideasPageHeaderBreadcrumbItem: {
    minHeight: 18,
    justifyContent: "center",
  },
  ideasPageHeaderBreadcrumbContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  ideasPageHeaderBreadcrumbText: {
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "600",
  },
  songDetailHeader: {
    marginTop: 2,
    marginBottom: 6,
  },
  songDetailNavRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  songDetailNavLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  songDetailInlineBreadcrumbs: {
    flex: 1,
    minWidth: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: 0,
    flexWrap: "nowrap",
  },
  songDetailNavCompactTitle: {
    fontSize: 16,
    lineHeight: 20,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailCompactTitleWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailBreadcrumbWrap: {
    flex: 1,
    minWidth: 0,
  },
  songDetailBreadcrumbScrollContent: {
    alignItems: "center",
    gap: 4,
    paddingRight: 8,
  },
  songDetailBreadcrumbChunk: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailBreadcrumbTextHitbox: {
    minHeight: 18,
    justifyContent: "center",
  },
  songDetailBreadcrumbSeparator: {
    fontSize: 12,
    lineHeight: 14,
    color: "#94a3b8",
    fontWeight: "600",
  },
  songDetailBreadcrumbText: {
    fontSize: 12,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "600",
  },
  songDetailBreadcrumbTextActive: {
    color: "#334155",
  },
  songDetailBreadcrumbEllipsis: {
    fontSize: 12,
    lineHeight: 14,
    color: "#94a3b8",
    fontWeight: "600",
  },
  songDetailNavEditActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailNavTextAction: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8dee7",
  },
  songDetailNavTextActionPrimary: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  songDetailNavTextActionText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  songDetailNavTextActionPrimaryText: {
    fontSize: 12,
    color: "#ffffff",
    fontWeight: "700",
  },
  songDetailTitleBlock: {
    marginTop: 0,
    gap: 4,
  },
  songDetailTitleBlockHidden: {
    display: "none",
  },
  songDetailHeaderModeLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailTitleInputWrap: {
    marginHorizontal: 0,
    marginTop: 2,
  },
  songDetailTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 2,
  },
  songDetailTitleLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  songDetailPageTitle: {
    flex: 1,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    color: "#0f172a",
  },
  songDetailPageTitleLarge: {
    flex: 1,
    minWidth: 0,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "700",
    color: "#0f172a",
  },
  songDetailPageTitleWithIcon: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  songDetailTypeLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  songDetailHeaderEditActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailHeaderActionBtn: {
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  songDetailDangerMenuText: {
    flex: 1,
    fontSize: 13,
    color: "#b91c1c",
    fontWeight: "700",
  },
  ideasSearchUtilityRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 10,
    position: "relative",
    zIndex: 35,
  },
  ideasSearchWrap: {
    marginTop: 0,
    marginBottom: 0,
    minHeight: 40,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasSearchWrapInline: {
    flex: 1,
    minWidth: 0,
  },
  ideasSearchInput: {
    flex: 1,
    fontSize: 14,
    color: "#0f172a",
    paddingVertical: Platform.OS === "ios" ? 9 : 8,
  },
  ideasSearchClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  ideasWorkspacePill: {
    maxWidth: 150,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ideasWorkspacePillText: {
    flexShrink: 1,
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  ideasToolbar: {
    marginBottom: 10,
    gap: 10,
    position: "relative",
    zIndex: 30,
  },
  ideasToolbarBackdrop: {
    position: "absolute",
    top: -420,
    bottom: -2400,
    left: -24,
    right: -24,
    zIndex: 20,
  },
  ideasFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasFilterChip: {
    minHeight: 32,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#e9edf2",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasFilterChipActive: {
    backgroundColor: "#111827",
  },
  ideasFilterChipText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  ideasFilterChipTextActive: {
    color: "#ffffff",
  },
  ideasUtilityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  ideasUtilityRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
  },
  ideasUtilityControlGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ideasUtilityLeadIndicator: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasUtilityChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  ideasUtilityChipOpen: {
    borderColor: "#94a3b8",
    backgroundColor: "#f8fafc",
  },
  ideasUtilityChipIconOnly: {
    minWidth: 42,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  ideasUtilityChipFilterOnly: {
    minWidth: 74,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  ideasUtilityChipSortOnly: {
    minWidth: 82,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  ideasUtilityChipDivider: {
    width: 1,
    height: 14,
    backgroundColor: "#dbe2ea",
  },
  ideasUtilityChipDividerActive: {
    backgroundColor: "#94a3b8",
  },
  ideasUtilityChipPrimary: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  ideasUtilityChipClear: {
    borderColor: "#fecaca",
    backgroundColor: "#fff5f5",
  },
  ideasUtilityChipText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  ideasUtilityChipTextDanger: {
    color: "#b91c1c",
  },
  ideasUtilityChipTextPrimary: {
    color: "#ffffff",
  },
  ideasSortChipIconStack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
  },
  ideasUtilityIconChip: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasUtilityIconDanger: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fff5f5",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasUtilityClearIconBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasSortMenu: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    padding: 8,
    gap: 4,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  ideasPopoverMenu: {
    position: "absolute",
    top: 44,
    minWidth: 210,
    maxWidth: 268,
    zIndex: 30,
  },
  ideasSortMenuItem: {
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasMenuItemLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  ideasSortMenuItemActive: {
    backgroundColor: "#eef2f6",
  },
  ideasSortMenuItemText: {
    flex: 1,
    fontSize: 13,
    color: "#334155",
    fontWeight: "600",
  },
  ideasSortMenuItemTextActive: {
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasDropdownSectionToggle: {
    minHeight: 34,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ideasDropdownSectionToggleText: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  ideasDropdownSectionMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  ideasDropdownSectionMetaText: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  ideasDropdownSectionStack: {
    gap: 8,
  },
  ideasStageChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  ideasStageChip: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasStageChipActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  ideasStageChipText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  ideasStageChipTextActive: {
    color: "#ffffff",
  },
  ideasToggleRow: {
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasSwitch: {
    width: 42,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#e2e8f0",
    padding: 2,
    justifyContent: "center",
  },
  ideasSwitchActive: {
    backgroundColor: "#0f172a",
  },
  ideasSwitchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    alignSelf: "flex-start",
  },
  ideasSwitchThumbActive: {
    alignSelf: "flex-end",
  },
  ideasSortDirectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  ideasSortDirectionControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasSortDirectionChip: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
  },
  ideasSortDirectionChipActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  ideasSortDirectionChipText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  ideasSortDirectionChipTextActive: {
    color: "#ffffff",
  },
  ideasDropdownSectionTitle: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    paddingHorizontal: 4,
    marginBottom: 2,
  },
  ideasDropdownDivider: {
    height: 1,
    backgroundColor: "#e2e8f0",
    marginVertical: 4,
  },
  screenProjectDetail: {
    backgroundColor: "#f4f5f7",
  },
  screenClipDetail: {
    backgroundColor: "#f4f5f7",
  },
  hamburgerBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(17,24,39,0.18)",
  },
  drawerPanel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: "84%",
    maxWidth: 340,
    backgroundColor: "#fff",
    borderTopRightRadius: 26,
    borderBottomRightRadius: 26,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    gap: 8,
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 12,
  },
  sideNavItem: {
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sideNavItemActive: {
    backgroundColor: "#f3f4f6",
  },
  sideNavLabel: {
    fontSize: 20,
    color: "#111827",
    fontWeight: "700",
  },
  sideNavItemLabel: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "600",
  },
  sideNavItemMeta: {
    fontSize: 14,
    color: "#6b7280",
    fontWeight: "500",
  },
  sideNavSectionLabel: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    paddingHorizontal: 12,
    marginTop: 2,
    marginBottom: 4,
  },
  sideNavHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 10,
  },
  sideNavWorkspaceBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: "#fff",
    justifyContent: "space-between",
  },
  sideNavWorkspaceCopy: {
    flex: 1,
    gap: 0,
  },
  sideNavCollectionList: {
    gap: 4,
    paddingLeft: 10,
  },
  sideNavCloseBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
  },
  sideNavScrollContent: {
    gap: 8,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  sideNavNestedCollectionRow: {
    marginLeft: 18,
  },
  sideNavCollectionMeta: {
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "700",
  },
  sideNavPlaceholderText: {
    fontSize: 13,
    color: "#94a3b8",
    fontWeight: "500",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  breadcrumbText: {
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "600",
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  contextPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#fff",
  },
  contextPillText: {
    fontSize: 10,
    color: "#4b5563",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  drawerDivider: {
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    marginVertical: 4,
  },
  sideNavToggle: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  shellContent: {
    flex: 1,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  headerLeftCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  backLinkBtn: {
    minHeight: 32,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  backLinkText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#4b5563",
  },
  title: { fontSize: 22, fontWeight: "700", color: "#0f172a" },
  pageTitleCompact: { fontSize: 20, fontWeight: "700", color: "#0f172a" },
  titleInlineWrap: {
    marginHorizontal: 8,
    position: "relative",
    alignSelf: "stretch",
  },
  titleInlineInput: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingLeft: 10,
    paddingRight: 64,
    paddingVertical: 4,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: "700",
    color: "#111827",
    minHeight: 34,
    textAlignVertical: "top",
  },
  titleInlineInputPlaceholder: {
    fontWeight: "500",
  },
  titleInlineBtns: {
    position: "absolute",
    right: 8,
    top: "50%",
    marginTop: -12,
    flexDirection: "row",
    gap: 6,
  },
  titleClearBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  subtitle: { marginTop: 2, marginBottom: 12, fontSize: 13, color: "#64748b" },
  inputRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginBottom: 8,
    flexWrap: "wrap",
  },
  input: {
    flex: 1,
    minWidth: 120,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  notesInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 64,
    textAlignVertical: "top",
    marginBottom: 6,
  },
  songDetailTopStack: {
    gap: 8,
    marginBottom: 6,
  },
  songDetailProgressStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 2,
  },
  songDetailProgressStripLabel: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailProgressStripPercent: {
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailSongTabs: {
    flexDirection: "row",
    marginBottom: 4,
    padding: 4,
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
  },
  songDetailSongTab: {
    flex: 1,
    paddingVertical: 6,
    alignItems: "center",
    borderRadius: 6,
  },
  songDetailSongTabActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  songDetailSongTabText: {
    fontSize: 13,
    color: "#64748b",
    fontWeight: "600",
  },
  songDetailSongTabTextActive: {
    color: "#0f172a",
  },
  songDetailTabScroll: {
    flex: 1,
  },
  songDetailTabScrollContent: {
    gap: 10,
    paddingBottom: 24,
  },
  songDetailTabPanelWrap: {
    gap: 10,
  },
  songDetailTabPanelCard: {
    width: "100%",
  },
  songDetailMetaTabStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flexWrap: "wrap",
  },
  songDetailMetaTab: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#e9edf2",
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailMetaTabActive: {
    backgroundColor: "#111827",
  },
  songDetailMetaTabText: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "700",
  },
  songDetailMetaTabTextActive: {
    color: "#f8fafc",
  },
  songDetailMetaPanel: {
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  songDetailMetaPanelBody: {
    gap: 6,
  },
  songDetailMetaCompactStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMetaStageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMetaValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMetaLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMetaFieldLabel: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailMetaFieldHint: {
    fontSize: 11,
    color: "#94a3b8",
    fontWeight: "600",
  },
  songDetailMetaValue: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailMetaValueCompact: {
    fontSize: 15,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailMetaSliderWrap: {
    gap: 2,
  },
  songDetailMetaPreview: {
    fontSize: 11.5,
    lineHeight: 16,
    color: "#334155",
  },
  songDetailMetaPreviewMuted: {
    color: "#64748b",
  },
  songDetailMetaActionRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
  },
  songDetailMetaActionChip: {
    minHeight: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailMetaActionChipText: {
    fontSize: 10,
    color: "#334155",
    fontWeight: "700",
  },
  songDetailSummaryCard: {
    gap: 8,
    paddingVertical: 12,
  },
  songDetailSummaryCardCompact: {
    gap: 6,
    paddingVertical: 10,
  },
  songDetailSummaryStrip: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  songDetailSummaryProgressCell: {
    flex: 0.9,
    minWidth: 0,
  },
  songDetailSummaryActionsStack: {
    flex: 1.1,
    minWidth: 0,
    gap: 8,
  },
  songDetailSummaryProgressCard: {
    minHeight: 84,
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
  },
  songDetailSummaryActionCard: {
    minHeight: 0,
    paddingVertical: 10,
    gap: 4,
  },
  songDetailSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  songDetailSummaryTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailStatusSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  songDetailStatusPercent: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailStatusPercentCompact: {
    fontSize: 18,
    color: "#0f172a",
    fontWeight: "700",
    lineHeight: 22,
  },
  songDetailStatusBadgeLarge: {
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  songDetailEditorCard: {
    gap: 10,
    paddingVertical: 12,
  },
  songDetailNotesEditorCard: {
    flex: 1,
  },
  songDetailWritingRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  songDetailWritingCell: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  songDetailWritingRowStacked: {
    flexDirection: "column",
  },
  songDetailMiniCard: {
    minWidth: 0,
    paddingVertical: 10,
    gap: 6,
    marginBottom: 0,
    minHeight: 88,
  },
  songDetailMiniCardStandalone: {
    width: "100%",
    minHeight: 0,
  },
  songDetailMiniCardRow: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  songDetailMiniCardStacked: {
    flex: 0,
    width: "100%",
  },
  songDetailMiniCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailMiniCardTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  songDetailMiniCardTitle: {
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailMiniCardMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  songDetailMiniCardActionWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  songDetailMiniCardMetaText: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailMiniCardBody: {
    fontSize: 11.5,
    lineHeight: 16,
    color: "#64748b",
  },
  songDetailMiniCardActionText: {
    fontSize: 10,
    color: "#0f172a",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSummaryLinkCard: {
    minHeight: 60,
    paddingVertical: 10,
    gap: 4,
    justifyContent: "center",
  },
  songDetailSummaryLinkHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailSummaryLinkLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  songDetailSummaryLinkTitle: {
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailSummaryLinkMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  songDetailSummaryLinkMetaText: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSummaryLinkBody: {
    fontSize: 11.5,
    lineHeight: 15,
    color: "#64748b",
  },
  songDetailMiniCardButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  songDetailMiniCardButton: {
    minHeight: 30,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  songDetailMiniCardButtonText: {
    fontSize: 12,
    fontWeight: "700",
  },
  songDetailLyricsCard: {
    borderColor: "#dbe2ea",
    backgroundColor: "#fbfdff",
    minHeight: 0,
  },
  songDetailSectionEyebrow: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  lyricsSummaryCard: {
    marginBottom: 8,
  },
  lyricsScreenContent: {
    flexGrow: 1,
    gap: 10,
    paddingBottom: 24,
  },
  lyricsScreenContentKeyboard: {
    paddingBottom: 120,
  },
  lyricsVersionDocumentContent: {
    flexGrow: 1,
    gap: 10,
    paddingBottom: 28,
  },
  lyricsVersionDocumentContentEdit: {
    flex: 1,
    paddingBottom: 0,
  },
  lyricsVersionScreenBody: {
    flex: 1,
    paddingBottom: 28,
  },
  lyricsVersionDocumentFill: {
    flex: 1,
    minHeight: 0,
    paddingBottom: 16,
  },
  lyricsVersionDocumentFillEdit: {
    paddingBottom: 0,
  },
  lyricsVersionTopActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
    marginBottom: 8,
  },
  lyricsHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  lyricsHeaderText: {
    flex: 1,
    gap: 4,
  },
  lyricsInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    paddingRight: 18,
    fontSize: 15,
    lineHeight: 22,
    color: "#111827",
    textAlignVertical: "top",
    marginBottom: 20,
  },
  lyricsInputFill: {
    flex: 1,
    minHeight: 0,
    marginBottom: 0,
  },
  lyricsEditFieldActive: {
    borderColor: "#9ca3af",
    borderWidth: 2,
    borderStyle: "dashed",
  },
  lyricsPreviewWrap: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 160,
    marginBottom: 10,
  },
  lyricsPreviewWrapExpanded: {
    flex: 1,
    minHeight: 0,
  },
  lyricsPreviewWrapDocument: {
    marginBottom: 16,
  },
  lyricsScrollableWrap: {
    flex: 1,
    minHeight: 0,
    position: "relative",
    marginBottom: 0,
  },
  lyricsScrollIndicatorTrack: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 4,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.08)",
    overflow: "hidden",
  },
  lyricsScrollIndicatorThumb: {
    width: 4,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.38)",
  },
  lyricsActionBtn: {
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9,
  },
  lyricsActionBtnText: {
    fontSize: 11,
  },
  lyricsTimelineCard: {
    gap: 8,
  },
  lyricsTimelineCardPressable: {
    gap: 8,
  },
  lyricsVersionHeader: {
    gap: 8,
  },
  lyricsVersionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  lyricsVersionBadgePlaceholder: {
    minWidth: 100,
    minHeight: 28,
  },
  lyricsVersionToggleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  lyricsTimelinePreviewScroll: {
    height: 160,
  },
  lyricsVersionPreviewContent: {
    flexGrow: 1,
  },
  lyricsPreviewText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#111827",
  },
  playerLyricsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 8,
  },
  playerLyricsHeaderText: {
    flex: 1,
    gap: 4,
  },
  playerLyricsTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    color: "#0f172a",
  },
  playerLyricsMeta: {
    fontSize: 12,
    color: "#64748b",
  },
  playerLyricsSyncMeta: {
    fontSize: 11,
    color: "#2563eb",
    fontWeight: "600",
  },
  playerLyricsToggleBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  playerLyricsBody: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 12,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  playerLyricsScroll: {
    maxHeight: 140,
  },
  playerLyricsText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#111827",
  },
  playerUtilityBtn: {
    minHeight: 32,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#10b981",
    alignItems: "center",
    justifyContent: "center",
  },
  playerUtilityBtnSecondary: {
    backgroundColor: "#1e293b",
  },
  playerUtilityBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  playerUtilityBtnTextSecondary: {
    color: "#fff",
  },
  lyricsHistoryList: {
    marginTop: 10,
    gap: 10,
  },
  lyricsHistoryCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    backgroundColor: "#f9fafb",
    padding: 12,
    gap: 8,
  },
  progressWrap: {
    width: "100%",
    marginBottom: 8,
    gap: 6,
  },
  progressTrack: {
    width: "100%",
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
    overflow: "hidden",
  },
  progressInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  progressTrackInline: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#111827",
  },
  progressMeta: {
    fontSize: 12,
    color: "#4b5563",
    fontWeight: "600",
  },
  threadRowWrap: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  threadGuideWrap: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingRight: 4,
  },
  threadGuideLine: {
    width: 10,
    borderLeftWidth: 1,
    borderLeftColor: "#d1d5db",
    marginRight: 2,
  },
  threadCard: {
    flex: 1,
  },
  threadToggleBtn: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: "#f9fafb",
  },
  threadToggleText: {
    fontSize: 10,
    color: "#4b5563",
    fontWeight: "600",
  },
  primaryBtn: {
    backgroundColor: "#111827",
    borderRadius: 10,
    minHeight: 36,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { fontSize: 12, color: "white", fontWeight: "700", letterSpacing: 0.2 },
  recordBtn: {
    backgroundColor: "#0f766e",
    borderRadius: 12,
    minHeight: 40,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 4,
    marginBottom: 6,
  },
  songDetailSectionHeaderStack: {
    gap: 8,
  },
  songDetailSectionHeaderCopy: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    minWidth: 0,
  },
  songDetailSectionTitle: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  songDetailSectionMeta: {
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "700",
  },
  songDetailClipListHeader: {
    gap: 10,
  },
  songDetailClipSummarySection: {
    marginBottom: 4,
  },
  songDetailClipSection: {
    gap: 8,
  },
  songDetailStickyIdeasHeader: {
    backgroundColor: "#eef2f6",
    paddingTop: 4,
    paddingBottom: 6,
  },
  songDetailTimelineControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  songDetailTimelineMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    flexWrap: "wrap",
  },
  songDetailTimelineMetricChip: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailTimelineMetricChipActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  songDetailTimelineMetricChipText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  songDetailTimelineMetricChipTextActive: {
    color: "#ffffff",
  },
  songDetailTimelineDirectionChip: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  songDetailTimelineDirectionText: {
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  songDetailViewToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    padding: 3,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
  },
  songDetailViewToggleOption: {
    minHeight: 28,
    borderRadius: 13,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailViewToggleOptionActive: {
    backgroundColor: "#0f172a",
  },
  songDetailViewToggleText: {
    fontSize: 12,
    lineHeight: 14,
    color: "#475569",
    fontWeight: "700",
  },
  songDetailViewToggleTextActive: {
    color: "#ffffff",
  },
  songDetailTimelineDividerWrap: {
    paddingTop: 2,
    paddingBottom: 4,
  },
  songDetailRecordBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
  },
  songDetailVersionCard: {
    paddingVertical: 8,
    gap: 0,
  },
  songDetailVersionCardCompact: {
    paddingVertical: 6,
  },
  songDetailVersionRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  songDetailVersionLead: {
    width: 42,
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "stretch",
    flexShrink: 0,
  },
  songDetailVersionLeadInlineActive: {
    justifyContent: "center",
  },
  songDetailVersionLeadDurationSlot: {
    width: "100%",
    minHeight: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailVersionLeadDurationText: {
    fontSize: 11,
    lineHeight: 13,
    color: "#64748b",
    fontWeight: "600",
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  songDetailVersionMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  songDetailVersionTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  songDetailVersionTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  songDetailVersionRepliesToggle: {
    minHeight: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailVersionRepliesToggleText: {
    fontSize: 10,
    color: "#475569",
    fontWeight: "700",
  },
  songDetailVersionTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 17,
    color: "#0f172a",
    fontWeight: "700",
  },
  songDetailVersionTrailing: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    minHeight: 24,
  },
  songDetailVersionSetPrimaryBtn: {
    minHeight: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailVersionSetPrimaryText: {
    fontSize: 10,
    color: "#334155",
    fontWeight: "700",
  },
  songDetailVersionReplyBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  songDetailVersionReplyBtnCompact: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  songDetailVersionMeta: {
    fontSize: 10,
    lineHeight: 13,
    color: "#64748b",
    fontWeight: "600",
  },
  songDetailVersionNotes: {
    fontSize: 12,
    lineHeight: 17,
    color: "#64748b",
  },
  songDetailVersionInlinePlayerWrap: {
    marginTop: 3,
  },
  songDetailEvolutionGuideWrap: {
    position: "relative",
    alignSelf: "stretch",
    flexShrink: 0,
  },
  songDetailEvolutionStem: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "#dbe2ea",
  },
  songDetailEvolutionElbow: {
    position: "absolute",
    top: "50%",
    width: 12,
    height: 1,
    marginTop: -0.5,
    backgroundColor: "#cbd5e1",
    justifyContent: "center",
  },
  songDetailEvolutionDot: {
    position: "absolute",
    right: -3,
    top: -2,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "#94a3b8",
  },
  recordingBtn: { backgroundColor: "#dc2626" },
  recordBtnText: { color: "white", fontWeight: "700", letterSpacing: 0.2 },
  recordingTimer: { fontSize: 44, fontWeight: "700", color: "#111827", marginVertical: 10 },
  recordingTimerCompact: { fontSize: 34, marginVertical: 6 },
  recordingMetaCardCompact: {
    padding: 12,
    gap: 4,
  },
  liveWaveWrap: {
    marginTop: 10,
    marginBottom: 16,
    backgroundColor: "#eef0f3",
    borderRadius: 12,
    height: 280,
    justifyContent: "center",
    paddingHorizontal: 8,
    position: "relative",
    overflow: "hidden",
  },
  liveWaveWrapCompact: {
    height: 180,
    marginBottom: 12,
  },
  liveWaveRow: {
    height: 120,
    flexDirection: "row",
    alignItems: "center",
  },
  liveWaveHalfLeft: {
    flex: 1,
    height: 120,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 2,
  },
  liveWaveHalfRight: {
    flex: 1,
    height: 120,
  },
  liveWaveBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: "#111827",
  },
  livePlayhead: {
    position: "absolute",
    top: 18,
    bottom: 18,
    left: "50%",
    width: 2,
    marginLeft: -1,
    backgroundColor: "#ef4444",
  },
  recordingControlsBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  recordingControlsBarCompact: {
    gap: 12,
  },
  circleControlBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
  },
  circleControlBtnCompact: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  circleControlBtnActive: {
    borderWidth: 2,
    borderColor: "#111827",
    backgroundColor: "#f3f4f6",
  },
  circleControlBtnDisabled: {
    backgroundColor: "#f9fafb",
    borderColor: "#e5e7eb",
  },
  circleRecordBtn: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "#ef4444",
    borderWidth: 4,
    borderColor: "#fecaca",
    alignItems: "center",
    justifyContent: "center",
  },
  circleRecordBtnCompact: {
    width: 74,
    height: 74,
    borderRadius: 37,
  },
  circleRecordBtnActive: {
    borderColor: "#991b1b",
    borderWidth: 5,
  },
  controlGlyph: {
    fontSize: 24,
    color: "#374151",
    fontWeight: "700",
  },
  recordGlyph: {
    fontSize: 32,
    color: "#fff",
    lineHeight: 36,
  },
  backBtn: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    borderRadius: 10,
    minHeight: 36,
    minWidth: 36,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnText: { color: "#1f2937", fontWeight: "600" },
  ideasHeaderSelectBtn: {
    minHeight: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasHeaderSelectBtnText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  ideasHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasHeaderActionsPlaceholder: {
    width: 84,
  },
  ideasHeaderMenuBtnPlaceholder: {
    width: 32,
    height: 32,
  },
  ideasHeaderMenuBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee7",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasHeaderMenuLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    elevation: 10,
  },
  ideasHeaderMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  ideasHeaderOverflowMenu: {
    position: "absolute",
    top: 44,
    right: 0,
    minWidth: 188,
    zIndex: 2,
  },
  listContent: { paddingVertical: 10, gap: 8 },
  listContentTimeline: {
    paddingTop: 34,
  },
  listContentCompact: {
    gap: 5,
    paddingVertical: 6,
  },
  workspaceBrowseSection: {
    marginTop: 6,
    marginBottom: 8,
    gap: 8,
  },
  workspaceBrowseSectionTitle: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    paddingHorizontal: 4,
  },
  workspaceBrowseCollectionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workspaceBrowseCollectionActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: 8,
  },
  workspaceBrowseChildList: {
    gap: 8,
  },
  workspaceBrowseChildCard: {
    paddingVertical: 14,
    borderColor: "#d7e7fb",
    backgroundColor: "#f8fbff",
  },
  workspaceBrowseChildTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  workspaceBrowseChildTitleWrap: {
    flex: 1,
    gap: 8,
  },
  workspaceBrowseChildMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  workspaceBrowseChildChevron: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#d7e7fb",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  collectionBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  collectionBreadcrumbLink: {
    paddingVertical: 2,
  },
  collectionBreadcrumbText: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  collectionBreadcrumbTextActive: {
    color: "#334155",
    fontWeight: "700",
  },
  appBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 2,
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  appBreadcrumbItem: {
    paddingVertical: 2,
  },
  appBreadcrumbItemInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  appBreadcrumbText: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
    flexShrink: 1,
  },
  appBreadcrumbTextActive: {
    color: "#334155",
    fontWeight: "700",
  },
  subcollectionDisclosureWrap: {
    gap: 8,
    marginBottom: 10,
  },
  subcollectionDisclosureInlineWrap: {
    position: "relative",
    zIndex: 36,
    minWidth: 170,
    maxWidth: 220,
  },
  subcollectionDisclosureBtn: {
    minHeight: 38,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  subcollectionDisclosureBtnInline: {
    minHeight: 40,
    borderRadius: 20,
  },
  subcollectionDisclosureBtnOpen: {
    borderColor: "#cfd9e4",
    backgroundColor: "#f8fafc",
  },
  subcollectionDisclosureLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subcollectionDisclosureTitle: {
    fontSize: 13,
    lineHeight: 18,
    color: "#475569",
    fontWeight: "600",
  },
  subcollectionDisclosureList: {
    gap: 6,
    paddingLeft: 8,
  },
  subcollectionDisclosureDropdown: {
    position: "absolute",
    top: 46,
    left: 0,
    minWidth: 220,
    maxWidth: 260,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    padding: 8,
    gap: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 6,
  },
  subcollectionDisclosureItem: {
    minHeight: 34,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#fbfdff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  subcollectionDisclosureItemMain: {
    minHeight: 34,
  },
  subcollectionDisclosureItemLead: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subcollectionDisclosureItemActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  subcollectionDisclosureChevronBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  subcollectionDisclosureItemText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: "#334155",
    fontWeight: "600",
  },
  collectionInlineActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  activityRangeBanner: {
    marginBottom: 10,
    minHeight: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityRangeBannerCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activityRangeBannerText: {
    flex: 1,
    fontSize: 12,
    color: "#475569",
    fontWeight: "700",
  },
  activityRangeBannerClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  activityChipRow: {
    flexGrow: 0,
    marginBottom: 10,
  },
  activityChipScroll: {
    gap: 8,
    paddingRight: 8,
  },
  activityFilterChip: {
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activityFilterChipActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  activityFilterChipText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  activityFilterChipTextActive: {
    color: "#ffffff",
  },
  activityControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  activitySegmentWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    flex: 1,
  },
  activitySegmentBtn: {
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activitySegmentBtnActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  activitySegmentText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  activitySegmentTextActive: {
    color: "#ffffff",
  },
  activityYearControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activityYearBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  activityYearText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
    minWidth: 44,
    textAlign: "center",
  },
  activitySummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  activitySummaryText: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  activityHintText: {
    marginBottom: 10,
    fontSize: 11,
    color: "#64748b",
    fontWeight: "600",
  },
  activityLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  activityLegendLabel: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "600",
  },
  activityLegendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#dbe2ea",
  },
  activityScreenContent: {
    paddingBottom: 24,
    gap: 12,
  },
  activityCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 16,
    backgroundColor: "#ffffff",
    padding: 12,
    gap: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  activityHeatmapContent: {
    gap: 8,
  },
  activityMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 16,
    paddingLeft: 24,
  },
  activityMonthPressable: {
    minHeight: 16,
    justifyContent: "center",
  },
  activityMonthLabel: {
    position: "relative",
    fontSize: 10,
    color: "#64748b",
    fontWeight: "700",
  },
  activityMonthSummaryCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityMonthSummaryCopy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  activityMonthSummaryTitle: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "700",
  },
  activityMonthSummaryMeta: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
  },
  activityGridRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  activityWeekdayLabels: {
    width: 16,
    gap: 4,
    paddingTop: 1,
  },
  activityWeekdayLabel: {
    height: 14,
    fontSize: 9,
    color: "#94a3b8",
    textAlign: "center",
    includeFontPadding: false,
  },
  activityWeeksWrap: {
    flexDirection: "row",
    gap: 4,
  },
  activityWeekColumn: {
    gap: 4,
  },
  activityDayCell: {
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dbe2ea",
  },
  activityDayCellRangeSelected: {
    borderColor: "#1e3a8a",
    borderWidth: 2,
  },
  activityDayCellPressed: {
    transform: [{ scale: 0.94 }],
  },
  activityRangeSummaryCard: {
    borderWidth: 1,
    borderColor: "#dbe2ea",
    borderRadius: 16,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  activityRangeSummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityRangeSummaryCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  activityRangeSummaryTitle: {
    flex: 1,
    fontSize: 13,
    color: "#334155",
    fontWeight: "700",
  },
  activityRangeSummaryMeta: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  activityRangeSummaryClear: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  activityRangeScopedActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  activityRangeWorkspaceGroupList: {
    gap: 12,
  },
  activityRangeCollectionList: {
    gap: 8,
  },
  activityRangeCollectionCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  activityRangeCollectionCopy: {
    gap: 4,
  },
  activityRangeCollectionTitle: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  activityRangeCollectionMeta: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "600",
  },
  activityRangeCollectionActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  activityRangeCollectionCount: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "700",
  },
  activityRangeOpenBtn: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  activityRangeOpenBtnText: {
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "700",
  },
  activityDayModalCard: {
    gap: 10,
    maxHeight: "72%",
  },
  activityDayEntryScroll: {
    maxHeight: 340,
  },
  activityDayWorkspaceGroupList: {
    gap: 12,
    paddingBottom: 4,
  },
  activityDayWorkspaceGroup: {
    gap: 8,
  },
  activityDayWorkspaceTitle: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
    paddingHorizontal: 2,
  },
  activityDayEntryList: {
    gap: 8,
    paddingBottom: 4,
  },
  activityDayEntryCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  activityDayEntryTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  activityDayEntryTitleWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  activityDayEntryTitle: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    color: "#0f172a",
    fontWeight: "700",
  },
  activityDayEntryMetric: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "700",
  },
  activityDayEntryMeta: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "600",
  },
  activityDayModalActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  activityDayOpenBtn: {
    minHeight: 34,
  },
  activityDayCloseBtn: {
    minWidth: 90,
  },
  collectionMoveScroll: {
    maxHeight: 320,
  },
  collectionMoveScrollContent: {
    gap: 12,
    paddingTop: 10,
  },
  collectionMoveSection: {
    gap: 8,
  },
  collectionMoveOptionList: {
    gap: 6,
  },
  collectionMoveOption: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  collectionMoveOptionSelected: {
    borderColor: "#94a3b8",
    backgroundColor: "#f8fafc",
  },
  collectionMoveOptionCopy: {
    flex: 1,
    gap: 2,
  },
  collectionMoveOptionTitle: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "600",
  },
  collectionMoveOptionTitleSelected: {
    color: "#0f172a",
    fontWeight: "700",
  },
  collectionMoveOptionSubtitle: {
    fontSize: 11,
    color: "#64748b",
  },
  ideasListContentFloating: {
    paddingBottom: 178,
  },
  ideasListContentSelection: {
    paddingBottom: 168,
  },
  ideasListItemWrap: {
    gap: 6,
  },
  listRowWrap: { flexDirection: "row", alignItems: "stretch", gap: 6 },
  ideasSwipeActionsLeft: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
    paddingRight: 8,
    gap: 6,
  },
  ideasSwipePrimaryBtn: {
    minWidth: 44,
    width: 44,
    minHeight: 44,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasSwipeActionHide: {
    backgroundColor: "#f8fafc",
    borderColor: "#dbe2ea",
  },
  ideasSwipeSelectBtn: {
    minWidth: 94,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  ideasSwipeActionsRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingVertical: 6,
    paddingLeft: 8,
    gap: 6,
  },
  ideasSwipeActionBtn: {
    width: 44,
    minHeight: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  ideasSwipeActionShare: {
    backgroundColor: "#f8fafc",
    borderColor: "#dbe2ea",
  },
  ideasSwipeActionCopy: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  ideasSwipeActionMove: {
    backgroundColor: "#ecfeff",
    borderColor: "#a5f3fc",
  },
  ideasSwipeActionDelete: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
  },
  ideasSwipeActionText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  ideasDayDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 1,
  },
  ideasDayDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#dbe2ea",
  },
  ideasDayDividerText: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  ideasDayDividerActionBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasStickyDayWrap: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 25,
  },
  ideasStickyDayChip: {
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  ideasStickyDayChipText: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  cardFlex: { flex: 1 },
  selectionIndicatorHidden: { width: 0, marginRight: 0 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 14,
    gap: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    position: "relative",
  },
  transportLayout: {
    flex: 1,
  },
  transportHeaderZone: {
    gap: 12,
  },
  transportBodyZone: {
    flex: 1,
    position: "relative",
  },
  transportSurface: {
    flex: 1,
  },
  transportSurfaceWithFloating: {
    paddingBottom: 220,
  },
  transportScrollContent: {
    paddingBottom: 12,
  },
  transportScrollContentWithFloating: {
    paddingBottom: 220,
  },
  transportFloatingZone: {
    position: "absolute",
    right: 16,
    left: 16,
    bottom: 12,
  },
  transportFooterZone: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "#f8fafc",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  transportFooterCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe4f0",
    padding: 14,
    gap: 12,
  },
  transportFooterMeta: {
    gap: 2,
  },
  transportFooterEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: "#64748b",
  },
  transportFooterTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  transportFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  transportFooterButton: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
  },
  transportFooterButtonSecondary: {
    backgroundColor: "#e2e8f0",
  },
  transportFooterButtonDanger: {
    backgroundColor: "#b91c1c",
  },
  transportFooterButtonDisabled: {
    backgroundColor: "#cbd5e1",
  },
  transportFooterButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  transportFooterButtonTextSecondary: {
    color: "#0f172a",
  },
  cardDisabled: {
    opacity: 0.5,
  },
  selectionBadgeText: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
    textAlign: "center",
    textAlignVertical: "center",
  },
  selectionIndicatorCol: {
    width: 24,
    marginRight: 4,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  selectionIndicatorCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  selectionIndicatorActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  projectCard: {
    backgroundColor: "#f5f6f8",
    borderColor: "#d1d5db",
  },
  clipCard: {
    backgroundColor: "#ffffff",
    paddingVertical: 8,
    gap: 4,
    opacity: 0.97,
  },
  listCardRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  listCardMain: { flex: 1, gap: 2 },
  miniProgressWrap: {
    marginBottom: 4,
  },
  miniProgressTopDivider: {
    height: 1,
    borderRadius: 999,
    backgroundColor: "#e2e8f0",
    marginTop: 6,
    marginBottom: 6,
  },
  miniProgressTimes: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  miniProgressTime: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  miniProgressTrackHitbox: {
    justifyContent: "center",
    paddingTop: 4,
    paddingBottom: 12,
  },
  miniProgressTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
    overflow: "visible",
    position: "relative",
  },
  miniProgressFill: {
    height: "100%",
    backgroundColor: "#111827",
    borderRadius: 999,
  },
  miniProgressDot: {
    position: "absolute",
    top: 2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#111827",
    transform: [{ translateX: -5 }, { translateY: -5 }],
  },
  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  cardTitleRow: { flex: 1, flexDirection: "row", alignItems: "center", gap: 6 },
  cardTitle: { flex: 1, fontSize: 16, fontWeight: "600", color: "#0f172a" },
  cardMeta: { fontSize: 12, color: "#64748b" },
  recordingInputCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 14,
    gap: 10,
    marginBottom: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  recordingSettingsBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  recordingSettingsModalCard: {
    gap: 12,
  },
  recordingSettingsHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  recordingSettingsHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  recordingSettingsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
  },
  recordingSettingsMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: "#64748b",
  },
  recordingSettingsCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ea",
  },
  recordingInputHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  recordingInputHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  recordingInputTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  recordingInputMeta: {
    fontSize: 12,
    lineHeight: 17,
    color: "#64748b",
  },
  recordingInputRefreshBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ea",
  },
  recordingInputCurrentLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  recordingInputChipRow: {
    gap: 8,
    paddingRight: 8,
  },
  recordingInputChip: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  recordingInputChipActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  recordingInputChipDisabled: {
    opacity: 0.55,
  },
  recordingInputChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#374151",
  },
  recordingInputChipTextActive: {
    color: "#fff",
  },
  recordingInputHint: {
    fontSize: 12,
    lineHeight: 17,
    color: "#4b5563",
  },
  recordingInputDisabledNote: {
    fontSize: 12,
    color: "#0f766e",
    fontWeight: "600",
  },
  recordingInputError: {
    fontSize: 12,
    color: "#b91c1c",
    fontWeight: "600",
  },
  badge: {
    fontSize: 10,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontWeight: "700",
  },
  badgeCurrent: {
    backgroundColor: "#dcfce7",
    color: "#166534",
    overflow: "hidden",
  },
  statusSeed: { backgroundColor: "#e5e7eb" },
  statusSeedText: { color: "#374151" },
  badgeGhostProject: {
    backgroundColor: "#166534",
    color: "#ffffff",
    overflow: "hidden",
  },
  statusSprout: { backgroundColor: "#dbeafe" },
  statusSproutText: { color: "#1e40af" },
  statusSemi: { backgroundColor: "#fef3c7" },
  statusSemiText: { color: "#92400e" },
  statusSong: { backgroundColor: "#dcfce7" },
  statusSongText: { color: "#166534" },
  statusClip: { backgroundColor: "#f3f4f6" },
  statusClipText: { color: "#4b5563" },
  secondaryBtn: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: { fontSize: 12, color: "#334155", fontWeight: "600" },
  setPrimaryBtn: {
    alignSelf: "flex-start",
    marginTop: 2,
    borderWidth: 1,
    borderColor: "#9ca3af",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#fff",
    minWidth: 56,
  },
  setPrimaryBtnText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#374151",
    fontWeight: "700",
    textAlign: "center",
  },
  statusChipBtn: {
    alignSelf: "flex-start",
    borderWidth: 0,
    borderRadius: 8,
    minHeight: 34,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#fff",
    justifyContent: "center",
  },
  statusBtnActive: {
    borderColor: "#111827",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  pressDown: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  pressDownStrong: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },
  btnDisabled: { opacity: 0.5 },
  iconBtnText: { fontSize: 16, lineHeight: 18 },
  emptyText: { marginTop: 10, color: "#6b7280" },
  rowButtons: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
  ideasFabWrap: {
    position: "absolute",
    right: 18,
    bottom: 20,
    alignItems: "flex-end",
    gap: 10,
  },
  ideasNowPlayingDock: {
    marginBottom: 8,
    zIndex: 28,
  },
  ideasNowPlayingCard: {
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  ideasNowPlayingTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  ideasNowPlayingCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  ideasNowPlayingTitle: {
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasNowPlayingSubtitle: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "600",
  },
  ideasNowPlayingBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasNowPlayingProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasNowPlayingProgressTrack: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#e2e8f0",
    overflow: "hidden",
  },
  ideasNowPlayingProgressFill: {
    height: "100%",
    backgroundColor: "#0f172a",
  },
  ideasNowPlayingTimeText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#64748b",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
    minWidth: 34,
    textAlign: "center",
  },
  ideasUndoWrap: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 96,
    zIndex: 40,
  },
  ideasUndoCard: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#0f172a",
    backgroundColor: "#0f172a",
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasUndoText: {
    flex: 1,
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  ideasUndoBtn: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#94a3b8",
    backgroundColor: "#1e293b",
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasUndoBtnText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  globalInlineDockWrap: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 50,
  },
  globalInlineDockCard: {
    minHeight: 58,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 8,
  },
  globalInlineDockTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  globalInlineDockCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  globalInlineDockTitle: {
    fontSize: 12,
    lineHeight: 15,
    color: "#0f172a",
    fontWeight: "700",
  },
  globalInlineDockSubtitle: {
    fontSize: 11,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "600",
  },
  globalInlineDockCloseBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  globalInlineDockProgressTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: "#e2e8f0",
    overflow: "hidden",
  },
  globalInlineDockProgressFill: {
    height: "100%",
    backgroundColor: "#0f172a",
  },
  globalInlineDockTimesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  globalInlineDockTime: {
    fontSize: 10,
    lineHeight: 12,
    color: "#64748b",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  ideasFabMenu: {
    gap: 10,
    alignItems: "flex-end",
    marginBottom: 4,
  },
  ideasFabMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe2ea",
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  ideasFabMenuItemText: {
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasFabRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  ideasCreateFab: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe2ea",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  ideasRecordFab: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#d92d20",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7f1d1d",
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 6,
  },
  statusRowSpaced: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  navBar: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  selectionBar: {
    marginTop: 4,
    marginBottom: 8,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  songDetailClipList: {
    flex: 1,
  },
  songDetailClipListContent: {
    paddingTop: 0,
    paddingBottom: 28,
    gap: 6,
  },
  selectionText: { fontSize: 13, color: "#374151", fontWeight: "600" },
  ideasSelectionDock: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
  },
  ideasSelectionDockHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  ideasSelectionCount: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasSelectionHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ideasSelectionHeaderBtn: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#eef2f6",
    alignItems: "center",
    justifyContent: "center",
  },
  ideasSelectionHeaderBtnText: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "700",
  },
  ideasSelectionActions: {
    gap: 8,
    paddingRight: 6,
  },
  ideasSelectionAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 36,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe2ea",
  },
  ideasSelectionActionText: {
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasSelectionActionDanger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 36,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  ideasSelectionActionDangerText: {
    fontSize: 12,
    color: "#b91c1c",
    fontWeight: "700",
  },
  dangerBtn: {
    borderWidth: 1,
    borderColor: "#ef4444",
    backgroundColor: "#fee2e2",
    borderRadius: 8,
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 40,
  },
  dangerBtnDisabled: {
    borderWidth: 0,
    backgroundColor: "#f3f4f6",
  },
  dangerBtnText: { color: "#b91c1c", fontWeight: "700", fontSize: 14 },
  cardSelected: { borderColor: "#111827", borderWidth: 2 },
  listCardSelected: {
    borderColor: "#111827",
    borderWidth: 2,
    borderStyle: "dashed",
  },
  cardEditing: { borderColor: "#2563eb", borderWidth: 2 },
  cardHighlight: { borderColor: "#22c55e", borderWidth: 2 },
  cardHighlightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#dcfce7",
    borderRadius: 16,
  },
  clipRowWrap: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 4,
  },
  clipRowCard: {
    flex: 1,
  },
  ideasListLeadHotzone: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 76,
    zIndex: 4,
  },
  ideasListLeadHotzoneCompact: {
    width: 70,
  },
  ideasListLeadHotzoneExpanded: {
    width: 76,
  },
  ideasListCard: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#e6eaf0",
    paddingVertical: 7,
    paddingHorizontal: 11,
    position: "relative",
  },
  ideasListCardCompact: {
    borderRadius: 18,
    paddingVertical: 5,
    paddingHorizontal: 9,
  },
  ideasListProjectCard: {
    backgroundColor: "#fbfcfe",
  },
  ideasListCardNowPlaying: {
    borderColor: "#cbd5e1",
  },
  ideasListCardSelected: {
    borderColor: "#111827",
    borderWidth: 2,
    borderStyle: "dashed",
  },
  ideasHiddenCard: {
    backgroundColor: "#fbfcfe",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e8edf3",
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  ideasHiddenCardPressable: {
    flex: 1,
  },
  ideasHiddenRowInner: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  ideasHiddenTitleWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  ideasHiddenTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 15,
    color: "#475569",
    fontWeight: "500",
  },
  ideasHiddenUnhideBtn: {
    minHeight: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
  },
  ideasHiddenUnhideBtnText: {
    fontSize: 10,
    color: "#334155",
    fontWeight: "700",
  },
  ideasHiddenDayCard: {
    flex: 1,
    minHeight: 38,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e8edf3",
    backgroundColor: "#fbfcfe",
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasHiddenDayCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  ideasHiddenDayTitle: {
    fontSize: 12,
    lineHeight: 15,
    color: "#334155",
    fontWeight: "700",
  },
  ideasListCardHighlightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#dcfce7",
    borderRadius: 22,
  },
  ideasListExpandedStaticWrap: {
    gap: 3,
  },
  ideasListExpandedHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  ideasListExpandedHeaderLead: {
    width: 46,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
  },
  ideasListExpandedHeaderMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  ideasListExpandedMetaGrid: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  ideasListExpandedMetaRows: {
    gap: 1,
  },
  ideasListExpandedMetaGridRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ideasListExpandedMetaLeadSpacer: {
    width: 46,
    flexShrink: 0,
  },
  ideasListExpandedMetaLeftCol: {
    width: 46,
    minHeight: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListExpandedMetaCenterCol: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  ideasListExpandedMetaRightCol: {
    width: 72,
    gap: 1,
    flexShrink: 0,
  },
  ideasListCardRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  ideasListLeadCol: {
    width: 46,
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
    alignSelf: "stretch",
  },
  ideasListLeadColInlineActive: {
    justifyContent: "center",
  },
  ideasListLeadDurationSlot: {
    width: "100%",
    minHeight: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasListLeadDurationText: {
    fontSize: 12,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "600",
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  ideasListCardMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  ideasListCardMainCompact: {
    gap: 4,
  },
  ideasListCardTopBlock: {
    gap: 2,
    minWidth: 0,
  },
  ideasListCardBottomBlock: {
    gap: 1,
    minWidth: 0,
  },
  ideasListCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  ideasListCardTrailing: {
    alignItems: "flex-end",
    justifyContent: "flex-start",
    gap: 2,
    width: 72,
    flexShrink: 0,
  },
  ideasListCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    flex: 1,
    minWidth: 0,
  },
  ideasListCardTitleRowExpanded: {
    alignItems: "flex-start",
  },
  ideasListTitleIconWrap: {
    width: 14,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13.5,
    lineHeight: 17,
    color: "#0f172a",
    fontWeight: "700",
  },
  ideasListCardTitleCompact: {
    fontSize: 12.5,
    lineHeight: 15,
  },
  ideasListCardTitleHighlight: {
    backgroundColor: "#fde68a",
    color: "#0f172a",
    fontWeight: "800",
  },
  ideasSearchTagRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  ideasSearchTag: {
    borderWidth: 1,
    borderColor: "#dbe2ea",
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  ideasSearchTagText: {
    fontSize: 10,
    color: "#475569",
    fontWeight: "700",
  },
  ideasListCardMeta: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
  },
  ideasListCreatedAtText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#64748b",
    fontWeight: "500",
    fontVariant: ["tabular-nums"],
  },
  ideasListExpandedMetaStack: {
    gap: 1,
  },
  ideasListDateRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  ideasListDateStack: {
    gap: 2,
    flex: 1,
    minWidth: 0,
  },
  ideasListMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 14,
  },
  ideasListMetaLeftCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 14,
    flexShrink: 1,
    minWidth: 0,
  },
  ideasListMetaToken: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  ideasListMetaIconWrap: {
    width: 13,
    height: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  ideasListMetaDurationText: {
    fontSize: 13,
    lineHeight: 14,
    color: "#334155",
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaDurationTextCompact: {
    fontSize: 12,
    lineHeight: 13,
  },
  ideasListMetaText: {
    fontSize: 11,
    lineHeight: 13,
    color: "#64748b",
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  ideasListCompactProgressText: {
    fontSize: 11,
    lineHeight: 13,
    color: "#64748b",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaRightCol: {
    width: 72,
    alignItems: "flex-end",
    justifyContent: "center",
    flexShrink: 0,
  },
  ideasListMetaRightColInner: {
    width: "100%",
    alignItems: "flex-end",
    justifyContent: "center",
    minHeight: 14,
  },
  ideasListMetaRightCluster: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
    minHeight: 12,
  },
  ideasListMetaSizeText: {
    fontSize: 11,
    lineHeight: 14,
    color: "#64748b",
    fontWeight: "600",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasListDateSizeCol: {
    width: 72,
    alignItems: "flex-end",
    justifyContent: "center",
    flexShrink: 0,
    minHeight: 28,
  },
  ideasListDateSizeText: {
    fontSize: 10,
    lineHeight: 13,
    color: "#64748b",
    fontWeight: "500",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasListMetaSizeTextCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  ideasListMetaSeparator: {
    fontSize: 10,
    lineHeight: 12,
    color: "#94a3b8",
    fontWeight: "700",
  },
  ideasListStatusBadgeText: {
    fontSize: 9,
    lineHeight: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 46,
    textAlign: "center",
  },
  ideasListProgressText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#64748b",
    fontWeight: "600",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  ideasInlinePlayBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#dbe2ea",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  ideasInlinePlayBtnCompact: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  ideasListNowPlayingTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 2,
    backgroundColor: "#e2e8f0",
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    overflow: "hidden",
  },
  ideasListNowPlayingFill: {
    height: "100%",
    backgroundColor: "#0f172a",
  },
  ideasGhostProjectRow: {
    borderStyle: "dashed",
    borderColor: "#16a34a",
    borderWidth: 1,
    borderRadius: 22,
    backgroundColor: "#f5fff7",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  ideasGhostProjectIcon: {
    backgroundColor: "transparent",
    borderColor: "#16a34a",
  },
  primaryPickCol: {
    width: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    gap: 2,
    backgroundColor: "transparent",
  },
  primaryPickStarWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  primaryPickLabel: {
    fontSize: 8,
    fontWeight: "700",
    color: "#111827",
  },
  cardGhostProject: {
    borderStyle: "dashed",
    borderColor: "#16a34a",
    borderWidth: 2,
    backgroundColor: "#f0fdf4",
  },
  cardInsideHover: {
    transform: [{ scale: 1.02 }],
  },
  cardActiveInside: {
    transform: [{ scale: 0.97 }],
  },

  inlinePlayBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    marginTop: 2,
  },
  inlinePlayBtnText: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "700",
    marginLeft: 1,
  },

  inlinePlayerWrap: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 2,
    backgroundColor: "#ffffff",
  },
  // inlineTimes removed

  waveWrap: {
    marginTop: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 2,
  },
  waveBarsRow: {
    height: 64,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    paddingHorizontal: 2,
  },
  waveBar: { flex: 1, backgroundColor: "#cbd5e1", borderRadius: 6 },
  waveBarPlayed: { backgroundColor: "#111827" },
  playheadWrap: {
    position: "relative",
    height: 0,
  },
  playhead: {
    position: "absolute",
    top: -62,
    width: 2,
    height: 66,
    backgroundColor: "#ef4444",
    marginLeft: -1,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.25)",
    justifyContent: "center",
    padding: 20,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.25)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 14,
    gap: 1,
  },
  modalTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: "#0f172a",
    fontWeight: "700",
    marginBottom: 8,
  },
  collectionActionsModalCard: {
    gap: 10,
  },
  collectionActionsOptionList: {
    gap: 8,
  },
  collectionActionsOption: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  collectionActionsOptionDestructive: {
    borderColor: "#fecaca",
    backgroundColor: "#fff5f5",
  },
  collectionActionsOptionLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  collectionActionsOptionText: {
    fontSize: 14,
    lineHeight: 18,
    color: "#0f172a",
    fontWeight: "600",
  },
  collectionActionsOptionTextDestructive: {
    color: "#b91c1c",
  },
  bottomSheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.25)",
    justifyContent: "flex-end",
  },
  bottomSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  bottomSheetCard: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 10,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    marginHorizontal: 0,
    marginBottom: 0,
  },
  bottomSheetDragZone: {
    paddingBottom: 6,
  },
  bottomSheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#cbd5e1",
    marginBottom: 10,
  },
  clipActionsTitleBlock: {
    gap: 2,
    marginBottom: 8,
  },
  clipActionsSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: "#64748b",
    fontWeight: "500",
  },
  clipActionsOptionList: {
    gap: 6,
  },
  clipActionsOption: {
    minHeight: 42,
    borderRadius: 12,
  },
  ideasTitleModalCard: {
    gap: 8,
  },
  ideasTitleModalText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#0f172a",
    fontWeight: "600",
  },
});
