export type IdeaStatus = "seed" | "sprout" | "semi" | "song" | "clip";

export type Note = {
  id: string;
  title: string;
  body: string;
  createdAt: number;
  updatedAt: number;
  isPinned: boolean;
};

/** "Word Ladder" is a Jeff Tweedy-style writing exercise: pair a column of
 * role-verbs (or place-adjectives) against a column of nouns to spark odd,
 * unplanned lyric collisions. Lives in the global Lyrics Notebook alongside
 * Notes, not attached to a song unless the writer chooses to send a line on. */
export type WordLadderMode = "role" | "place";

export type WordLadderWord = {
  id: string;
  text: string;
};

export type WordLadderPairing = {
  id: string;
  columnAWordId: string;
  columnBWordId: string;
  locked: boolean;
};

export type WordLadderLine = {
  id: string;
  text: string;
  pairingId: string | null;
  starred: boolean;
};

export type WordLadderExercise = {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  mode: WordLadderMode;
  seedLabel: string;
  columnALabel: string;
  columnA: WordLadderWord[];
  columnB: WordLadderWord[];
  pairings: WordLadderPairing[];
  lines: WordLadderLine[];
};

export type BluetoothMonitoringCalibration = {
  routeKey: string;
  routeLabel: string;
  offsetMs: number;
  updatedAt: number;
};

export type EditActionType = "keep" | "remove";

export type EditRegion = {
  id: string;
  startMs: number;
  endMs: number;
  type: EditActionType;
};

export type ChordPlacement = {
  id: string;
  chord: string;
  at: number;
};

export type LyricsLine = {
  id: string;
  text: string;
  chords: ChordPlacement[];
};

export type LyricsDocument = {
  lines: LyricsLine[];
};

export type LyricsVersion = {
  id: string;
  createdAt: number;
  updatedAt: number;
  document: LyricsDocument;
};

export type ProjectLyrics = {
  versions: LyricsVersion[];
};

export type PracticeMarker = {
  id: string;
  label: string;
  atMs: number;
  /** Optional free-text note ("try minor IV here"). */
  note?: string;
};

export type ClipSectionKind =
  | "intro"
  | "verse"
  | "prechorus"
  | "chorus"
  | "bridge"
  | "solo"
  | "outro"
  | "custom";

/** A labelled span of a clip's structure (verse, chorus, …). Each section has an explicit
 *  start and end; sections never overlap but may leave gaps between them. `color` is only
 *  set for custom sections (presets derive their colour from the kind). Legacy sections
 *  stored without `endMs` are backfilled on load (see normalizeSections). */
export type ClipSection = {
  id: string;
  startMs: number;
  endMs: number;
  label: string;
  kind: ClipSectionKind;
  color?: string;
};

export type MusicalMode = "major" | "minor";

/** Cached result of offline key/tempo detection for a clip. */
export type ClipAnalysis = {
  schemaVersion: number;
  analyzedAt: number;
  /** Tonal centre label, e.g. "E♭" / "F♯". null when detection was inconclusive. */
  key: string | null;
  mode: MusicalMode | null;
  /** 0..1 — separation between the winning key and the runner-up. */
  keyConfidence: number;
  /** Detected tempo (BPM), rounded. null when inconclusive. */
  bpm: number | null;
  /** 0..1 — how steady the tempo is; gates the steady click / count-in. */
  bpmSteadiness: number;
  /** Set once the user confirms or overrides the suggestion. */
  confirmed?: boolean;
};

export type ClipOverdubTonePreset = "neutral" | "low-cut" | "warm" | "bright";

export type ClipOverdubRootSettings = {
  gainDb: number;
  tonePreset: ClipOverdubTonePreset;
};

export type ClipOverdubStem = {
  id: string;
  title: string;
  audioUri?: string;
  gainDb: number;
  offsetMs: number;
  tonePreset: ClipOverdubTonePreset;
  isMuted: boolean;
  durationMs?: number;
  waveformPeaks?: number[];
  createdAt: number;
};

export type ClipOverdubState = {
  root?: ClipOverdubRootSettings;
  stems: ClipOverdubStem[];
  renderedMixUri?: string;
  renderedMixDurationMs?: number;
  renderedMixWaveformPeaks?: number[];
  lastRenderedAt?: number;
};

export type ClipVersion = {
  id: string;
  title: string;
  /** True when the title was auto-generated (naming system) and has not been manually edited.
   *  Used to decide which child clips to offer renaming when a parent is renamed. */
  isTitleAutoGenerated?: boolean;
  notes: string;
  createdAt: number;
  importedAt?: number;
  sourceCreatedAt?: number;
  isPrimary: boolean;
  parentClipId?: string;
  /** Time this clip was attached to its current lineage parent. Falls back to createdAt for older clips. */
  parentAssignedAt?: number;
  audioUri?: string;
  sourceAudioUri?: string;
  durationMs?: number;
  waveformPeaks?: number[];
  editRegions?: EditRegion[];
  tags?: string[];
  isBookmarked?: boolean;
  practiceMarkers?: PracticeMarker[];
  sections?: ClipSection[];
  analysis?: ClipAnalysis;
  manualSortOrder?: number;
  overdub?: ClipOverdubState;
};

export type CustomTagDefinition = {
  key: string;
  label: string;
  color: string;
};

export type ClipGroup = {
  id: string;
  name: string;
  collapsed: boolean;
  createdAt: number;
  updatedAt: number;
};

export type SongIdea = {
  id: string;
  title: string;
  notes: string;
  status: IdeaStatus;
  completionPct: number;
  kind: "project" | "clip";
  collectionId: string;
  clips: ClipVersion[];
  lyrics?: ProjectLyrics;
  customTags?: CustomTagDefinition[];
  clipGroups?: ClipGroup[];
  clipGroupAssignments?: Record<string, string>;
  createdAt: number;
  importedAt?: number;
  sourceCreatedAt?: number;
  lastActivityAt: number;
  isDraft?: boolean;
  isBookmarked?: boolean;
};

export type PlaybackQueueItem = { ideaId: string; clipId: string };
export type PlayerTarget = PlaybackQueueItem | null;
export type InlineTarget = { ideaId: string; clipId: string } | null;
export type TransportScreenKind = "recording" | "player" | "editor";
export type TransportInteractionZone = "header" | "surface" | "footer" | "floating";
export type LyricsAutoscrollMode = "off" | "follow" | "manual";
export type LyricsAutoscrollState = {
  mode: LyricsAutoscrollMode;
  currentTimeMs: number;
  durationMs: number;
  activeLineId?: string | null;
};

export type IdeasTimelineMetric = "created" | "updated";

export type ActivityMetric = "created" | "updated";
export type ActivitySource =
  | "recording"
  | "import"
  | "song-save"
  | "lyrics-save"
  | "audio-edit"
  | "history-seed";
export type ActivityIdeaKind = "song" | "clip";

export type ActivityEvent = {
  id: string;
  at: number;
  workspaceId: string;
  collectionId: string;
  ideaId: string;
  ideaKind: ActivityIdeaKind;
  ideaTitle: string;
  clipId?: string | null;
  metric: ActivityMetric;
  source: ActivitySource;
};

export type IdeasHiddenDay = {
  metric: IdeasTimelineMetric;
  dayStartTs: number;
};

export type IdeasListState = {
  hiddenIdeaIds: string[];
  hiddenDays: IdeasHiddenDay[];
};

export type WorkspaceHiddenDay = IdeasHiddenDay;
export type WorkspaceIdeasListState = IdeasListState;

export type WorkspaceArchiveState = {
  schemaVersion: number;
  archivedAt: number;
  archiveUri: string;
  packageSizeBytes: number;
  originalAudioBytes: number;
  originalMetadataBytes: number;
  archivedMetadataBytes: number;
  savingsBytes: number;
  audioFileCount: number;
  missingFileCount: number;
};

export type Collection = {
  id: string;
  title: string;
  description?: string;
  workspaceId: string;
  parentCollectionId?: string | null;
  createdAt: number;
  updatedAt: number;
  ideasListState: IdeasListState;
};

export type Workspace = {
  id: string;
  title: string;
  description?: string;
  color?: string;
  avatarKey?: number;
  isArchived?: boolean;
  archiveState?: WorkspaceArchiveState;
  collections: Collection[];
  ideas: SongIdea[];
  ideasListState?: WorkspaceIdeasListState;
};

export type WorkspaceStartupPreference = "primary" | "last-used";
export type WorkspaceListOrder = "last-worked" | "least-recent" | "title-az" | "title-za";
export type BackupReminderFrequency = "off" | "weekly" | "monthly" | "quarterly";

export type PlaylistItemKind = "song" | "clip";

export type PlaylistItem = {
  id: string;
  kind: PlaylistItemKind;
  workspaceId: string;
  collectionId: string;
  ideaId: string;
  clipId?: string | null;
  addedAt: number;
};

export type Playlist = {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  items: PlaylistItem[];
};

export type PlayerState = {
  target: PlayerTarget;
  isPlaying: boolean;
  isLoaded: boolean;
  isLooping: boolean;
  position: number;
  duration: number;
};

export type InlinePlayerSnapshot = {
  inlineTarget: InlineTarget;
  inlinePosition: number;
  inlineDuration: number;
  isInlinePlaying: boolean;
};

export type InlinePlayerControls = {
  getSnapshot: () => InlinePlayerSnapshot;
  toggleInlinePlayback: (ideaId: string, clip: ClipVersion) => Promise<void>;
  beginInlineScrub: () => Promise<void>;
  endInlineScrub: (ms: number) => Promise<void>;
  cancelInlineScrub: () => Promise<void>;
  seekInline: (ms: number) => Promise<void>;
  resetInlinePlayer: () => Promise<void>;
};

export type InlinePlayer = InlinePlayerSnapshot & InlinePlayerControls;

export type IdeasFilter = "all" | "clips" | "projects" | "bookmarked";
export type IdeaSort =
  | "newest"
  | "oldest"
  | "updated-newest"
  | "updated-oldest"
  | "title-az"
  | "title-za"
  | "duration-long"
  | "duration-short"
  | "completion-high"
  | "completion-low";

/**
 * @description Type definition for the clipboard content. This is a type, not a component.
 */
export type ClipClipboard = {
  mode: "copy" | "move";
  itemType: "clip" | "project" | "mixed";
  sourceWorkspaceId: string;
  sourceCollectionId?: string;
  sourceIdeaId?: string;
  clipIds: string[];
  from: "list" | "project";
};
